klee/klee

- lib/Expr/ExprSMTLIBPrinter.cpp
than writing "(not (= a b))". This makes the code simpler and queries
slightly simpler.
> Teach ExprSMTLIBPrinter to use SMTLIBv2's distinct function rather

- include/klee/Expr.h
- lib/Core/Executor.cpp
- lib/Core/Memory.cpp
- lib/Expr/Expr.cpp
- lib/Expr/Parser.cpp
- lib/SMT/SMTParser.cpp
- unittests/Expr/ExprTest.cpp
- unittests/Solver/SolverTest.cpp
This pull is a smaller version of the larger pull request "PreviousPointAndQuickCache".  It was requested by @ccadar in order to make verification of the larger commits easier.
In order to be included in the mainline, the following changes were requested
1) Would it be possible to add a test that shows the aliasing issues, and how with this commit resolves it? I think this would be an interesting test to have in the regression suite.
Such a test case actually already exists.  Running Dogfood/ImmutableSet.cpp in the test suite will exercise this change. I cannot, however, create a test case that actually proves the the prior version was incorrect.  The reason for this is the previous version is safe, but missed opportunities for matching.  If you examine the input …
> Added factory method for Arrays + hid constructors from outside calls

- lib/Core/Executor.cpp
Previously, KLEE was only warning about killing states if MaxMemoryInhibit was set to true.
Still, states were silently killed if memory limit was provided.
This patch changes the behavior to always warn in case states are killed
> [Core] Always warn if states get deleted due to memory limits

- include/klee/Internal/System/Time.h
- lib/Core/TimingSolver.cpp
- lib/Support/Time.cpp
- lib/Support/Timer.cpp
Related to #207 
For getting timestamps, KLEE was using LLVM's GetTimeUsage(now,user,sys) everywhere, despite that user and sys times aren't needed almost anywhere. This call uses getrusage() for user and sys times and is thus 10x more expensive than TimeValue::now()/gettimeofday()/clock_gettime(CLOCK_MONOTONIC) and 30x more expensive than clock_gettime(CLOCK_MONOTONIC_COARSE).
This patch adds the util::getWallTimeVal() function that uses LLVM's TimeValue::now() method (which uses gettimeofday() internally; i.e. it is not monotonic). The util::getWallTime() function and all places in the code that used the previous, inefficient timestamps have been updated to use util::getWallTimeVal().
As before, util::getWallTime() returns a double timestamp and is suitable only for cases where high …
> Cleaner, more efficient timestamps

- Makefile.config.in
- autoconf/configure.ac
- configure
ignore the C++ compiler detected and just use the compiler detected
during the LLVM configure.
> Fix very annoying issue where KLEE's configure would completly

- lib/Core/Executor.cpp
- test/Feature/PreferCex.c
Previously, default Klee would go through every byte in a test case
and attempt to bound it to be between 0 and 127, making it human
readable.  While this may be useful when initially attempting to 
understand Klee, it also means that the time required to create large
test suites was greatly increased.  By making this behavior default off, 
unsuspecting users won't incur these costs.
When tested on the core-utils suite, I noticed a 3-4X drop for the default
search (i.e. when all paths produce a tests case).  Given the relatively
small benefits of the option (I almost never look directly at a test case)
it seems like it would be much better to make this behavior opt in rather
than opt out. Should you guys decide that it is important for new users to
be able to examine and understand the …
> Make creation of human readable test cases optional rather than default

- lib/Solver/CexCachingSolver.cpp
The super-set check in the CexCachingSolver takes MUCH longer than the
sub-set check.  Upon closer inspection, the super-set check gets slower
and slower as more counterexamples fill the UBTree.  Pretty quickly,
the cost of the super-set check becomes larger than the time required
to simply bypass it and go to the Solver.
In the original implementation, the UBTree checks for both supersets and subsets of an incoming constraint set.  The sub-set query is very efficient, taking on average under than 1% of the overall computation.  The super-set query, however, is much less efficient.  Over the course of a run, it can account for up to 79% of the computation while on average taking up 44% of the computation.
The reason for this inefficiency is because when more and more constraint sets are …
> Make the super-set check in CexCachingSolver default off

- include/klee/util/Assignment.h
- lib/Solver/IndependentSolver.cpp
The previous implementation simply passes the entire constraint forward
without any factoring of the constraint at all. This is a problem
since it is highly likely that there are cached solutions to pieces
of the constraint. The new implementation breaks the entire
constraint down into its requisite factors and passes each piece
forward, one by one, down the solver chain. After an answer is
returned, it is integrated into a larger solution. Since, by
definition, no factor can affect another, we can safely create a
solution to the larger constraint from the answers of its smaller
pieces.
After completion, the changes:
1) Pass all provided tests (other than ones that were expected to fail)
2) Have been verified via -debug-validate-solver by a complete run through of 9 members of the …
> Independent solver get initial values

- lib/Module/ModuleUtil.cpp
- test/Feature/BitcastAliasMD2U.ll
It failed when the function being called is an alias.
> Fix assertion failure in getDirectCallTarget

- lib/Solver/STPBuilder.cpp
- test/regression/2015-08-30-sdiv-1.c
Division by constant divisor get optimized
using shift and multiplication operations in STP builder.
The used method cannot be applied for divisor 1 and -1.
In that case we will use the normal division operator.
> Fix signed division by constant 1/ -1

- test/Runtime/POSIX/Futimesat.c
This caused problems on our shared machine where multiple users were building/running the
KLEE tests.
> Don't use /tmp for futimesat unit test

- lib/Solver/STPBuilder.cpp
- test/Feature/srem.c
The '%' operater in C is not Gauss Modulo
but remainder operations.
Using a negative number as right operand
can result in a negative number.
Fix appropriate SRem building
Note: MetaSMTlib implementation doesn't have that bug.
Fixes #261
> [STPBuilder] Generate SRrem expressions correctly

- Makefile.common
It's not supported and breaks compilation. This affects in particular
Debian Jessie and probably all derived distros, too
> Removing -fstack-protector-strong for clang <= 3.4

- include/klee/Expr.h
- lib/Expr/Updates.cpp
- utils/sanitizers/lsan.txt
The overloaded assignment operator previously only deleted the head
``UpdateNode`` if the ``UpdateList`` had exclusive ownership which left the remaining
list of ``UpdateNode``s dangling if those nodes had ``refCount`` of 1.
To fix this the logic that was previously in the ``UpdateList`` destructor
for deleting nodes that were exclusively referenced by the UpdateList
has been moved into ``UpdateList::tryFreeNodes()`` so that it can be
called from ``UpdateList::operator=()``.
It looks like this bug has been in KLEE since the beginning.
Unlike #315 which fixes a benign leak, this leak is **not** benign.
> Fix a memory leak in ``UpdateList`` detected by AddressSanitizer.

- lib/Module/IntrinsicCleaner.cpp
- test/Intrinsics/objectsize.ll
- test/Intrinsics/objectsize.llvm29.ll
- test/lit.cfg
introduced in LLVM 2.7. Previously KLEE would emit the following error
message when ``IntrinsicLowering::LowerIntrinsicCall()`` was called on
the intrinsic
```
LLVM ERROR: Code generator does not support intrinsic function 'llvm.objectsize.i64.p0i8'!
```
The ``IntrinsicCleaner`` pass now lowers this intrinsic to a constant
integer depending on the second argument to the intrinsic. This
corresponds to the case where the size of the object pointed to by the
first argument is unknown.
An alternative design would be to handle this intrinsic in the Executor
where is actually possible to know the size of objects during execution.
However that would be much more complicated because if the pointer is
symbolic we would have to fork for every object that could be pointed
to.
The implementation is …
> Implement support for lowering the ``llvm.objectsize`` intrinsic

- .clang-format
The entry is incompatible to Clang 3.4.2 which does not support `Language:` configuration key. With the `Language: Cpp` entry in `.clang-format` the `git clang-format` would say:
```
YAML:2:11: error: unknown key 'Language'
Language: Cpp
^~~
Error reading /home/dcsandr/software/klee/.clang-format: Invalid argument
Can't find usable .clang-format, using LLVM style
```
> Removed Language: Cpp Entry from .clang-format

- lib/Module/ModuleUtil.cpp
CallInst::getOperand() uses incompatible operand orders across LLVM versions. Use CallSite::hasArgument() instead. This bug prevented the MD2U searcher from working correctly.
> Fix valueIsOnlyCalled() used by MD2U.

- test/Feature/LinkLLVMLib.c
- tools/klee/main.cpp
This allows a user to invoke klee with specific libraries to load from
command line. This is an attempt to allow klee to run on applications
linked to external libraries.
The libraries still have to be compiled specially for klee, in a manner
similar to klee-uclibc, i.e. archives (build with llvm-ar) of llvm IR
files.
> Added support to load libraries from command line

- .travis.yml
- autoconf/configure.ac
- configure
- include/klee/Config/config.h.in
- runtime/POSIX/selinux.c
Fixes https://github.com/klee/klee/issues/303:
The SELinux function signatures have changed between version 2.2 and
2.3. In particular, the type of the "security context" parameters were
changed from char * to const char *, with the following patch:
https://github.com/SELinuxProject/selinux/commit/9eb9c9327563014ad6a807814e7975424642d5b9.
Recent Linux distributions (e.g., Ubuntu 15.10) ship with the updated
version of libselinux. This PR makes the runtime compatible with these
changes by replacing security_context_t typedef with its original char *
definition and defining it as const only if the installed library does
so. Whether the systems library uses const char * type is detected with 
the configure script.
> Fix SELinux signatures in runtime

- include/klee/Expr.h
Fix incorrect position of ``Not`` in ``Expr::Kind`` which meant it was included
in the range of ``BinaryKindFirst`` and ``BinaryKindLast``. ``NotExpr``
is a unary expr not a binary expression.
> Fix incorrect position of ``Not`` in ``Expr::Kind``

- lib/Module/PhiCleaner.cpp
Wrong std::vector 'values' usage after vector's capacity reserve. It is the error to use [] operator for accessing vector's elements after reserving operation. In such cases push_back/emplace methods should be used. But in this source code the usage of std::vector is redundant. So vector 'values' was iliminated.
> Wrong std::vector usage after reserve() call.

- runtime/Runtest/Makefile
Based on llvm-shlib/Makefile
SHARED_VERSION reflects the API version of the library itself
Should fix #237
> Add soname for Runtest dynamic library

- include/klee/Interpreter.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- test/Coverage/ReplayOutDir.c
- tools/klee/main.cpp
I was reading the code that lets KLEE replay ``.ktest`` files within its interpreter (rather than natively using the ``libkleeRuntest``) and I realised the names were kind of messed up. I guess at some point in time ``.ktest`` files used be called ``.out`` files maybe? Either way generated test cases are now called ``ktest`` files so the command line options and variable names should reflect this.
This PR attempts to fix this. After merging this we should also update the documentation describing how KLEE can be instructed to replay ``.ktest`` files.
> Refactor use of the name "outFile" to "KTest"

- lib/Core/Executor.cpp
Remove computation of ``isLocal`` that is always true when handling AllocaInst.
> Remove computation of ``isLocal`` that is always true when handling

- tools/klee/main.cpp
The PR removes the local variable `infoFile` and instead writes to the stream by directly invoking the handler->getInfoStream() method.
The commit unifies how we handle the writes on the `info` file: in half of the method the `infoFile` variable was used, while in the other half `handler->getInfoStream()` was used instead.
> Small refactoring to improve the consistency of info file handling

- lib/Solver/QueryLoggingSolver.cpp
- lib/Solver/QueryLoggingSolver.h
If solver segfault, requests won't get logged. This PR allows to log the solver requests before they get resolved. After the solver call, results are logged are appended.
Flushing the buffer twice per request might have a negative performance impact, therefore it is disabled by default.
> Partial logging of requests

- lib/Solver/IndependentSolver.cpp
- test/regression/2016-03-22-independence-solver-missing-objects-for-assignment.kquery
- test/regression/lit.local.cfg
The problem was that ``assertCreatedPointEvaluatesToTrue()`` used in the
IndependentSolver assumed that it would be given an assignment for every
array. If this wasn't the case the ``Assignment`` object by default
would just replace every read of an unknown array with a byte filled
with zeros.
This problem would appear if
``IndependentSolver::getInitialValues(...)`` was called without asking
for assignment for used arrays.
I saw two ways of fixing this
* Get an assignment for all arrays even if the client didn't ask
for them. This guarantees that
we can compute a concrete assignment.
* Just do a "best effort" check and only check expressions that can
be fully assigned to.
I chose the latter because the first option seems pretty wasteful,
especially for an assert.
The second option isn't …
> Try to fix #348

- include/klee/Internal/Module/KInstIterator.h
The "rule of three" of `KInstIterator` class is synthesized version. The `KInstIterator` isn't deep copy, so it's redundant to write them explicitly.
> remove synthesized `rule of three` of KInstIterator

- .travis.yml
Workaround for #390 until we phase out LLVM 2.9 support.
> Add newer cmake 2.8.11 from external ppa repository

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- test/Feature/LoggingInstructions.c
-debug-print-instructions can now be invoked with 4 different values:
1) all:stderr,   which logs all instructions to stderr;
2) all:file,     which logs all instructions to file in format [src, inst_cntr, inst_id, llvm_inst];
3) src:file,     which logs all instructions to file in format [src, inst_cntr, inst_id];
4) compact:file, which logs all instructions to file in format [inst_cntr, inst_id];
Writing to file gives a speedup of ~50x.
Changes made mainly by @MartinNowack.
> Modified -debug-print-instructions to write directly on log file.

- tools/klee/main.cpp
This trivial change allows relocation of an  installed klee tree.
For example, if klee is configured with bindir /usr/bin, and with runtime dir /usr/lib/klee/runtime,
but klee is called from, for example, /home/user/klee/usr/bin/klee, it will find and use runtime in /home/user/klee/usr/lib/klee/runtime, instead of global /usr/lib/klee/runtime.
It will use global runtime directory only when installed to global binary directory.
Inspired by relocation code in gcc.
> Allow relocation of installed klee tree

- runtime/POSIX/fd.h
- runtime/POSIX/fd_init.c
- runtime/POSIX/klee_init_env.c
- test/Runtime/POSIX/Isatty.c
- test/Runtime/POSIX/Stdin.c
Currently, it is not transparent the way a symbolic stdin is created in KLEE: it is implicitly done whenever `--sym-file` is specified and the length of the symbolic file is used.
I have split the `--sym-file` option in two:
1. `--sym-file <NUM> <LEN>` that creates symbolic files only (as usual)
2. `--sym-stdin <LEN>` that creates a stdin of maximum size LEN
In this way they can be used explicitly and independently.
I commit both the code and the tests that are touched by the modifications.
> Distinct options for symbolic files and symbolic stdin

- include/expr/Parser.h
- lib/Expr/Parser.cpp
- test/Solver/2016-04-12-array-parsing-bug.kquery
- tools/kleaver/main.cpp
We now update the references to array declarations, and we use all of them to solve the query.
Added the new option --clear-array-decls-after-query to discard all the array declarations instead of updating them (default: disabled for backward compatibility).
Added regression test case to test/Solver.
> Fixed bug #375 in Kleaver's parser

- .travis.yml
- .travis/install-llvm-and-runtime-compiler.sh
Use alternativ PPA for LLVM packages which are build using the debian package description.
> Fix Travis CI build - use alternative ppa for LLVM

- tools/klee/main.cpp
A very small refactoring to improve the error string with -run-in option.
It helped me a lot to understand what kind of error I was encountering.
> Added string for -run-in directory errors

- Dockerfile
This fixes an issue related to the PATH used by docker run, that is different than the one used by bash.
This allows to run docker run klee/klee klee FILE.o directly.
> Dockerfile: link binaries to /usr/bin

- lib/Core/Executor.cpp
- lib/Core/StatsTracker.cpp
Use `stats-write-after-instructions` to dump klee statistics after
every n instructions. This is disabled by default
Be aware, `stats-write-interval` is enabled by default.
If both features are enabled, statistics are written every n
instructions and every m seconds to the same file.
> Add option to dump statistics every n instructions

- lib/Core/AddressSpace.cpp
- lib/Core/ExecutionState.cpp
- lib/Core/Executor.cpp
- lib/Core/MemoryManager.cpp
- lib/Core/MemoryManager.h
- lib/Core/StatsTracker.cpp
As KLEE depends on external allocators, the
memory allocated can be random from run to run.
This behavior can make it impossible to compare
runs of the same benchmark even a deterministic
searcher was used.
This patch provides a deterministic (mmap-based)
allocator, which assures that allocations from
the benchmark are done the same way for every run.
> Add support for deterministic allocation

- lib/Core/MemoryManager.cpp
Allows to provide 0 as an address to allocate the deterministic memory area at
any free space.
> Fix parsing of deterministic address.

- lib/Core/Executor.cpp
- test/Feature/NonSizedGlobals.c
Sometimes, globals are not sized and ->getTypeStoreSize on such type
crashes inside the LLVM. Check whether type is sized prior to calling
the function above.
A minimalistic example of Y being unsized with no effect on the actual
code is put to tests.
Signed-off-by: Jiri Slaby <jslaby@suse.cz>
> Executor: do not crash on non-sized globals

- lib/Support/MemoryUsage.cpp
The mallinfo() interface is ill-designed. It returns 'int' as occupied
memory. This means at most 2G. This causes troubles when capping the
memory to 3G by -max-memory=3000 for example.
We cannot fix the interface, but we can at least extend the space to
4G. So cast those 'int's to 'unsigned int's to avoid sign extension.
Then do the addition on 'size_t' to count on 64bit values (on 64 bit).
Apart from that, the original 'int' + 'int' lead to overflow which is
undefined on 'signed int's in C.
Signed-off-by: Jiri Slaby <jslaby@suse.cz>
> MemoryUsage: handle ill-designed mallinfo

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/SpecialFunctionHandler.cpp
- test/Feature/ExitOnErrorType.c
It allows stopping the execution on some conditions like assertions.
The use is like:
klee -exit-on-error-type=Assert -exit-on-error-type=External file.llvm
This is especially useful in the SV-COMP.
A test to cover the new parameter was added too.
Signed-off-by: Jiri Slaby <jslaby@suse.cz>
> klee: add exit-on-error-type parameter

- tools/klee/main.cpp
Use LLVM-based functions to print errno. Compiles on both LLVM 3.4 and LLVM 2.9.
Thanks to @MartinNowack
> Fix to #449

- lib/Core/PTree.cpp
In PTree::remove we delete the memory pointed by `n` at line 40 but then we use the same pointer inside the `if` at lines 41 and 45. As far as I know this is undefined behavior.
> Fix to PTree pointer use-after-delete

- Dockerfile
This is a suggested fix to #461 in order to let Klee Web run the coverage report.
> [Klee Web] Link libkleeRuntest library to fix coverage report

- runtime/POSIX/klee_init_env.c
Should fix misunderstandings on the POSIX write operations like the one in #411.
If accepted I will update the website accordingly.
> Document -save-all-writes to klee_init_env help message

- .travis/testing-utils.sh
GTest has moved from googlecode to GitHub so update URL and directory
name used in source archive as appropriate.
> Try to unbreak the TravisCI and Docker builds.

- include/klee/CommandLine.h
- include/klee/Internal/Support/ErrorHandling.h
- lib/Basic/CmdLineOptions.cpp
- lib/Basic/ConstructSolverChain.cpp
- lib/Solver/CoreSolver.cpp
Now that we have better support multiple solvers it is possible to cross check the core solver against another. This PR adds support for doing this using the new ``-debug-cross-check-core-solver=`` option.
Practically I see this being useful to cross check STP and Z3.
> Allow cross checking of solvers

- include/klee/Interpreter.h
- lib/Module/KModule.cpp
- lib/Module/Optimize.cpp
- test/regression/2016-08-11-entry-point-internalize-pass.c
- tools/klee/main.cpp
This PR aims to fix #454.
I solved the issue by refactoring the ModuleOpt struct, and adding an EntryPoint string. The field is then used as parameter of the internalizePass.
Looking forward for your comments.
> Avoid internalization of non-standard entry points (fix to #454)

- lib/Basic/ConstructSolverChain.cpp
- lib/Core/Executor.cpp
- lib/Core/Searcher.cpp
- lib/Solver/MetaSMTSolver.cpp
- lib/Solver/Z3Solver.cpp
- tools/klee/main.cpp
This is a work in progress which aims to steer the usage of klee_message, klee_warning, and klee_error as opposed to fprintf and llvm::errs() when strictly required (for example, I left llvm::errs() for debugging info).
Any feedback is very appreciated.
> Refactoring logging information

- tools/klee/main.cpp
In the description, --sym-argv and --sym-argvs should have instead been --sym-arg and --sym-args
> Fixed the description of -posix-runtime option

- autoconf/configure.ac
- configure
- include/klee/Config/config.h.in
- lib/Support/PrintVersion.cpp
It is pain for build systems to see __DATE__ or __TIME__ in sources as
the build is not reproducible. So add an option to disable time
stamping the sources.
> configure: add option to disable timestamping

- include/klee/util/ExprEvaluator.h
- lib/Expr/ExprEvaluator.cpp
- unittests/Assignment/AssignmentTest.cpp
- unittests/Assignment/Makefile
- unittests/Makefile
Fix bug in `AssignmentEvaluator` where NotOptimizedExpr would not be folded preventing an assignment from being properly evaluated.
> Fix bug in `AssignmentEvaluator` where NotOptimizedExpr would not

- Makefile.common
When building KLEE with the sanitizers make sure the runtime is not built with them because KLEE can't handle this.
> Don't build KLEE's runtime with any sanitizers.

- lib/Module/IntrinsicCleaner.cpp
Fix `-Wmisleading-indentation` warning and also correctly set the `dirty` flag if we remove `llvm.trap` from the module.
> Fix `-Wmisleading-indentation` warning and also correctly set the `dirty` flag 

- tools/klee/CMakeLists.txt
Links in the correct LLVM libraries when using the MCJIT. This has no effect for LLVM versions less than 3.6. This is mean to make the work done by @rtrembecky in PR #385 compatible with the new CMake build system.
> [cmake] Build with newer JIT (for LLVM >= 3.6)

- lib/Core/Searcher.cpp
- lib/Core/UserSearcher.cpp
This prevents `klee --use-merge` to crash on an assertion (https://github.com/klee/klee/blob/e853f0bceeb7099acc3df16e52a3cfd1dabad422/lib/Core/UserSearcher.cpp#L121). The PR also adds an explanation why RandomPathSearcher does not work with MergingSearcher.
> add nicer error messages for --use-merge and add explanation why it currently cannot be used with random-path

- lib/Core/Searcher.cpp
- test/Feature/BFSSearcher.c
For performance reasons, if KLEE branches, one state is reused
and it is progressed by adding new constraints.
Make sure both new states end up at the end of the BFS searcher queue.
Addition to #488 .
> Fix BFS searcher

- unittests/Assignment/CMakeLists.txt
- unittests/Expr/CMakeLists.txt
- unittests/Ref/CMakeLists.txt
- unittests/Solver/CMakeLists.txt
Remove unneeded dependency declarations for the unit tests.
These were changes that I forgot to make in
dda296e09ee53ed85ccf1c3f08e7e809adce612e .
> [CMake] Remove unneeded dependency declarations for the unit tests.

- CMakeLists.txt
[CMake] Fix legacy build system files in source tree interfering
with CMake build.
We now raise a fatal error if we detect certain files in the source
tree. This is a heuristic but it's good enough for now.
The order of includes has also been changed so that the build tree
include directory has priority over the source tree include directory so
that even if the added check was missing the right header file (i.e.
`${CMAKE_BINARY_DIR}/include/klee/Config/config.h` would be picked up at
build time.
> [CMake] Fix legacy build system files in source tree interfering with CMake build.

- runtime/Runtest/CMakeLists.txt
[CMake] Implement install of the kleeRuntest target.
Required to fix #480
> [CMake] Implement install of the kleeRuntest target.

- cmake/klee_add_component.cmake
This fixes issue #507.
We can't build the components as shared libraries right now due
to cyclic dependencies (see #502 for a fix) and there are a few
other patches needed too (see #507).
Building the components as shared libraries isn't really desirable
anyway because it would require us to ship KLEE's libraries which
don't have a stable API.
> [CMake] Fix the build when `-DBUILD_SHARED_LIBS=ON` is passed.

- cmake/find_llvm.cmake
- lib/Module/CMakeLists.txt
This has shown that there is another circular dependency
(added by me! sigh...) between `kleeCore` and `kleeModule`.
> [CMake] Add missing dependencies reported in #507.

- tools/klee/main.cpp
As far as I understood, `klee_posix_prefer_cex` should also be present in the `modelledExternals` array inside KLEE main file (`tools/klee/main.cpp:757`).
> Added `klee_posix_prefer_cex` among the external calls that we model

- CMakeLists.txt
[CMake] Fix bug where if KLEE was built with `ENABLE_TCMALLOC`
and then re-configured with `ENABLE_TCMALLOC` set to OFF then
`klee/Config/config.h` was not correctly re-generated.
> [CMake] Fix bug with enabling and then disabling TCMalloc support

- lib/Core/Executor.cpp
There seems to be a comma that should be a semi-colon (unless I'm totally missing something...).
> executor: comma -> semi-colon

- cmake/find_llvm.cmake
When trying to KLEE with a version of LLVM (specifically, 3.5) built from Github (https://github.com/llvm-mirror/llvm/tree/release_35) the regex in find_llvm.cmake failed to match the LLVM version string because it was suffixed with "svn" - i.e. "3.5.2svn".
I added the optional "svn" suffix to the CMake regex to fix this. I would have prefered to use a non-capturing group, however when I used `(?:svn)?` the regex failed to compile for some reason (anyone know why?). Alternatively, you could just remove the `$` from the end of the regex (i.e. `^([0-9]+)\\.([0-9]+)\\.([0-9]+)`). Let me know what you guys would prefer!
> CMake: Fixed the LLVM version regex

- autoconf/configure.ac
- configure
1. Use -lmetaSMT in LDFLAGS caused linking failure;
2. This linking failure was missed.
> Fix two issues with AC_LINK_IFELSE for metaSMT:

- test/Feature/LinkLLVMLib.c
- test/lit.cfg
Brings llvm-ar into line with llvm-as and lli, removing the assumption that llvm-ar is installed system-wide.
> tests: Added lit substitution for llvm-ar

- runtime/Runtest/Makefile
- runtime/Runtest/intrinsics.c
- test/CMakeLists.txt
- test/Makefile
- test/Replay/libkleeruntest/replay_invalid_klee_assume.c
- test/Replay/libkleeruntest/replay_invalid_klee_choose.c
- test/Replay/libkleeruntest/replay_invalid_klee_range.c
- test/Replay/libkleeruntest/replay_invalid_num_objects.c
- test/Replay/libkleeruntest/replay_invalid_object_names.c
- test/Replay/libkleeruntest/replay_invalid_object_size.c
- test/Replay/libkleeruntest/replay_posix_runtime.c
- test/Replay/libkleeruntest/replay_simple.c
- test/Replay/libkleeruntest/replay_two_objects.c
- test/lit.cfg
- test/lit.site.cfg.in
This contains fixes and enhancements for libkleeRuntest that I previously discussed with @danielschemmel.
The main changes are
* Add actual tests!
* Fix a bug when replaying test cases created when KLEE ran using the POSIX runtime
* Fix how errors are handled inside libkleeRuntest so by default it exits when errors occur instead of the old behaviour which just carried on executing (which seems a pretty silly default).
@danielschemmel could you review this?
> Fixes and testing for libkleeRuntest

- .travis/klee.sh
- CMakeLists.txt
- Makefile.rules
- README-CMake.md
- test/CMakeLists.txt
- test/Makefile
- tools/klee-stats/CMakeLists.txt
- tools/ktest-tool/CMakeLists.txt
This was a proposal from #500.
@andreamattavelli pointed out that the lit tests are really
system tests rather than integration tests so this commit fixes
the inappropriate naming that I chose.
> [CMake] Rename "integrationtests" to "systemtests", removed some undocumented targets and other build changes

- cmake/modules/FindZ3.cmake
On Fedora 25 the `z3.h` file from the `z3-devel` package is located at `/usr/include/z3`.
The `FindZ3.cmake ` script need a little hint to be able to find that location.
> [cmake] add PATH_SUFFIXES needed to find z3 on Fedora

- test/Feature/Vararg.c
The helper function had int return type, while no value was being
returned.
> test: fix broken Vararg test

- runtime/CMakeLists.txt
Unfortunately, Ubuntu 14.04 LTS (supported until 4/2019) still ships with pre-3.2 cmake. It'd be nice to support rebuilding the POSIX runtime without having to issue `make clean` all the time even on this version. Especially since the "klee/klee" docker image is based on 14.04 Ubuntu, sporting cmake 2.8.
This is also compatible with post-3.2 cmake versions as well, checked with cmake 3.6.
If you think there is a better way to achieve a similar result (either with a patch or without), then please do let me know, I'm happy to cancel this PR.
> [CMake] More widely available rebuilding for the POSIX runtime

- include/klee/Expr.h
- include/klee/util/Bits.h
This PR implements the suggestion made by @delcypher in #536.
After implementing the pre/post conditions, I had to fix the assertion in `ConstantExpr::create`. The method might be invoked with a value for `Width w` greater than 64, leading to consequent a failure in `assert(v == bits64::truncateToNBits(v, w) && "invalid constant");` since we now check the size in `truncateToNBits`.
> Bits pre/post conditions as assertions

- lib/Expr/Expr.cpp
- test/Feature/RewriteEqualities.c
- unittests/Expr/ExprTest.cpp
`ReadExpr::create()` was missing an opportunity to constant fold when handling constant arrays.
@andreamattavelli This a sketch of a potential optimization we have been discussing.
> ReadExpr::create() was missing an opportunity to constant fold

- include/klee/Internal/Support/ModuleUtil.h
- lib/Core/StatsTracker.cpp
- lib/Module/ModuleUtil.cpp
- test/regression/2016-11-24-bitcast-weak-alias.c
Fix assertion failure when klee::getDirectCallTarget() is used on call to bitcasted weak alias.
Test case is included.
> Fix assertion failure when klee::getDirectCallTarget() is used on call to bitcasted weak alias

- Makefile.rules
As per:
http://llvm.org/releases/3.6.0/docs/ReleaseNotes.html#the-opt-option-std-compile-opts-was-removed
the -std-compile-opts was effectively an alias of -O3. And since it was
removed in later LLVM versions, stop relying on that.
> Makefile: change -std-compile-opts to -O3

- lib/Solver/ConstantDivision.cpp
New compilers warn about using 'register' as follows:
ConstantDivision.cpp:66:3: warning: 'register' storage class specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
Remove the register specifier -- the compilers are clever enough to know
what to do.
> klee: remove use of deprecated 'register'

- include/klee/CommandLine.h
Pass the list as reference. Otherwise we can get errors with newer LLVM
like:
```
lib/Basic/ConstructSolverChain.cpp:26:19: error: call to deleted constructor of 'llvm::cl::list<QueryLoggingSolverType>'
if (optionIsSet(queryLoggingOptions, SOLVER_KQUERY)) {
^~~~~~~~~~~~~~~~~~~
llvm/Support/CommandLine.h:1466:3: note: 'list' has been explicitly marked deleted here
list(const list &) = delete;
^
```
> CommandLine: do not copy list in optionIsSet

- include/klee/Interpreter.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/ExternalDispatcher.cpp
- lib/Core/ExternalDispatcher.h
- lib/Module/Checks.cpp
- lib/Module/IntrinsicCleaner.cpp
- lib/Module/KModule.cpp
- lib/Module/LowerSwitch.cpp
- lib/Module/ModuleUtil.cpp
- tools/klee/main.cpp
It was marked as deprecated long time ago and finally removed in LLVM
3.9. Remove all uses of getGlobalContext and create our own context.
Propagate it all over the code then.
> llvm: stop using global context

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/MemoryManager.h
- test/regression/2016-12-14-alloc-alignment.c
Teach KLEE to respect the requested memory alignment of globals and stack variables when possible.
Previously an alignment 8 was always used which did not faithfully
emulate what was either explicitly requested in the LLVM IR or what
the default alignment was for the target.
> Teach KLEE to respect the requested memory alignment of allocated memory

- lib/Core/Executor.cpp
- lib/Core/StatsTracker.cpp
- lib/Module/Checks.cpp
- lib/Module/InstructionInfoTable.cpp
- lib/Module/KModule.cpp
- lib/Module/LowerSwitch.cpp
- lib/Module/RaiseAsm.cpp
- tools/klee/main.cpp
Newer versions of LLVM do not allow to implicitly cast iterators to
pointers where they point. So convert all such uses to explicit
static_cast, the same as LLVM code does.
> convert iterators using static_cast

- lib/Solver/CoreSolver.cpp
This clearly identifies KLEE output and makes it possible to turn it off.
> Using klee_message instead of llvm:errs

- include/klee/Internal/Module/KInstruction.h
- lib/Core/Executor.cpp
- lib/Module/KInstruction.cpp
This was suggested by @MartinNowack in #418, and it is indeed a much better place for this function.
> Moved printFileLine() to be part of KInstruction

- lib/Module/ModuleUtil.cpp
object::Binary has isObject method, which can be used to check whether
it is an object::ObjectFile. Use that, since dyn_casting of
object::Binary is not allowed in newer LLVMs:
```
lib/Module/ModuleUtil.cpp:304:78: error: cannot convert ‘llvm::object::ObjectFile’ to ‘llvm::object::ObjectFile*’ in initialization
else if (object::ObjectFile *o = dyn_cast<object::ObjectFile>(child.get()))
^
```
> Module: simplify is_object checks

- lib/Core/ExternalDispatcher.cpp
We will use newer MCJIT with newer LLVM versions. But it needs unique
names of functions or a wrong function can be called. So prepend
"dispatcher_" to function names (even for older LLVMs).
> Core: MCJIT functions need unique names

- lib/Core/StatsTracker.cpp
Newer LLVMs do not allow implicit conversion from Instruction to
CallSite. We see this error:
```
Internal/Support/ModuleUtil.h:36:19: note: candidate function not viable: no known conversion from 'llvm::Instruction *' to 'llvm::CallSite' for 1st argument
llvm::Function *getDirectCallTarget(llvm::CallSite);
^
```
So explicitly create a CallSite from Instruction.
> Core: explicitly create CallSite from Instruction

- test/Concrete/ConstantExpr.ll
There is a test that thinks this should hold:
((&gInt >> 8) << 8) != ((&gInt << 8) >> 8)
For example, if the address is 0x00123400, this means:
0x00123400 != 0x00123400
which is obviously not true. Kill the bogus assumption as it causes
occasional failures in the tests.
> test: ConstantExpr, kill bogus test

- test/Feature/Alias.c
- test/Feature/LargeReturnTypes.cpp
- test/lit.cfg
- test/regression/2016-11-24-bitcast-weak-alias.c
PR #514 introduces a test case that fails on OS X:
```bash
FAIL: KLEE :: regression/2016-11-24-bitcast-weak-alias.c (190 of 197)
******************** TEST 'KLEE :: regression/2016-11-24-bitcast-weak-alias.c' FAILED ********************
Script:
--
/usr/local/bin/clang-3.4 -I/Users/andrea/Work/SRG/klee/klee/include /Users/andrea/Work/SRG/klee/klee/test/regression/2016-11-24-bitcast-weak-alias.c -Wall -emit-llvm -g -O0 -c -o /Users/andrea/Work/SRG/klee/klee-build/test/regression/Output/2016-11-24-bitcast-weak-alias.c.tmp.bc
rm -rf /Users/andrea/Work/SRG/klee/klee-build/test/regression/Output/2016-11-24-bitcast-weak-alias.c.tmp.klee-out
klee --output-dir=/Users/andrea/Work/SRG/klee/klee-build/test/regression/Output/2016-11-24-bitcast-weak-alias.c.tmp.klee-out -exit-on-error …
```
> Fix test case for OSX: only weak aliases are supported on darwin

- test/CMakeLists.txt
There was a typo and 'not' utility was tried to be built with
FileCheck's libraries. But those can be undefined. Fix this by using the
correct variable.
> test: fix 'not' build

- runtime/POSIX/fd.c
clang warns about check-after-use in POSIX runtime:
```
runtime/POSIX/fd.c:573:17: warning: nonnull parameter 'path' will evaluate to 'true' on first
r [-Wpointer-bool-conversion]
(path ? __concretize_string(path) : NULL),
^~~~ ~
```
path is dereferenced in __get_sym_file before this check. So if this
were an error it would crash much earlier before this check point.
Remove these checks completely, as we assume path cannot be NULL per
docco of these functions.
Actually the glibc version of futimesat allows path to be NULL and
changes times of dirfd in that case. But I have no idea how we could
implement that (return an error?).
> runtime: change __get_sym_file to return NULL when path is NULL

- test/Runtime/POSIX/FD_Fail.c
In our build environments, /etc/fstab is an empty file. Use /etc/mtab,
which should be non-empty anywhere, hopefully.
For the reference, the test fails as follows:
```
FAIL: KLEE :: Runtime/POSIX/FD_Fail.c (188 of 212)
************ TEST 'KLEE :: Runtime/POSIX/FD_Fail.c' FAILED ************
Script:
--
clang-3.8 -Iinclude test/Runtime/POSIX/FD_Fail.c -emit-llvm -O0 -c -o build/test/Runtime/POSIX/Output/FD_Fail.c.tmp1.bc
rm -rf build/test/Runtime/POSIX/Output/FD_Fail.c.tmp.klee-out
build/bin/klee --output-dir=build/test/Runtime/POSIX/Output/FD_Fail.c.tmp.klee-out --libc=uclibc --posix-runtime build/test/Runtime/POSIX/Output/FD_Fail.c.tmp1.bc --sym-files 0 0 --max-fail 1 > build/test/Runtime/POSIX/Output/FD_Fail.c.tmp.log
grep -q "fread(): ok" build/test/Runtime/POSIX/Output/FD_Fail.c.tmp.log …
```
> test: POSIX, stop FD_Fail to fail

- lib/Solver/CMakeLists.txt
[CMake] Unbreak build due to not adding AssignmentValidatingSolver.cpp to list of source files.
> [CMake] Unbreak build due to not adding AssignmentValidatingSolver.cpp

- runtime/POSIX/stubs.c
With glibc 2.25, we see:
```
runtime/POSIX/stubs.c:243:14: error: conflicting types for 'gnu_dev_major'
unsigned int gnu_dev_major(unsigned long long int __dev) __attribute__((weak));
^
/usr/include/sys/sysmacros.h:79:27: note: previous definition is here
__SYSMACROS_DEFINE_MAJOR (__SYSMACROS_IMPL_TEMPL)
^
```
Glibc 2.25 switched from ULL to dev_t for gnu_dev_major, gnu_dev_minor,
and gnu_dev_makedev. Handle by using an appropriate type according to
the glibc version.
> runtime: POSIX, make it compile with glibc 2.25

- cmake/find_llvm.cmake
[CMake] Try to fix bug reported by #633.
It looks like older LLVM versions that were built from SVN/git didn't
have a patch version number (i.e. `3.4svn` rather than `3.4.0svn`).
> [CMake] Try to fix bug reported by #633.

- .travis/metaSMT.sh
@delcypher @ccadar @andreamattavelli 
Due to my inexperience with git, I introduced an "optimization" (git submodule update --depth 1) that now fails because more commits have been added to the submodule. This needs to be merged ASAP... Sorry!
> [travis] fix a git submodule failure of metaSMT

- .travis.yml
- .travis/metaSMT.sh
- CMakeLists.txt
- MetaSMT.mk
if recent boost is used (version >= 1.57.0)
> Support -fno-rtti with metaSMT

- .travis/stp.sh
It seems there are have been quite a few changes upstream that
change the way CMake is invoked. There doesn't seem to be any good
reason for doing this.
I advise we drop this configuration so we don't have to worry about upstream STP breaking things.
> [TravisCI] Try to unbreak the build against upstream STP.

- .travis.yml
- lib/Core/Executor.cpp
- lib/Core/ExternalDispatcher.cpp
- lib/Core/ExternalDispatcher.h
- lib/Core/StatsTracker.cpp
- lib/Module/KModule.cpp
- lib/Module/ModuleUtil.cpp
- lib/Module/Optimize.cpp
- lib/Module/RaiseAsm.cpp
- lib/Solver/QueryLoggingSolver.cpp
- lib/Support/CompressionStream.cpp
- test/lit.cfg
- tools/klee/Makefile
- tools/klee/main.cpp
Based on #378, but it is cleaned of unnecessary changes (they were dropped (whitespace changes) or extracted and posted as separate pull requestes.) This one depends on #600 which is included here as well. I will rebase this PR once #600 is accepted.
On the top of this, I have changes for llvm up to 3.9 ready. But let's do this in steps.
> Llvm 3.5 and 3.6 support

- include/klee/Internal/Support/FileHandling.h
- lib/Solver/Z3Builder.cpp
- lib/Solver/Z3Builder.h
- lib/Solver/Z3Solver.cpp
- lib/Support/CMakeLists.txt
- lib/Support/FileHandling.cpp
- tools/klee/main.cpp
This upstreams a bunch of enhancements for working with Z3 from my fork.
@ccadar This includes the Z3 API logging I mentioned to you (see `-z3-log-interaction` option).
It also starts to address #653. I won't continue doing that until this PR is merged.
> Z3 fixes and enhancements

- tools/klee/main.cpp
ExitOnError collides with llvm::ExitOnError from LLVM 4:
```
tools/klee/main.cpp:430:23: error: reference to 'ExitOnError' is ambiguous
if (errorMessage && ExitOnError) {
^
/usr/include/llvm/Support/Error.h:938:7: note: candidate found by name lookup is 'llvm::ExitOnError'
class ExitOnError {
^
klee/tools/klee/main.cpp:141:3: note: candidate found by name lookup is '(anonymous namespace)::ExitOnError'
ExitOnError("exit-on-error",
^
1 error generated.
```
> llvm: rename ExitOnError to OptExitOnError

- test/Feature/Realloc.c
I have experienced rare test failure in our fork of KLEE due to failure of realloc where it returns NULL. I propose that the original assertion should only be checked when realloc succeeds.
> Prevent test failure when realloc fails in test/Feature/Realloc.c

- include/klee/Config/Version.h
- lib/Basic/CmdLineOptions.cpp
- lib/Core/Executor.cpp
- lib/Core/UserSearcher.cpp
- lib/Expr/ExprSMTLIBPrinter.cpp
- lib/Module/KModule.cpp
- tools/kleaver/main.cpp
- tools/klee/main.cpp
It became unnecessary when defining options and mainly undefined.
> llvm: don't use clEnumValEnd for LLVM 4.0

- lib/Module/InstructionInfoTable.cpp
DILocation is not copyable in LLVM 3.7. So, pass it as reference and
make it const given we do not write to it.
> llvm37: do not copy DILocation to getDSPIPath

- include/klee/Internal/Module/LLVMPassManager.h
- lib/Module/KModule.cpp
- lib/Module/Optimize.cpp
In LLVM 3.7, PassManager was moved to the legacy:: namespace. Introduce
a type for it and use it in the code.
> llvm37: introduce type for PassManager

- include/klee/Internal/Support/ModuleUtil.h
- lib/Module/ModuleUtil.cpp
- tools/klee/main.cpp
- having an explicit function which is defined for multiple llvm
versions separately increases readability.
- also: error handling was simplified
- Personal motivation: being able to use this functionality in unittests
fixes #561
related to #656
> move module loading into external function

- lib/Core/Executor.cpp
- lib/Core/StatsTracker.cpp
- lib/Module/Checks.cpp
- lib/Module/InstructionInfoTable.cpp
- lib/Module/KModule.cpp
- lib/Module/LowerSwitch.cpp
- lib/Module/RaiseAsm.cpp
- tools/klee/main.cpp
In commit b7a6aec4eeb4 (convert iterators using static_cast), I switched
all implicit casts to static_cast. It turned out that llvm 4.0 banned
casting via static_cast. See e.g. 1e2bc42eb988 in the llvm repo what
they do.
So similarly to the above commit, change all the casts of iterators to
"&*" which is what they do in LLVM.
> llvm: get rid of static_casts from iterators

- lib/Core/Executor.cpp
Instead of using an id, use the assembly line number executed.
This correctly reflects the appropriate line in assembly.ll.
> Use assembly line for printing debug information

- lib/Core/TimingSolver.cpp
Do not opencode what we already have in WallTimer. This simplifies the
code a lot and makes transition to LLVM 4.0 a lot easier.
We also introduce a helper to update the times.
> Core: TimingSolver, use WallTimer

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Module/CMakeLists.txt
- lib/Module/InstructionOperandTypeCheckPass.cpp
- lib/Module/KModule.cpp
- lib/Module/Passes.h
- lib/Module/Scalarizer.cpp
- test/VectorInstructions/extract_element.c
- test/VectorInstructions/extract_element_symbolic.c
- test/VectorInstructions/floating_point_ops_constant.c
- test/VectorInstructions/insert_element.c
- test/VectorInstructions/insert_element_symbolic.c
- test/VectorInstructions/integer_ops_constant.c
- test/VectorInstructions/integer_ops_signed_symbolic.c
- test/VectorInstructions/integer_ops_unsigned_symbolic.c
- test/VectorInstructions/shuffle_element.c
We use LLVM's Scalarizer pass to remove most vectorized code so that the
Executor only needs to support the InsertElement and ExtractElement
instructions.
This pass was not available in LLVM 3.4 so to support that LLVM version
the pass has been back ported.
There is no support for LLVM 2.9.
There are a few limitations to this implementation.
* The InsertElement and ExtractElement index cannot be symbolic.
* Due to the lack of proper floating point support the
`float_vector_constant_llvm*.ll` tests currently do not pass.
> Implement basic support for vectorized instructions.

- test/Concrete/FloatingPointOps.ll
Re-enable parts of `FloatingPointOps.ll`. The message about failures
doesn't seem relevant anymore given that LLVM 3.4 is the minimum version
KLEE supports. Also do minor clean up. This was spotted by @andreamattavelli.
> Re-enable parts of `FloatingPointOps.ll`

- test/regression/2015-08-05-invalid-fork.c
The bug in #262 only occurs with older versions of STP.
> Added regression test for bug reported by @kren1 in #262

- .travis/klee.sh
- CMakeLists.txt
- README-CMake.md
- cmake/find_metasmt.cmake
- cmake/find_stp.cmake
- cmake/find_z3.cmake
This PR addresses feedback from @MartinNowack  in #496.
This PR changes solver detection so that by default if the solver is available support for it will be enabled.
This PR also adds a `ENABLE_ZLIB` option.
I decided not to change the tcmalloc default because I don't think enabling it by default (even if it is available) is a good default because I've been tripped up by this before. Changing the memory allocator is a big deal and I think users should change this explicitly if they want this.
> [CMake] Change some defaults

- CMakeLists.txt
- lib/Support/CompressionStream.cpp
On FreeBSD <sys/capabilities.h> is present in libc, so we don't require libcap there.
Close and write functions are located in <unistd.h>.
> Fix build for FreeBSD.

- CMakeLists.txt
- README-CMake.md
- docs/CMakeLists.txt
- runtime/CMakeLists.txt
Not sure if this should be `clean-all` or `clean_all`. `clean_all` would be more consistent with the other target names.
> [CMake] Implement clean-all (fixes #718)

- CMakeLists.txt
- README-CMake.md
fixes #314
this also means we can no longer support llvm 2.9
Also enforce at least llvm 3.4 as older version are not included in the
test matrix.
> Enforce C++11

- lib/Core/SpecialFunctionHandler.cpp
- test/Feature/ubsan_signed_overflow.c
- test/Feature/ubsan_unsigned_overflow.c
This may resolve #731. Although I could think of a technique to detect signed / unsigned operations by detecting comparison with the constant 2147483647 or 4294967295 right before the call to `__ubsan` functions to distinguish signed or unsigned cases, but since ubsan itself does not distinguish both cases, KLEE should probably not try further. So the solution adopted here is to simply remove the word 'unsigned' from the error messages.
> Removed the word 'unsigned' from integer overflow error messages

- lib/Core/Executor.cpp
> Removed unnecessary and redundant variable in Executor

- lib/Core/Searcher.cpp
- test/Feature/BFSSearcherAndDFSSearcherInterleaved.c
With reasonably complex programs, the use of `-search=bfs -search=dfs` leads to a failed assertion:
> klee:  ../lib/Core/Searcher.cpp:106: virtual void klee::BFSSearcher::update(klee::ExecutionState*, const std::vector\<klee::ExecutionState*\>&, const std::vector\<klee::ExecutionState*\>&): Assertion `states.front() == current' failed.
The assertion (introduced with the fix in 2b2b2b0) assumes that `current` was chosen by BFSSearcher. But, if chosen by another searcher (in an interleaved searcher), `current` can be different from BFSSearcher's front element.
> Fix: BFS as part of interleaved searcher

- .travis.yml
- .travis/klee.sh
- .travis/metaSMT.sh
- cmake/find_metasmt.cmake
- include/klee/CommandLine.h
- lib/Basic/CmdLineOptions.cpp
- lib/Solver/MetaSMTSolver.cpp
1. Update to use a proper version of metaSMT (v4.rc1).
2. Add support for CVC4 and Yices2.
3. Update to use two new flags generated by metaSMT: list of available backends and whether RTTI is required.
4. Several small improvements.
The commits are rather small to make review easier (hopefully). Once approved , they can be squashed together if desired.
Currently, travis_wait is required because CVC4 needs around 10m to finish Solver/2016-04-12-array-parsing-bug.kquery. This test case appears to be rather complex, I recall that boolector-1.5 also had difficulties solving it. @andreamattavelli is it possible to simplify the test case a bit or can you shed some light on how it is supposed to be solved quickly?
> Improve metaSMT support (proper version, support CVC4 and Yices, ...)

- lib/Core/Executor.cpp
The boundary for a huge allocation is 1<<31.
Note that 1<<31 is of type signed int, so while passed to ConstandExpr::alloc,
it is sign-extended to 0xffffffff80000000, which is later cast to uint64_t.
As a result, the boundary actually becomes 18446744071562067968L instead of 2147483648.
> Fixing huge allocation size constant to be unsigned

- lib/Core/SpecialFunctionHandler.cpp
- test/Feature/MakeSymbolicAPI.c
- test/regression/2017-11-01-test-with-empty-varname.c
* uses `klee_error` instead of assertions for illegal argument number
* renames empty names to `unnamed` (otherwise test generation fails)
* deprecates two argument version
> klee_make_symbolic: warn on deprecated usage

- include/klee/ExecutionState.h
- include/klee/MergeHandler.h
- include/klee/klee.h
- lib/Core/CMakeLists.txt
- lib/Core/ExecutionState.cpp
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/MergeHandler.cpp
- lib/Core/Searcher.cpp
- lib/Core/SpecialFunctionHandler.cpp
- lib/Core/SpecialFunctionHandler.h
- lib/Core/UserSearcher.cpp
- test/Merging/batching_break.c
- test/Merging/easy_merge.c
- test/Merging/indirect_value.c
- test/Merging/loop_merge.c
- test/Merging/merge_fail.c
- test/Merging/nested_merge.c
- test/Merging/split_merge.c
- test/Merging/unexpected_close.c
- tools/klee/main.cpp
This PR implements the basic version of a region-based state merging approach, behind the `-use-bounded-merge` flag. PR #691 adds additional functionality to this basic approach.
```c
klee_open_merge();
/* code containing branches etc. */
klee_close_merge();
```
Will lead to all states that forked from the state that executed the `klee_open_merge()` being merged in the `klee_close_merge()`. This allows for fine-grained regions to be specified for merging.
Tests for the implementation are also included in this PR, which give a few examples of how this technique can be used.
The main part of the new functionality is implemented in the class `BoundedMergeHandler`. The Special Function Handler generates an instance of this class every time a state runs into a `klee_open_merge()` call.
This …
> Implement basic region-based state merging (RBSM 2/3)

- .travis.yml
This PR needs to be accepted at the same time the homebrew tap repository is moved under the KLEE organization.
> Move Homebrew tap from personal repository to the KLEE organization

- test/Merging/batching_break.c
- test/Merging/easy_merge.c
- test/Merging/indirect_value.c
- test/Merging/loop_merge.c
- test/Merging/merge_fail.c
- test/Merging/nested_merge.c
- test/Merging/split_merge.c
- test/Merging/unexpected_close.c
- test/regression/2016-11-24-bitcast-weak-alias.c
See #800 
This fixes the merging tests, and also another test that was still using `klee` (instead of `%klee`).
The other test was: `test/regression/2016-11-24-bitcast-weak-alias.c`
> Fix Merging Tests: use `%klee` instead of `klee`

- include/klee/MergeHandler.h
clang 5 reports:
```
In file included from ../lib/Core/MergeHandler.cpp:10:
../include/klee/MergeHandler.h:81:12: warning: private field 'closedStateCount' is not used [-Wunused-private-field]
unsigned closedStateCount;
^
```
So fix it by removing the member.
> MergeHandler: remove unused closedStateCount

- .codecov.yml
- .travis.yml
- .travis/install-llvm-and-runtime-compiler.sh
- .travis/klee.sh
* Fixed: Generation of coverage information
* Enables caching for travis (reduces build time by 1/3 from total ~3h to ~2h)
* Mac OSX: use cached LLVM build (if available) or build brew bottle locally and cache it
> Show additional coverage information and enable caching for TravisCI

- lib/Core/Context.h
- lib/Core/Executor.cpp
- lib/Core/ExecutorUtil.cpp
- lib/Core/Memory.cpp
- lib/Core/Memory.h
- test/Concrete/ConstantInit.ll
- test/Feature/ConstantArray.ll
- test/regression/2007-08-01-bool-zext-in-call.ll
This PR handles a couple of issues:
* fix handling of `getElementPtr` for vectors and arrays
* fix handling of constant-ordered vector
* fix handling of `ExtractElement`/`InsertElement`
Fixes root cause of issue with #669 .
> Fix vector handling

- lib/Core/StatsTracker.cpp
- tools/klee-stats/klee-stats
This patch stores the statistics recorded by the counterexample cache and also updates `klee-stats` to use them.
> Store CexCache stats and then update klee-stats to use them

- test/Feature/BFSSearcherAndDFSSearcherInterleaved.c
When building KLEE with LLVM 3.7, `test/Feature/BFSSearcherAndDFSSearcherInterleaved.c` fails, as seen in #669.
As I introduced the failing test, I looked into the issue and found the problem: I wanted to check the output against two conditions:
- is exactly 4 characters long
- for each of A, B, C and D: occurs exactly once
To check these, I used `CHECK` and (multiple) `CHECK-SAME` expressions that all try to match the same whole line. Starting form LLVM 3.7, `FileCheck` seems to skip already matched parts of the ouput permanently, it is no longer possible to match the whole line from the beginning.
The only fix I could think of (that actually works, unlike regex lookaheads), is to explicitly enumerate all possible patterns in a single `CHECK`.
> fix: test/Feature/BFSSearcherAndDFSSearcherInterleaved.c (LLVM 3.7)

- README-CMake.md
- unittests/CMakeLists.txt
For example, the archlinux gtest package splits its files in `/usr/include/gtest` and `/usr/src/gtest`.
> Add cmake option to set GTest include dir

- lib/Core/Executor.cpp
- test/regression/2018-05-05-number-instructions-dumped-states.c
`doDumpStates` calls `stepInstruction` and therefore indirectly increases time and instruction statistics for all dangling (dumped) states. This patch removes the call, but now the instruction timing stats for the last executed state are lost, as `StatsTracker::stepInstruction` isn't called anymore.
I think the best way to fix this is to split the `stepInstruction`s into `prepareInstruction` and `finishInstruction` but that's for another pull request.
> doDumpStates: incorrectly increments stats

- .travis.yml
This retires the old PPA used to get llvm into travis and replaces it with the official llvm one. This way we should be able to easily support llvm versions up to at least 6.0.
Note this is partially done by #669 already, but I think it makes sense to move all the llvm versions to this repository.
> Change Travis LLVM source to official LLVM apt

- tools/klee/main.cpp
This pull request is opened about the bug described in issue #851 . It is fixed by moving klee_error message to the end of processTestCase function
> exitOnError no output buf fix

- include/klee/klee.h
- lib/Core/AddressSpace.cpp
- lib/Core/AddressSpace.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/ExternalDispatcher.cpp
- lib/Core/ExternalDispatcher.h
- lib/Core/Memory.h
- lib/Core/SpecialFunctionHandler.cpp
- lib/Core/SpecialFunctionHandler.h
- runtime/POSIX/fd.c
- test/Runtime/POSIX/DirSeek.c
- test/Runtime/POSIX/Ioctl.c
- tools/klee/main.cpp
The object pointed to by `__errno_location()` should be part of the execution state.
Currently, this is only the case if `CTYPE_EXTERNALS` is defined and we are neither on Windows nor Darwin.
> Provide errno independent of CTYPE_EXTERNALS being defined

- include/klee/Internal/Support/Debug.h
- include/klee/Internal/System/Time.h
- lib/Module/KModule.cpp
`#include <>` often refers to systems include directories while `#include ""` refers to user provided directories.
Keep them the same throughout the project to avoid wrong inclusions.
> Fix include files

- lib/Module/IntrinsicCleaner.cpp
- lib/Module/KModule.cpp
- lib/Module/Passes.h
This used to be workaround for older LLVM version (< 3).
Remove the old behaviour.
> Allow lowering of LLVM intrinsics before optimization

- lib/Module/KModule.cpp
This option was used by default to workaround a problem in an ancient kcachegrind.
The behaviour could not be reproduce for kcachegrind from 2012.
Remove this option all together.
On the plus side: `assembly.ll` can be compiled to bitcode again.
> Remove the option for truncating lines in assembly.ll

- .clang-format
After a productive discussion (☕️) with @251 and @kren1 , we realised that clang-format should be updated.
> Update clang-format standard of KLEE codebase to C++11

- include/klee/ExecutionState.h
- include/klee/MergeHandler.h
- lib/Core/ExecutionState.cpp
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/MergeHandler.cpp
- lib/Core/Searcher.cpp
- lib/Core/Searcher.h
- lib/Core/SpecialFunctionHandler.cpp
- lib/Core/UserSearcher.cpp
- test/Merging/incomplete_merge.c
This PR finishes up the implementation of a region-based state merging approach with a feature that will heuristically continue states waiting at a merge point even when not all corresponding states have been merged yet. When the flag `-incomplete-bounded-merge` is passed (in addition to `-use-bounded-merge`), this will prevent states waiting at a merge point from waiting indefinitely, e.g. in cases where one or multiple states take much longer to reach the close point than other states. This PR builds upon and extends PR #690.
The main part added by this PR is in da58d3f. This commits adds functionality to the `BoundedMergingSearcher` that will prioritize (e.g., immediately schedule) states running inside a bounded-merge region once a state has reached a corresponding …
> Non-blocking State Merging (RBSM 3/3)

- lib/Core/SpecialFunctionHandler.cpp
- test/Feature/MakeSymbolicAPI.c
As discussed in #841.
I'm not sure how good returning `""` on error is, but I guess it works.
> Improve error messages for ReadStringAtAddress

- test/Feature/ByteSwap.c
- test/Feature/CheckForImpliedValue.c.failing
- test/Feature/CompressedExprLogging.c
- test/Feature/CopyOnWrite.c
- test/Feature/DanglingConcreteReadExpr.c
- test/Feature/ExprLogging.c
- test/Feature/FunctionPointer.c
- test/Feature/ImpliedValue.c.failing
- test/Feature/InAndOutOfBounds.c
- test/Feature/IsSymbolic.c
- test/Feature/KleeReportError.c
- test/Feature/MultipleFreeResolution.c
- test/Feature/MultipleReadResolution.c
- test/Feature/MultipleReallocResolution.c
- test/Feature/MultipleWriteResolution.c
- test/Feature/PreferCex.c
- test/Feature/ReplayPath.c
- test/Feature/Searchers.c
- test/Feature/WithLibc.c
- test/Programs/pcregrep.c
- test/regression/2007-07-25-invalid-stp-array-binding-to-objectstate.c
- test/regression/2007-07-30-unflushed-byte.c
- test/regression/2007-08-01-cache-unclear-on-overwrite-flushed.c
- test/regression/2007-08-06-64bit-shift.c
- test/regression/2007-08-06-access-after-free.c
- test/regression/2007-08-16-invalid-constant-value.c
- test/regression/2007-08-16-valid-write-to-freed-object.c
- test/regression/2007-10-11-illegal-access-after-free-and-branch.c
- test/regression/2015-08-30-empty-constraints.c
- test/regression/2016-06-28-div-zero-bug.c
Removes usage of obsolete API from tests.
> tests: use names in klee_make_symbolic

- include/klee/SolverStats.h
- include/klee/util/ArrayExprHash.h
- lib/Core/StatsTracker.cpp
- lib/Solver/SolverStats.cpp
This is too generic and llvm 6.0 defines DEBUG as follows:
```
#define DEBUG(X) DEBUG_WITH_TYPE(DEBUG_TYPE, X)
```
This then results in various build failures where once the macro is
defined, once it is not.
> stop using DEBUG macro name

- lib/Module/IntrinsicCleaner.cpp
- lib/Module/Passes.h
This PR started with me noticing that #867 didn't remove `bool LI=true` (after it was already merged...).
I found some other stuff that I also want to address with this PR:
* remove unused variables `block_split` (::runOnBasicBlock) and `LI` (::IntrinsicCleanerPass) in IntrinsicCleanerPass
* add `dirty = true` to `Intrinsic::vacopy` case
* use `eraseFromParent()` methods instead of `removeFromParent()` and `delete`
* add `override` keyword to `runOn{Module,Function}` methods
> Minor Passes Housekeeping

- test/VectorInstructions/integer_ops_unsigned_symbolic.c
Use `&&` instead. Some compilers are picky:
```
test/VectorInstructions/integer_ops_unsigned_symbolic.c:85:22: warning: & has lower precedence than <; < will be evaluated first [-Wparentheses]
```
> test: add parenthesis around & operands 

- lib/Core/Executor.cpp
The switch governing floating point comparison is currently implemented as a series of fallthrough cases, which shortcut the NaN check for the ordered case, before using the unordered implementation otherwise.
Not only is this intransparent, it also causes compilation warnings on my current test system (GCC 8.1/CMake 3.11 source build on Arch):
```../lib/Core/Executor.cpp: In member function ‘void klee::Executor::executeInstruction(klee::ExecutionState&, klee::KInstruction*)’:
../lib/Core/Executor.cpp:2345:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
if (CmpRes == APFloat::cmpUnordered) {
^~
../lib/Core/Executor.cpp:2349:5: note: here
case FCmpInst::FCMP_OEQ:
^~~~
../lib/Core/Executor.cpp:2354:7: warning: this statement may fall through [-Wimplicit-fallthrough=] …
```
> remove switch fallthrough in floating point comparision (and thereby fix warnings)

- include/klee/MergeHandler.h
- lib/Core/MergeHandler.cpp
- lib/Core/SpecialFunctionHandler.cpp
Good catch! This leak actually had semantic consequences. We added an assertion to ensure that the heuristic merging does not fail silently.
> Fixed memory leak from Executor::inCloseMerge, fixes #883

- include/klee/klee.h
- lib/Core/SpecialFunctionHandler.cpp
- test/regression/2018-04-05-make-symbolic-null-name.c
Make KLEE a little bit more robust against lazy users (me). With NULL as name in `klee_int` the assertion in  `klee::SpecialFunctionHandler::readStringAtAddress` (XXX out of bounds / multiple resolution unhandled) fires.
> klee_int/klee_make_symbolic: allow NULL as name

- lib/Expr/Expr.cpp
- test/Feature/DeterministicSwitch.c
I did some flame graph profiling and noticed that ConstantExprs take some time, because they are computing the hash.
The reason is that `hash_value(APInt)` is quite expensive. Considering that most of our ConstantExpr, should fit in 64bits, it should be fine to just use `getLimitedValue`. If there are some ConstantExpr with more than 64bits, this still works fine, but there might be more collisions. However I don't think wide ConstantExprs are  common enough to be a problem.
> Improve ConstantExpr performance

- include/klee/Internal/ADT/MapOfSets.h
- lib/Expr/Parser.cpp
This fixes all remaining warnings that occur during compilation of the main KLEE code with GCC8. A couple of warnings remain in the runtime.
Remaining warnings in the runtime:
4x "attribute declaration must precede definition [-Wignored-attributes]" in klee/runtime/POSIX/stubs.c
1x "klee/runtime/POSIX/fd.c:554:19: warning: nonnull parameter 'path' will evaluate to 'true' on first encounter [-Wpointer-bool-conversion]"
> Fix remaining GCC8 warnings in primary KLEE code

- CMakeLists.txt
This changes tcmalloc to be enabled by default as per discussion in #847. I've updated the build documentation in https://github.com/klee/klee.github.io/pull/129.
> Enable tcmalloc by default

- scripts/build/dependencies-ubuntu.sh
- scripts/build/llvm.sh
@ccadar wildcard is not expanded on Mac. Therefore, the cached file could not be found.
Please merge.
> Fix slow Mac Travis build: wildcard is not expanded with quotes

- lib/Module/ModuleUtil.cpp
- test/Feature/EscapingFunctions.c
- test/Feature/EscapingFunctionsAlias.c
A while ago, I learned the hard way about a subtle API change between LLVM 3.4 and 3.5: `use_begin()` was renamed to `user_begin()`, but a new method of the same name was added to `Value`, so existing code will still compile, but behave differently (more details in first commit).
In KLEE, this iterator is (only) invoked by `valueIsOnlyCalled()`, which is used to create the set of escaping functions, which in turn is used by both the MD2U (Min-Dist-to-Uncovered) and Coverage-New NURS searchers.
I added a test for escaping functions ~~and as a result stumbled across another bug~~ and also added handling of `BlockAddress`es.
During all of this, I discovered that function pointers of functions that have only a declaration are not considered escaping functions (as they are not part of the set …
> Fix bug introduced by subtle LLVM API change, improve valueIsOnlyCalled

- test/.clang-format
Code files in `test/` might contain comment lines that are longer
as they contain `// RUN` commands. clang-formatting breaks the
tests. Stop clang-formatting from doing that.
> [clang-format] Allow longer codelines in test/

- lib/Core/ExternalDispatcher.cpp
- lib/Module/IntrinsicCleaner.cpp
- lib/Module/KModule.cpp
- lib/Module/LowerSwitch.cpp
- tools/klee/main.cpp
Replace the remaining occurrences of `Inst::Create()` with
`llvm::Builder` to manage metadata automatically and to fold
instructions.
C++11 it and clang-format
> Replace remaining *Inst::Create() calls with llvm::Builder

- CMakeLists.txt
Addresses #768 
CMake can now be invoked without any additional configuration flag.
> Disabled unit testing in default build

- tools/klee-stats/klee-stats
Currently `TResolve` is only printed with `--print-rel-times` or `--print-abs-times` but should imho also be included in `--print-all`.
> klee-stats: add TResolve(%) to --print-all

- test/Feature/Vararg.c
Vararg test can fail if KLEE is able to resolve the
intended out-of-bound memory address to a memory object.
To avoid this, allocate memory explicitly deterministic with
sufficient space between the allocations.
Enables support for Mac OSX again
> Avoid Vararg non-deterministic allocation

- .travis.yml
With the rewrite of the build scripts, we do not depend on `sudo` anymore.
This allows us to use container-based build infrastructure of TravisCI.
This patch removes the `sudo` requirement.
This is cherry-picked from  #955 as requested from @ccadar. Ready to be merged right away.
> Remove requirement for sudo on TravisCI

- runtime/POSIX/stubs.c
- test/Runtime/POSIX/CanonicalizeFileName.c
Fixes #46 and reverts parts of #47. As stated in #46, the solution works for musl, glibc etc. However, the code in stub.c is executed by uclibc and uclibc doesn't allocate the target buffer in `realpath`. The memory error occured while running `df` for 10min with DFS.
Weird that no-one ran into it. I have not included an `ifdef` chain for different systems (`limits.h` locations) as it seems to work now (5 years later) on Ubuntu, Arch, ...
> runtime: fix memory error in canonicalize_file_name

- test/CXX/StaticConstructor.cpp
- test/CXX/StaticDestructor.cpp
- test/Feature/InAndOutOfBounds.c
- test/Feature/KleeReportError.c
- test/Feature/MultipleFreeResolution.c
- test/Feature/OneFreeError.c
- test/Feature/OneOutOfBounds.c
- test/Feature/OvershiftCheck.c
- test/Feature/SourceMapping.c
- test/Feature/consecutive_divide_by_zero.c
- test/Feature/ubsan_signed_overflow.c
- test/Feature/ubsan_unsigned_overflow.c
- test/Runtime/POSIX/FreeArgv.c
- test/Runtime/POSIX/Isatty.c
- test/regression/2014-07-04-unflushed-error-report.c
As we do not support LLVM 2.9 anymore, we can use `FileCheck` `LINE` instead of hard coding line numbers.
> Use FileCheck LINE if possible

- lib/Core/Executor.cpp
- test/Merging/state_termination.c
KLEE currently crashes on a specific edge case involving merging, as discussed in issue #985 
> Whenever a 'MergeHandler' object is deleted, it dumps the remaining (merged) states into the 'Executor::continuedStates' vector. 
> These states are then reintroduced to the searchers.
> But, in Executer::updateStates, the MergeHandler is deleted after the continuedStates are reintroduced, which results in the merged states being forgotten for one simulation step.
> This is fixed by reintroducing the continuedStates after the removal of states.
Also added the failing test case as regression test
> StateMerging segfault fix

- include/klee/Config/config.h.cmin
- lib/Module/CMakeLists.txt
- lib/Module/ModuleUtil.cpp
This contains three tiny changes:
* get rid of `HAVE_MALLOC_MALLOC_H` in `config.h.cmin` (I forgot to do that in #919)
* #868 with ef90f1e219fec27a3d594158ae5f380a9e9a2f37 removed the dependency on SpecialFunctionHandler in `ModuleUtil.cpp`
* kleeModule always links against `irreader` (as support for LLVM < 3.4 was dropped)
> minor cmake/build process cleanup

- CMakeLists.txt
- lib/Core/ExternalDispatcher.cpp
- test/lit.cfg
- test/lit.site.cfg.in
- test/regression/2018-10-01-double-segfault.c
Currently KLEE only handles the first segfault in external calls as it doesn't unblock SIGSEGV afterwards. This patch unblocks the signal and enables handling of multiple failing calls.
It also introduces asan/not-asan, ubsan/not-ubsan flags for lit as the new test case triggers the ASAN build in Travis.
> lit: add (not-)asan/ubsan flags; klee: fix handling of failing external calls

- lib/Core/Executor.cpp
- lib/Module/KModule.cpp
- test/Feature/Atomic.c
This PR is part of a chain of PRs that adds C++-support to KLEE. For more information and an overview see PR #966.
---
This PR implements some atomic instructions from the LLVM instruction set. The 'atomic' property of these operations is not paid special regards in the implementation, as KLEE is currently only capable of running single-threaded programs anyway. Therefore, the semantics of these instructions are implemented in a straight-forward way.
These instructions often appear in C++ programs, or at least in those linked against a libc++, but can of course also appear in regular LLVM/C programs, as they are LLVM instructions.
> Implement handling for atomic LLVM instructions

- lib/Module/Checks.cpp
- lib/Module/KLEEIRMetaData.h
- test/Feature/DivCheck.c
- test/Feature/ShiftCheck.c
This PR provides a couple of goodies:
* Use `llvm::Builder` instead of `*Inst::create()`:
- manages metadata automatically (e.g. debug, TBAA, ...)
- does optimisation like code folding with newly added instructions (no `bitcasts` if none needed)
* Fixes an issue introduced by the #868: checks for single instructions can be inserted multiple times: avoid this by flagging an instruction as instrumented
- Add basic support to annotate code with KLEE
* Optimisation: Do not instrument instructions that do not need instrumentation (e.g. div by non-zero constant)
* Add tests to check the optimised and non-optimised case
Update with C++11 and clang-format.
> Update and fix div/shift checks

- test/Runtime/POSIX/GenBout.c
- test/lit.cfg
- tools/gen-bout/CMakeLists.txt
- tools/gen-bout/gen-bout.cpp
Whereas `gen-random-bout` produces ktest file `file.bout` with random content, `gen-bout` produces `file.bout` with specific content specified by the user.
* Sample use cases:
* Using an interesting input as a seed.
* Analyzing the path condition of a concrete input.
* Also added the test: `test/Runtime/POSIX/GenBout.c`.
> gen-bout tool to generate ktest file using concrete arguments and files

- lib/Core/Executor.cpp
- test/Feature/StackOverflow.c
Check if a state reaches the maximum number of stack frames allowed.
To be performant, the number of stack frames are checked.
In comparison, native execution checks the size of the stack.
Still, this is good enough to find possible stack overflows.
The limit can be changed with `-max-stack-frames`. The current
default is 8192 frames.
> Check for stack overflow in a tested program

- lib/Core/ExecutorUtil.cpp
- test/CXX/LandingPad.cpp
This PR is part of a chain of PRs that adds C++-support to KLEE. For more information and an overview see PR #966.
---
This PR adds a hack to make LLVM landingpads work in KLEE. These make use of a zero-sized type, which would be represented in KLEE by a zero-length `ConstantExpr`, which crashes with an assertion, as zero-length `ConstantExpr`s are not supported. Therefore, we simply use a length 1 `ConstantExpr` instead. The created expression should have no relevance for the program, but is required in KLEE.
Landingpads are usually found in C++ programs that use exceptions, but can of course also appear in other LLVM programs that use landingpads (e.g., compiled from Rust?).
> Add a hack to support zero-size array types (C++ 4/6)

- test/Concrete/CMakeLists.txt
- test/lit.site.cfg.in
I just noticed a mistake I made in #1009: `-O0` has to be used in conjunction with, not instead of `-Xclang -disable-O0-optnone`. Sorry.
> actually set -O0 in concrete tests

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/SpecialFunctionHandler.cpp
- lib/Core/SpecialFunctionHandler.h
- test/Feature/Memalign.c
- tools/klee/main.cpp
This pull requests adds an additional parameter to the Executor::executeAlloc function, allocationAlignment. The function retains its original behavior if the parameter is the default value, 0. Otherwise the allocation is executed with the given alignment.
The other addition is the modeling of memalign, which uses the alignment parameter of executeAlloc. If the alignment is not a constant expression, the lowest possible value is chosen via solver::getRange.
Memalign is required for current versions of libcxx (version 6.0), as it uses memalign to allocate an exception. This is relevant, but not required, for PR#966 "Add support for exception handling".
> Model memalign with alignment

- CMakeLists.txt
C++14 has a couple of nice features (https://en.wikipedia.org/wiki/C%2B%2B14).
The minimal compiler requirements are:
* clang 3.4
* gcc 4.9 for all the features we need; gcc 5 for all features
(gcc 5.4 is the default compiler on Xenial Ubuntu 16.04)
Make C++14 the minimal requirement.
> Enable C++14 support

- scripts/build/build-travis.sh
- test/regression/2014-09-13-debug-info.c
- tools/ktest-tool/ktest-tool
* switch to Python 3
* add file encoding
* some PEP8 reformatting
* fix TOCTOU for open
* replace trimZeros() with rstrip
* remove unused pos/args variables
* remove --write-ints (print by default)
* remove programName section (unused)
* added/modified output rows
- "data:" now shows the Python representation (for use in scripts; basically just a 'b' in front of the old output)
- "hex :" shows the hex representation
- "text:" shows ASCII, all out-of-range/non-printable characters are replaced by a dot
- "int :"/"uint:" print (un/signed) 8/16/32/64 bit integers
* reduce width for object counter to needed minimum instead of 4
* refactor printing into function
Fixes #1011.
Closes #540.
>  Various fixes for ktest-tool

- lib/Solver/CexCachingSolver.cpp
This patch fixes the following error when compiling KLEE with GCC 8.2.1 and C++17 enabled:
```
In file included from /usr/include/c++/8/set:60,
from ../include/klee/Expr.h:23,
from ../include/klee/Solver.h:13,
from ../lib/Solver/CexCachingSolver.cpp:10:
/usr/include/c++/8/bits/stl_tree.h: In instantiation of ‘class std::_Rb_tree<klee::Assignment*, klee::Assignment*, std::_Identity<klee::Assignment*>, AssignmentLessThan, std::allocator<klee::Assignment*> >’:
/usr/include/c++/8/bits/stl_set.h:133:17:   required from ‘class std::set<klee::Assignment*, AssignmentLessThan>’
../lib/Solver/CexCachingSolver.cpp:67:23:   required from here
/usr/include/c++/8/bits/stl_tree.h:457:21: error: static assertion failed: comparison object must be invocable as const
static_assert(is_invocable_v<const …
```
> make AssignmentLessThan::operator() const-invocable

- lib/Core/Executor.cpp
- test/Feature/Alias.c
- test/regression/2018-10-28-alias-to-alias.leq36.ll
- test/regression/2018-10-28-alias-to-alias.leq37.ll
- test/regression/2018-10-28-alias-to-alias.ll
This fixes a segfault in `Executor` during `initializeGlobals` when coming across aliases that point to another alias that was not yet added to `globalAddresses`.
**Edit:** Some more information. Although I could reliably reproduce the segfault with LLVM 3.4 on my computer, it rarely occurs on TravisCI. Here is a case of LLVM 3.7 crashing (on TravisCI):
```
#0 0x1230478 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/tmp/klee_build37_O_ND_A_stp2.1.2_z34.4.1_klee_uclibc_v1.0.0/bin/klee+0x1230478)
#1 0x122eee1 SignalHandler(int) (/tmp/klee_build37_O_ND_A_stp2.1.2_z34.4.1_klee_uclibc_v1.0.0/bin/klee+0x122eee1)
#2 0x7faeb74d8390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#3 0x5af485 klee::ref<klee::ConstantExpr>::inc() const /tmp/klee_src/include/klee/util/Ref.h:41:0
#4 …
```
> fix Executor::initializeGlobals for aliases pointing to another alias

- tools/ktest-tool/ktest-tool
Adds an option to `ktest-tool` to dump object values into files, e.g.:
```shell
> ktest-tool --trim-zeros --extract stdin ./test000011.ktest
> ls
test000011.ktest test000011.ktest.stdin
> hexdump -C test000011.ktest.stdin
00000000  40 00 ff                                          |@..|
00000003
```
> ktest-tool: add --extract option

- include/klee/Internal/System/Time.h
- lib/Core/Executor.cpp
- lib/Core/ExecutorTimers.cpp
- lib/Core/Searcher.cpp
- lib/Support/Time.cpp
- unittests/Time/TimeTest.cpp
Adds double for `Span` multiplication. Before `t *= 1.1;` was implicitly converted to identity. Implicit type conversions - what a splendid idea...
> time: add double type for span multiplications

- include/klee/SolverCmdLine.h
- lib/Basic/CmdLineOptions.cpp
- lib/Expr/ExprVisitor.cpp
- lib/Support/ErrorHandling.cpp
- tools/kleaver/main.cpp
With this PR, Kleaver now has a clean help menu, w/o the irrelevant LLVM options.   This cuts the number of lines of `--help` almost in half.
> More work on option categories

- include/klee/Internal/Module/KModule.h
- include/klee/Internal/Support/ModuleUtil.h
- lib/Core/Executor.cpp
- lib/Module/KModule.cpp
- lib/Module/ModuleUtil.cpp
- lib/Module/Optimize.cpp
I noticed that there was an unused `checkModule()` method after the last refactoring in ModuleUtil. Right now, the `VerifierPass` is not run after all of KLEE's custom passes (to make sure that they do not introduce any invalid constructs) but only after the optimization passes. So in this PR, I move the method to `KModule` and insert the `InstructionOperandTypeCheckPass` (which was in previously in `optimiseAndPrepare`). Finally, `checkModule()` is called from `Executor` right after `optimiseAndPrepare()`.
> run VerifierPass after optimization and instrumentation

- include/klee/SolverCmdLine.h
- lib/Basic/CmdLineOptions.cpp
- lib/Basic/ConstructSolverChain.cpp
@MartinNowack based on your suggestion, I renamed `--use-cache`.  As mentioned before, I'd like to go with `--use-branch-cache` to be in sync with the CAV'13 paper, which right now provides the best overview of KLEE's caching architecture.
> Renamed --use-cache to --use-branch-cache

- lib/Module/CMakeLists.txt
- lib/Module/KModule.cpp
- lib/Module/OptNone.cpp
- lib/Module/Passes.h
- test/Feature/srem.c
This is part of fixing #1008. It addresses a more general problem: KLEE's function calls are intented to annotate specific variables or parts of the code. But, we use `CFGSimplifierPass` that always runs after a module has been built even with optimisation disabled.
With newer LLVM versions, compiler optimisation got much better. The problem is that function calls (used as annotations) are hoisted and moved away from the  actual code position they should have been applied to in the first place. This leads to a couple of issues:
* less instances of a function call as they get optimised away (#1008)
* missing branch constraints as functions are called prematurely (#920 )
This patch works around this issue by disabling optimisation (`optnone`) on a function level.
It adds an additional pass …
> Fix klee call optimisation

- lib/Expr/Expr.cpp
- test/Expr/ReadExprConsistency.c
ObjectStates can be shared between multiple states.
A read expression of a symbolic object can be represented differently
depending on previous read expression on the same object.
If the read expression uses a symbolic index, all pending updates
will become entries in the update list of the object state.
If the same object state is read again, with a concrete index,
the latest update list item will be referenced, even though it might
contain more recent but non-essential updates.
If, instead, a concrete read will be executed first, it does not contain
the non-essential updates.
For both executions, the ReadExpr with a constant index will have two
different representations, which is not intented.
This patch makes sure, we do not include more recent, non-essential
updates for concrete …
> Fix representation of ReadExpr of equivalent arrays

- include/klee/Internal/Module/InstructionInfoTable.h
- lib/Core/CallPathManager.cpp
- lib/Core/CallPathManager.h
- lib/Core/Executor.cpp
- lib/Core/StatsTracker.cpp
- lib/Module/InstructionInfoTable.cpp
- lib/Module/IntrinsicCleaner.cpp
- lib/Module/KInstruction.cpp
- lib/Module/KModule.cpp
Currently, KLEE handles debug information on a best-effort basis based on the historic debug information with the following consequences:
- allocas at the beginning of an function has none or wrong debug information assigned
- function information is based on its first instruction that can be wrong due to inlining
- optimisation looses debug information
- debug information for instructions are sometimes wrong due to optimisations
This PR involves the following major changes:
* Separate function debug information tracking from instruction debug information tracking
* Utilise newer LLVM debug infrastructure if possible ( >= LLVM 3.7)
* Keep debug information as part of the module
* Tracks `columns` beside `linenumbers`
> Utilise newer LLVM debug information infrastructure

- CMakeLists.txt
I propose we bump the version number after each release to `<next-version>-pre`
> Moving to version 2.1-pre

- lib/Solver/STPSolver.cpp
- test/Solver/STPDumpDebugQueries.c
This PR removes some old-style boilerplate, fixes a missing `free()` and slightly changes the filling of the `values` vectors. I did some micro-benchmarks and the `emplace_back()` version should be faster than the old assignment/push_back code.
Still, we could save some copy operations when we don't need the actual cex values...
> STPSolver: C++11, add missing free(), refactoring

- test/Runtime/POSIX/GenBout.c
- test/Runtime/POSIX/GenRandomBout.c
- test/lit.cfg
- tools/gen-random-bout/gen-random-bout.cpp
This is to keep it up-to-date with the current ktest format, so that the output can be used as a seed.
* Added handling of `--sym-arg`
* Resolved the crash when minimum and maximum number of arguments for `--sym-args` are equal
* Replaced `range` with `n_args` produced by `--sym-args`
* Added `model_version` variable (constrained to 1), to prevent klee complaining about insufficient input
* Allow a single dash to prefix an option
* Arrange the elements in the correct order: command-line arguments, files, stdin, and lastly stdout
> Various updates to gen-random-bout.cpp

- Dockerfile
- scripts/build/d-klee-linux-ubuntu.inc
Fixes #1080. The proper LD_LIBRARY_PATH is required when binaries linked
with kleeRuntest are run.
The STP line is changed to extend the library path instead of replace
it, I am not sure if it can be removed at this moment.
> Add LD_LIBRARY_PATH to docker image

- .cirrus.yml
- runtime/POSIX/FreeBSD.h
- runtime/POSIX/fd_32.c
- runtime/POSIX/fd_64.c
- runtime/POSIX/illegal.c
- runtime/POSIX/stubs.c
- tools/gen-random-bout/gen-random-bout.cpp
This PR adds support for FreeBSD CI on Cirrus. Right now, some tests are failing due to LLVM packaging issue. It was reported to the maintainer and expected to be fixed soon.
> More FreeBSD fixes and FreeBSD CI.

- lib/Core/Executor.cpp
- lib/Module/IntrinsicCleaner.cpp
- test/Intrinsics/fabs.ll
This PR adds support for the `llvm.fabs` intrinsic, and adds a test.
The test fails with current KLEE during intrinsic lowering, as LLVM can not/does not lower `llvm.fabs` further.
To change this, we ignore calls to the `llvm.fabs` intrinsic during intrinsic lowering, and instead handle them during `Executor::executeCall`, where the implementation is straight-forward, using `llvm::abs()`.
I moved up the definition of `fpWidthToSemantics` as it now needs to be called earlier.
Note: A call to `llvm.fabs` usually results from using `math.h`'s `fabs()` (it does so for my clang 8.0). In order to not rely on the behavior of my compiler, I added a `.ll` file instead of a `.c` file (although it was generated from one) for the test.
> Implement handling of the llvm.fabs intrinsic

- lib/Core/PTree.cpp
- lib/Core/PTree.h
Minor clean-up and fix for `dump()`. Just in case you are curious how it looks like:
> PTree: fix dump() method

- include/klee/Constraints.h
- lib/Solver/CachingSolver.cpp
- lib/Solver/FastCexSolver.cpp
- lib/Solver/IndependentSolver.cpp
While testing our KLEE build infrastructure for compatibility with GCC 9, I noticed a bunch of `-Wdeprecated-copy` warnings being emitted.
This PR fixes those by refactoring `ValueRange` and `ConstraintManager` into a more modern (and arguably correct) fashion.
> -Wdeprecated-copy

- Dockerfile
Now commands like `docker run klee/klee klee --version` are possible.
> Solve issues with running as a command on docker run

- test/CMakeLists.txt
Build `gen-bout` and `gen-random-bout` before running tests
> Add missing dependencies for `check` target

- .travis.yml
- Dockerfile
- scripts/build/p-klee.inc
- scripts/build/v-klee.inc
Allow to build klee runtime with different build parameters using the build script.
Supersedes #1119
> Provide klee runtime build type as parameter

- test/CMakeLists.txt
- test/lit.cfg
- test/lit.site.cfg.in
Specifying `REQUIRES: uclibc` in a test currently disables the test on _all_ platforms due to the wrong variable being used to check for availability of this feature, which this PR fixes.
Some CI platforms (Xcode, freebsd) run without uclibc support, which is why I noticed this problem.
Also the way in which availability of the 'libcxx'-feature for tests was determined was redundant, so this PR also cleans that up.
> Fix two test issues (fix 'REQUIRES: uclibc' tests)

- CMakeLists.txt
- README-CMake.md
- cmake/find_llvm.cmake
- unittests/CMakeLists.txt
- unittests/TestMain.cpp
Fixes an issue that occurs with `-DUSE_CMAKE_FIND_PACKAGE_LLVM=1` and LLVM compiled from sources. LLVM exports `gtest` and `gtest_main` targets, which means they cannot be redefined by googletest build during KLEE's build process. In case LLVM already defined these targets, with this patch, the LLVM version of googletest is reused.
> CMake: enable reuse of LLVM's googletest src and targets

- runtime/POSIX/klee_init_env.c
- test/Runtime/POSIX/GenBout.c
- test/Runtime/POSIX/GenRandomBout.c
- tools/gen-bout/gen-bout.cpp
- tools/gen-random-bout/gen-random-bout.cpp
Both tests fail on my system where `cd` is a shell builtin and not an installed command. Not sure how that works in Docker... looks like `lit` uses `subprocess.Popen` without shell.
> tests: fix Gen(Random)Bout.c: cd - command not found

- tools/klee-stats/klee-stats
Grafana wasn't correctly displaying statistics because klee-stats was reading the time when klee started incorrectly. This fixes that, Grafana now produces graphs and statistics during runtime.
> Read Klee's start time correctly in klee-stats

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/ExecutorTimers.cpp
* creates two new methods: dumpStates, dumpPTree
#1114 needs some refactoring beforehand and this rarely used dumping functionality is completely in the wrong place. In the long run these functions should move into a StateManager and the PTree.
> ExecutorTimers: move dumpStates/dumpPTree into Executor

- scripts/build/patches/llvm38.patch
- scripts/build/patches/llvm40.patch
- scripts/build/patches/llvm50.patch
These are patches that were sufficient to build LLVM 3.8 - 5.0 with GCC 8.3 on my system, albeit without compiler-rt, libcxx and libcxxabi (which would require additional patching).
> build scripts: additional patches for LLVM 3.8-5.0

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/PTree.cpp
- lib/Core/PTree.h
- lib/Core/Searcher.cpp
This patch
* replaces `split()` with `attach()`
* adds `unique_ptr`s
* removes some unnecessary type aliases/abstractions
Overall it should make #1141 even shorter as the code duplication in Executor is not needed anymore.
> simplify PTree API

- test/regression/2014-09-13-debug-info.c
Do not use `klee_range()` in `regression/2014-09-13-debug-info.c` test, as it is incompatible with klee_prefer_cex. Fixes https://github.com/klee/klee/issues/1161
While there, remove dependence on `sort` utility, which might help porting KLEE
Windows eventually.
> Do not use klee_range() in regression/2014-09-13-debug-info.c test

- test/Expr/Evaluate2.kquery
- test/Feature/SolverTimeout.c
- test/lit.cfg
Get rid of some legacy code:
* Since LLVM version 3.6.0 or lit version 0.5.0, `lit_config` is the name of the global object, not `lit`.
* In `lit.cfg`, test whether the current LLVM version is in the set of known versions.
* re-enable `SolverTimeout.c` test that "occasionally fails when using Z3 4.4.1" (from 2015)
---
Other than this, I stumbled upon https://github.com/klee/klee/blob/0fd707b62988ed25c31242eb3d858895d96eb619/test/Expr/Evaluate2.kquery#L1-L5
which is in its current form since d786ba65b69c57fec0804d4a529682844ac2d411 stating "(query [false] false), which should return VALID, [...] currently returns INVALID". Indeed, Kleaver still returns INVALID, but I fail to see the reason why it should return VALID.
> Remove legacy from tests

- .travis.yml
- lib/Module/Checks.cpp
- lib/Module/IntrinsicCleaner.cpp
- lib/Module/KModule.cpp
- lib/Solver/SolverCmdLine.cpp
- runtime/klee-libc/bcmp.c
- test/Intrinsics/objectsize.leq80.ll
- test/Runtime/FreeStanding/freestanding_only.c
- test/lit.cfg
- tools/klee/main.cpp
Significant changes in LLVM since 8.0:
* [multiple `OptionCategory`s allowed](https://reviews.llvm.org/rL360179)
* [altered signature of `getOrInsertFunction()`](https://reviews.llvm.org/rL352827)
* [`@llvm.objectsize()` has four parameters instead of three](https://reviews.llvm.org/rL352664)
* [third field in `@llvm.global_ctors` and `@llvm.global_dtors` is no longer optional](https://reviews.llvm.org/rL360742)
* [`memcpy()` may be converted to `bcmp()` under certain circumstances](https://reviews.llvm.org/rL355672)
> add LLVM 9.0 support

- lib/Core/Executor.cpp
- test/regression/2019-08-02-missing-switch-default.ll
... when a case and default have same successor block.
I had to create an .ll file as test as the switch in C always gets lowered (or not optimised to single successor). The idea is the following: a case (here 5) and default have the same successor block:
```C
#include "klee/klee.h"
int __attribute__((optnone)) main() {
int cond;
klee_make_symbolic(&cond, sizeof(cond), "cond");
int ret = 0;
switch (cond) {
case 1: ret = 1; break;
case 5:
default:
ret = 5;
}
if (cond == 7) ret = 7;
}
```
When KLEE handles the switch instruction it only adds the default case when the successor basic block is not already in the set of successor blocks for the different cases ([src](https://github.com/klee/klee/blob/04f5031ce572fa7488c9d97155207a3f5832e212/lib/Core/Executor.cpp#L1865)). Hence, it misses the …
> Executor: fix missing default case in switch instruction

- .travis.yml
Travis OS X is complaining about an outdated version.
Use the default one instead of the old one.
This should fix all the build issues we currently observe related to Mac OSX.
> Use default travis OS X version instead of outdated old one

- runtime/POSIX/fd_64.c
glibc 2.30 moved definition of `getdents64` to dirent_ext.h. Hence, it
became visible to us (via dirent.h) and conflicts with our definition:
```
runtime/POSIX/fd_64.c:112:5: error: conflicting types for 'getdents64'
int getdents64(unsigned int fd, struct dirent *dirp, unsigned int count) {
^
/usr/include/bits/dirent_ext.h:29:18: note: previous declaration is here
extern __ssize_t getdents64 (int __fd, void *__buffer, size_t __length)
```
We use the parameters defined by kernel, not by userspace (libc). Both
glibc and uclibc define it as:
```
ssize_t __getdents64 (int fd, char *buf, size_t nbytes)
```
so follow it.
> runtime: fix for glibc 2.30

- lib/Core/Executor.cpp
`numSeeds` is unused since commit 4eb050e2999b (ExecutorTimers: refactor
and move to support lib), so remove it.
> Core: Executor, remove unused variable

- lib/Module/IntrinsicCleaner.cpp
- test/Intrinsics/objectsize.leq80.ll
- test/Intrinsics/objectsize.ll
`llvm.objectsize` is used in several optimisation during compile time. Lowering
these intrinsics took a conservative approach returning always the value for
unknown. Instead, try to evaluate it to get an object's real size and use this
value instead.
> Evaluate objectsize if possible

- include/klee/Expr/ExprVisitor.h
I don't see any reason for this ConstantExpr to be allocated and it actually takes a lot of time as these Action objects keep getting created when using ExprVisitor.
> [expr-visitor] Remove unnecessary allocation

- runtime/POSIX/FreeBSD.h
- runtime/POSIX/fd_64.c
Append "64" suffix to function names.
> Compile fd_64.c file of POSIX runtime correctly on FreeBSD

- scripts/build/p-klee-osx.inc
Python 2 should not be needed anymore, so we remove it from osx CI.
Also see #1186.
> Remove python2 from osx CI

- include/klee/MergeHandler.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/MergeHandler.cpp
- lib/Core/Searcher.cpp
- lib/Core/Searcher.h
- lib/Core/SpecialFunctionHandler.cpp
- lib/Core/UserSearcher.cpp
This PR moves merging-related functionality from the `Executor` to the `MergingSearcher`, as discussed in #762 (cc @MartinNowack).
I am not sure if the ordering of the `MergingSearcher` in `UserSearcher.cpp/klee::constructUserSearcher()` makes the most sense this way, but I moved it to the "top" of the searcher chain as that is what was discussed in #762.
> Move merging related code from Executor into MergingSearcher

- include/klee/ExecutionState.h
- lib/Core/ExecutionState.cpp
- lib/Core/Executor.cpp
- lib/Core/Searcher.cpp
- lib/Core/Searcher.h
- lib/Core/UserSearcher.cpp
Having both weight and depth in execution state is wasteful and imprecise,
therefore this patch removes weight.
Because nurs:depth is not actually biased by depth, but by weight, I renamed it to nurs:rp, because i I see it as poor mans random path. 
A new nurs:depth searcher is introduced that biases the search with depth,
making it the only other searcher that prefers to go deep (similar to dfs).
> [Searchers] Remove weight from execution state, add nurs_depth

- lib/Expr/ArrayExprOptimizer.cpp
- lib/Expr/ArrayExprOptimizer.h
- lib/Expr/ArrayExprVisitor.cpp
- lib/Expr/ArrayExprVisitor.h
- test/ArrayOpt/test_expr_arbitrary.c
- test/ArrayOpt/test_expr_mul.c
- test/ArrayOpt/test_mixed_hole.c
- test/ArrayOpt/test_update_list_order.c
- unittests/Expr/ArrayExprTest.cpp
- unittests/Expr/CMakeLists.txt
Keeping track of bugs this PR aims to fix in value array optimization:
> [optimize-array] Fix value transformation

- lib/Core/StatsTracker.cpp
- test/Feature/SourceMapping.c
Assuming a `klee-out-*` directory is moved to a different path location, subsequent analysis of the run.istats with KCachegrind focusing on assembly is impossible as the `assembly.ll` cannot be found.
The reason is that the absolute path of the object file (assembly.ll) is hard-coded as part of the generated run.istats.
To fix this, assume that the file is local to the `run.istats`.
> Assume assembly.ll is local to the run.istats file

- tools/klee/main.cpp
Currently, arbitrary *.bc files or archives containing .bc files (.bca or .a) can
be linked using `--link-llvm-lib`. Change documentation of command line argument to make this clear.
This feature is useful to keep avoid linking the bitcode libraries with the application as bitcode file in the first place.
Fix error message in case library could not be loaded.
> Fixed documentation for command line argument link-llvm-lib

- tools/klee-stats/klee-stats
- utils/grafana/Dockerfile
- utils/grafana/dashboard.yml
- utils/grafana/datasource.yml
- utils/grafana/grafana.ini
- utils/grafana/klee_dashboard.json
- utils/grafana/upload.sh
This Dockerfile provides a Grafana server with a preconfigured dashboard and a datasource that will connect to klee-stats, as soon as klee-stats is run. The log in screen is also disabled.
> Add Dockerfile for preconfigured Grafana

- tools/klee-stats/klee-stats
Allows to provide a different IP address for the flask server.
This way, one can allow a binding on all available IP addresses (i.e `--grafana-host="0.0.0.0"`).
> Add support to provide a specific host address and port for grafana server

- lib/Module/InstructionInfoTable.cpp
- test/Feature/SourceMapping.c
Fix tracking of filenames where functions are defined.
Extend test case to avoid duplicate file path elements.
> Fix handling of debug information of functions

- include/klee/Expr/ArrayCache.h
- include/klee/Expr/ExprHashMap.h
- lib/Solver/CachingSolver.cpp
Remove support for old tr1 unordered set and map.
And check hashes using call-by-reference instead of call-by-value to avoid inc/dec of reference counters.
> Remove tr1

- cmake/find_llvm.cmake
- scripts/build/p-llvm.inc
I tried out the modifications to the build scripts using LLVM's git monorepo just merged with #1208 on a non-Ubuntu machine, so building LLVM from scratch. This PR fixes two things I noticed during these trials.
The first is the usage of `LLVM_ENABLE_PROJECTS` in LLVM's CMake invocation which makes sure the build system can find the tool and project directories (for `clang` etc.) in lieu of symlinks. This flag is present (and as far as I can tell, working) from LLVM 4 on, which is why I restricted the creation of the symlinks to earlier versions. Without this change, LLVM 9.0 could not be compiled correctly.
The other one is that instead of the `svn` postfix, LLVM now reports its version with `git` when using a non-tagged version.
> Fix build scripts for LLVM's git monorepo

- tools/gen-bout/gen-bout.cpp
This PR makes the naming of argument object consitent between `gen-bout` and posix runtime.
Currently first arg name is `arg1` in `gen-bout` and `arg01` in posix runtime. This PR makes them both `arg01`
> [gen-bout] Add leading zeros to genbout

- tools/klee-stats/klee-stats
Refactor preparing and printing the table
The number and order of statistics in klee-stats is hard coded which makes adding new cumbersome.
Moreover, adding new statistics to KLEE lead to crashes.
Rewriting that part of the script generalises and streamlines the process.
List of changes:
* Extend legend: this is used for known columns to provide shorter names
* simplify sqlite handling and reading of data
* select columns based on internal KLEE names
* streamline addition of artificial columns
* handle the case if different runs should be compared but not all have the same statistics
* fix calculation of summary row:
- avg of column if column is showing a relative value or avg value
- max of column if column is showing a max value
- sum of column entries, else
* smaller refactorings
> Generalise klee stats

- lib/Core/StatsTracker.cpp
Create table before transaction otherwise we end up with an empty DB in case KLEE aborts before first commit (and `klee-stats` complains about missing table in SELECT...).
> stats: enforce table creation

- .travis.yml
- test/lit.cfg
WIP as LLVM 10 has not been released yet.
So far, these changes are enough to pass KLEE's systemtests.
However, this PR requires a docker image for LLVM 10 so TravisCI will pass.
> add LLVM 10.0 support

- lib/Module/KModule.cpp
The `InstructionCombinationPass` can insert vectorized code during KLEE's optimization step. As the `ScalarizerLegacyPass` is not run afterwards (again), these automatically vectorized code causes KLEE to encounter unexpected instructions later on.
As a concrete example, build KLEE's master branch with `KLEE_RUNTIME_BUILD_TYPE` set to `Release` and linked against LLVM 8 and consider the following simple example:
```C
#include <string.h>
int main() {
char arr[1024];
memset(arr, 0, sizeof(arr);
return arr[0];
}
```
Executing KLEE on this example with `-optimize` and the freestanding runtime will add vectorized code (`shufflevector` instructions) during the `InstructionCombiningPass` step in the optimization process. As the `ScalarizerLegacyPass` is not executed after the optimization step, …
> Automatically Vectorized Code is not Scalarized Correctly

- test/VectorInstructions/memset.c
This test exposes the failure fixed by #1102 in certain configurations.  I can reproduce it on my machine, but I want to double-check that our CI catches this failure before merging #1102.
> Additional test for dealing with vector instructions

- runtime/POSIX/fd.c
- test/Runtime/POSIX/Fcntl.c
This PR adds a simple model for GET/SET_LK `fcntl` commands. It basically assumes the program does the correct thing with locking. This is needed to  run  `sqlite3` with a symbolic db.
> [posix-runtime] Simple GET/SET_LK model

- lib/Solver/Z3Solver.cpp
Ensure that temp_builder is used when adding constant array value assertion constraints
> Z3SolverImpl::getConstraintLog bug-fix

- unittests/Solver/CMakeLists.txt
- unittests/Solver/Z3SolverTest.cpp
Adds the unit test discussed in #1235 after the merge.
> Add unit test for Z3Solver::getConstraintLog

- include/klee/Solver/SolverStats.h
- include/klee/Statistic.h
- lib/Basic/Statistics.cpp
- lib/Solver/SolverStats.cpp
- tools/kleaver/main.cpp
- tools/klee/main.cpp
* remove unused `queryConstructTime`
* rename `QueriesConstructs` to `QueryConstructs` to match internal/klee-stats naming
* minor update of the `Statistic` class definition
> stats: minor changes

- lib/Core/SpecialFunctionHandler.cpp
- test/Feature/ReadStringAtAddress.c
Add support for the cases where `"XXX interior pointer unhandled"` assertion in `readStringAtAddress` failed.
> Support reading string from middle of objects

- runtime/POSIX/fd.c
- test/Runtime/POSIX/SymFileConsistency.c
This PR fixes an issue where you give a full path to the symbolic file. While you could argue that we simply never use realpath for symbolic file, the program can itself infer the absolute path. By concatenating the working directory with the filename. This is what SQLite3 does, see this strace:
```strace
...
lstat("seed.db", {st_mode=S_IFREG|0644, st_size=2048, ...}) = 0
getcwd("/data/klee/build7.0/bin", 511)  = 24
stat("/data/klee/build7.0/bin/seed.db", {st_mode=S_IFREG|0644, st_size=2048, ...}) = 0
open("/data/klee/build7.0/bin/seed.db", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2048, ...}) = 0
...
```
This PR basically tries to skip the current work dir when getting the symbolic files.
> [posix-runtime] slightly improve model

- Dockerfile
This fixes #1240 , as per first solution proposed in the issue. This supersedes #1244 (a squashed version of it).
Co-authored with @MartinNowack .
> docker: install KLEE headers in system include path

- lib/Solver/STPBuilder.cpp
- lib/Solver/Z3Builder.cpp
- test/regression/2020-04-27-stp-array-names.c
Array names used for STP queries used to be restricted to 32 characters,
with the last characters replaced by a unique number.
Similarly, an array is made unique by `klee_make_symbolic`.
Unfortunately, both combined can lead to the generation of the same STP array name for different arrays.
This leads to wrong queries with invalid results.
This is more likely be triggered with longer names for `klee_make_symbolic`
Fixes #1257
> [Solver:STP] Fix handling of array names

- lib/Module/RaiseAsm.cpp
- test/Feature/asm_lifting.ll
ASM memory barriers with operands might be used to propagate values as result of their operation.
This is currently not supported.
Tighten condition to not lift those optimisations.
Fixes #1252
> [Module] Disable asm lifting for memory fences with return values

- lib/Core/ExecutionState.cpp
- lib/Core/ExecutionState.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
First commit slightly updates `ExecutionState` and removes hole(s) in struct. Second commit adds state IDs:
* adds `getID()`/`setID()`
* uses `ExecutionStateIDCompare` in `Executor::states` set
* outputs state id in `.err` files (we could also change the `.ktest` format)
What's still missing is the fix for `DiscretePDF`. The question is how we fix it, in our projects I just compare by IDs but this might slow KLEE down a little bit for we have to dereference the states.
> Add state IDs and sort states in Executor::states by ID

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/ExecutorUtil.cpp
- test/Feature/Alias.c
- test/regression/2019-05-30_known-bitcast-alias.ll
- test/regression/2019-05-30_unknown-bitcast-alias.ll
- test/regression/2019-05-31_simple-unknown-bitcast-alias.ll
Aliases in LLVM IR are allowed to have either a global value (such as a function) or a constant expression (such as a bitcast of a function) as their aliasee. Further, there are no restrictions on the order in which of aliases and their eventual targets may be defined in the module.
This fixes the issue that while trying to initialize an alias, its aliasee (or one of its sub-expressions) is not yet initialized, which (in some cases) led to a segfault or (in other cases) went unnoticed. The patch included in this PR resolves all subexpressions first, in case the aliasee is not (immediately) a global value that has already been initialized.
I included the various regression tests for this issue and extended the existing `Alias.c` feature test.
While fixing the underlying issue, I also split …
> Fix GlobalAlias Initialization

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- test/Feature/MemoryLimit.c
This PR
* extends help messages for `-max-memory` and `-max-memory-inhibit`
* introduces `branchingPermitted()` to check fork limits
* enforces fork/branch limits in `branch()` (vector version)
* replaces `rand()` with `RNG` in `checkMemoryUsage()` (keep it? - initialized with `srand(1)`)
* changes the main loop
* calls `updateStates()` before `checkMemoryUsage()`
* calls `updateStates()` again in case we early terminate states
This should prevent double termination (see #952) for now. Other solutions are imho more expensive as we would have to compare possibly large vectors of states (either states(`arr`) in `checkMemoryUsage()` or `removedStates` in `terminateState()`).
> RFC: Enforce fork/branch limits in branch() and fix double termination

- lib/Core/Executor.cpp
- lib/Module/IntrinsicCleaner.cpp
- test/Intrinsics/fshlr.ll
- tools/klee/main.cpp
Changes:
- IntrinsicCleaner accepts fshr/fshl as accepted intrinsics
- Executor::executeCall converts fshr/fshl to urem/zext/concat/shift/extract
- Klee/main suppresses warnings about externals that are LLVM reserved
(i.e., begin with "llvm.")
- New test exercises 32 and 7 bit versions including oversize shift values
Test values are based on LLVM's test for fshl/fshr
Resolves #1272 
See also: unsupported intrinsics #678
> Implement fshr/fshl intrinsics

- include/klee/ADT/RNG.h
- include/klee/Support/OptionCategories.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/Searcher.cpp
- lib/Core/Searcher.h
- lib/Core/UserSearcher.cpp
- lib/Support/ErrorHandling.cpp
- lib/Support/RNG.cpp
- unittests/CMakeLists.txt
- unittests/RNG/CMakeLists.txt
- unittests/RNG/RNGTest.cpp
- unittests/Searcher/SearcherTest.cpp
* move global theRNG into Executor (we should introduce an ExecutionContext and remove that useless InterpreterXXX inheritance)
* pass theRNG via ctor to searchers
* remove some type warnings from RNG.cpp
Fixes #1023.
> introduce --rng-initial-seed=<unsigned>

- include/klee/klee.h
- runtime/Intrinsic/klee_is_replay.c
- runtime/Runtest/intrinsics.c
- test/Replay/libkleeruntest/replay_detection.c
This instrinsic detects whether the program is being executed
symbolically or concretely (i.e., using the libkleeRuntest library).
The intended usage (illustrated in the test program) is to
allow the test program to display the input values by invoking
any libraries it wants to.
This is especially valuable if you are constructing complex,
structured values and for languages like Rust (or C++) that have
rich libraries and print libraries.
For example, you might pick a symbolic value N with the
assumption "0 <= N < 10" and then pick N symbolic
values and write them to an array.
The resulting ktest file is a bit hard to understand compared with the
output of the standard print function in Rust/C++.
> New intrinsic: klee_is_replay

- cmake/find_llvm.cmake
This change allows KLEE to be configured to use the LLVM version
that comes with the Rust compiler instead of a standard version.
e.g., one might configure with
-DLLVM_CONFIG_BINARY=${RUST_SRC}/build/x86_64-unknown-linux-gnu/llvm/bin/llvm-config
For which typical output might be
10.0.1-rust-dev
> Tweak LLVM version string parser: support rust

- include/klee/ADT/DiscretePDF.h
- include/klee/ADT/DiscretePDF.inc
- lib/Core/Searcher.cpp
- lib/Core/Searcher.h
* order states by ID and not pointer value
* fixes whitespace and typo (propogate)
* see #1274
* fixes #739
Remark: Haven't done any benchmarks yet.
> DiscretePDF: use IDs instead of pointers

- runtime/klee-libc/__cxa_atexit.c
- test/Runtime/klee-libc/cxa_thread_atexit_impl.c
This function is usually a weak symbol but, in KLEE, this behaves like a call
to an unknown function and chaos ensues.
Worse, it happens just as the program is cleanly shutting itself down,
so programs that are cleanly exiting crash with the wrong message.
> Stub definition of __cxa_thread_atexit_impl

- lib/Core/Executor.cpp
- lib/Module/IntrinsicCleaner.cpp
- test/Intrinsics/Missing.ll
- If an unknown intrinsic appears in the bitcode file,
it is reported but execution can proceed.
- If an unknown intrinsic is encountered during execution of some path,
- the intrinsic is reported
- this path is treated as an error
- execution of other paths can proceed
To be more precise, there is a list of "known unknown intrinsics".
Intrinsics not on this list will prevent execution.
> More robust handling of unknown intrinsics

- lib/Core/PTree.cpp
- lib/Core/PTree.h
- unittests/Searcher/SearcherTest.cpp
`PTree::remove` not only removes the given node in the process tree but also walks up the tree to remove parent nodes with no other children. However, when this process finishes we're at a node with only a single child; this pull request adds code to remove that node as well. Otherwise the process tree keeps unnecessary intermediate nodes, allowing it in the extreme case to degrade to a very long linked list with only a single execution state at the end.
> Improve PTree::remove

- .travis.yml
Potential fix for the build issue for the Mac platform.
Mainly, it's switching to the travis-provided means of handling brew packages.
Beside that, older infrastructure parts are removed that are not needed in this context.
> Fix travis mac build

- scripts/build/run-tests.sh
Argument `-y` has been removed from the upload script.
https://github.com/codecov/codecov-bash/commit/c2f935a0dd0590d20296e95a759782e32b311b34
But `.codecov.yml` is now supported
> Fix codecov upload

- test/Replay/klee-replay/KleeZesti.c
- test/lit.cfg
- tools/gen-bout/gen-bout.cpp
- tools/klee-zesti/CMakeLists.txt
- tools/klee-zesti/klee-zesti
This patch adds a new tool, that adds a zesti like interface to standard `KLEE`.
For example with this PR and given that you have `klee` and `gen-bout` in PATH you can run somethign like:
```
$ ../../scripts/zesti.py -cex-cache-try-all --max-time=7200 --search=random-path --max-memory=4000 -only-output-states-covering-new --simplify-sym-indices --solver-backend=stp --disab
le-inlining -watchdog --libc=uclibc --posix-runtime --external-calls=all --run-in-dir=/tmp/sandbox --switch-t
ype=simple ls.bc -lh
KLEE: KLEE: WATCHDOG: watching 1799
KLEE: NOTE: Using POSIX model: /data/klee/build/Debug+Asserts/lib/libkleeRuntimePOSIX.bca
KLEE: NOTE: Using klee-uclibc : /data/klee/build/Debug+Asserts/lib/klee-uclibc.bca
KLEE: output directory is "/data/klee/build7.0/bin/klee-out-11"
KLEE: Using STP …
```
> Add ZESTI like interface as a wrapper script

- include/klee/Support/ModuleUtil.h
- lib/Core/Executor.cpp
- lib/Core/ExternalDispatcher.cpp
- lib/Core/Searcher.cpp
- lib/Core/StatsTracker.cpp
- lib/Module/KModule.cpp
- lib/Module/ModuleUtil.cpp
This is in preparation for LLVM 11 support as the `llvm:CallSite` class has been removed.
There is quite a lot of changes so I decided to split this PR in two parts.
> Replace llvm::CallSite with llvm::CallBase (LLVM 11 1/2)

- lib/Module/ModuleUtil.cpp
- test/Feature/GlobalVariable.ll
Global variables were not handled correctly while validating direct call targets.
This lead to crashes of KLEE.
This PR adds this case to handle direct call targets.
> Handle global variables

- lib/Core/Executor.cpp
- test/Feature/FNeg.ll
- test/regression/2020-01-14-fabs-compare.c
The first commit is a fix by @dlaprell for an issue he found in the `fabs` intrinsic implementation a while ago, along with a regression test. However, the test fails starting with LLVM 10, because floating point negation is now using the [fneg](https://releases.llvm.org/8.0.0/docs/LangRef.html#fneg-instruction) instruction introduced with LLVM 8 (instead of using `fsub`). The second commit therefore implements `fneg`, together with a test.
> fix fabs intrinsic, implement fneg instruction

- lib/Core/Executor.cpp
This PR gets rid of the following `-fsanitize=vptr` (of [UBSan](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html), requiring RTTI) message:
```
lib/Core/Executor.cpp:3318:28: runtime error: downcast of address 0x604000418b90 which does not point to an object of type 'KGEPInstruction'
0x604000418b90: note: object is of type 'klee::KInstruction'
17 00 00 43  90 e9 49 03 00 00 00 00  b8 77 16 00 80 60 00 00  90 12 82 00 30 60 00 00  30 47 12 00
^~~~~~~~~~~~~~~~~~~~~~~
vptr for 'klee::KInstruction'
```
As the pointer never gets used after a wrong cast, this is rather an annoyance than an actual error.
***
> Silence vptr-Sanitizer Report in Executor

- runtime/klee-libc/bcmp.c
- test/Runtime/klee-libc/bcmp.c
This was executing the loop when n==0 leading to an out of bound pointer
error.
Found while verifying Rust code that compares strings.
> fix: bcmp (n==0 and ignoring last byte)

- test/Feature/KleeStatsCsv.test
- tools/klee-stats/klee-stats
While working on #1294 I realised that we only dump a single `run.stats` file via `--to-csv`. As it is often required to use the data in figures, spreadsheets etc. I've added two more table modes: `csv` and `rcsv` (readable/aligned csv). Both are based on tabulate. `csv` could be implemented without tabulate but for simplicity I re-used the code for `rcsv`.
> klee-stats: add (readable) csv format (--table-format=readable-csv/csv)

- include/klee/ADT/Ref.h
- include/klee/Expr/Expr.h
- include/klee/Support/Casting.h
- lib/Core/ExecutionState.cpp
- lib/Core/Executor.cpp
- lib/Core/Memory.cpp
- lib/Core/SpecialFunctionHandler.cpp
- lib/Expr/ArrayExprOptimizer.cpp
- lib/Expr/ArrayExprRewriter.cpp
- lib/Expr/ArrayExprVisitor.cpp
- lib/Expr/AssignmentGenerator.cpp
- lib/Expr/ExprBuilder.cpp
- lib/Expr/ExprEvaluator.cpp
- lib/Expr/ExprPPrinter.cpp
- lib/Expr/ExprSMTLIBPrinter.cpp
- lib/Expr/Updates.cpp
- lib/Module/FunctionAlias.cpp
- lib/Solver/IndependentSolver.cpp
As previously suggested in #1081, this PR adds `operator bool()` to `klee::ref<>`.
In addition to using this for replacing various `.isNull()` and `.get()` patterns throughout the code, I also introduced `Casting.h` to make `isa_and_nonnull` from LLVM available across the codebase (including older LLVM versions).
***
> Modernize ref<> and isa<> nullptr checks

- runtime/klee-libc/fortify-klibc.c
> Declare mempcpy on macOS, to silence compiler warnings

- runtime/CMakeLists.txt
With this PR I fix various issues with the `CFLAGS` used for various runtime build types (introduced by #1250)
- `-DNDebug` -> `-DNDEBUG`: the latter is specified by the C standard, and a quick test with clang found that its preprocessor is case sensitive
- different flags for `Release{+Debug,}+Asserts`: before, both had the same flags
- `-g` is no longer part of common flags: i.e. it is no longer set for Release builds (before: Debug builds just had `-g -g`, while Release had `-g`)
- `-D_DEBUG` is now only set for debug builds
- removed unused `LIB_BC_FLAGS_{32,64}`: `-m32` is already added a few lines above
- added example, architecture prefix for specific flags: currently, there is no way to select a runtime that does not have an architecture prefix
***
> Fix Runtime CFLAGS

- CMakeLists.txt
- README-CMake.md
This PR removes some legacy from the build system:
- a comment mentioning "the old build system"
- `ENABLE_TESTS` variable, marked for removal in #569
- a mention of `MAKE_BINARY` (which was removed in #1250) in `README-CMake.md`
***
> retire some build system legacy

- include/klee/klee.h
> klee.h: fix compiler warnings (function declaration is not a prototype)

- CMakeLists.txt
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/SpecialFunctionHandler.cpp
- lib/Core/SpecialFunctionHandler.h
- lib/Module/IntrinsicCleaner.cpp
- test/lit.cfg
- tools/klee/main.cpp
This PR (mainly) restores KLEE's old behavior in case that Exception Handling is disabled (LLVM version < 8, no libc++abi headers available, CMake variable disabled). In addition, some more renaming, messages at startup informing whether EH support is available and removing a special case that was only required by an earlier (never merged) version of C++ EH support.
***
> C++ / Exception Handling Improvements

- runtime/POSIX/fd_64.c
commit 8ed005daf0ab of glibc-2.33 (Remove stat wrapper functions, move them to exported symbols) removed renames of `__fxstat`, `__xstat`, and `__lxstat` to `__fxstat64`, `__xstat64`, and `__lxstat64`, respectively.
But we relied on the renames to build `fd_64.c` properly. With glibc 2.33, we now see link failures of the POSIX runtime:
```
error: Linking globals named '__xstat': symbol multiply defined!
```
Rename the functions using `__REDIRECT_NTH` in the code as `__USE_FILE_OFFSET64` case (which we define at the top of the file by `#define _FILE_OFFSET_BITS 64`) did exactly that.
Fixes #1384.
> runtime/POSIX: fix failures with glibc-2.33

- CMakeLists.txt
Fixes warnings issued by CMake 3.19.6:
```
CMake Warning (dev) at CMakeLists.txt:75 (set):
implicitly converting 'String' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.
...
CMake Warning (dev) at CMakeLists.txt:478 (set):
implicitly converting 'String' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
> cmake: Fix warning about implicit type conversion

- test/lit.cfg
Adds LLVM 11.1 to lit.cfg otherwise `make systemtests` fails on Arch which is already on LLVM 11.1. Version bump is in: https://github.com/llvm/llvm-project/commit/b6164d967e010ed54ed8ce0d4a3ea19f54e90108 but not sure if it was officially released yet.
---
> tests: add support for LLVM 11.1

- lib/Solver/Z3Solver.cpp
Sometimes it happens that `ctrl-c` shortcut is used while KLEE is being inside the function ` Z3_solver_check`. 
The current behavior: KLEE prints **"Unexpected solver failure. Reason is "interrupted from keyboard,""** and aborts. `interrupt_handle` is not invoked even if you do return just before abort.
Expected behavior: KLEE clears resources of Z3, calls `interrupt_handle` and goes as usual.
Would you consider these changes?
To help expedite the review please ensure the following, by adding an "x" for each completed …
> [Z3] Handle the case when interruption caught by Z3

- CMakeLists.txt
- cmake/cmake_uninstall.cmake.in
`make uninstall` is enabled.
Without this, uninstalling was done manually with `rm` command.
```sh
sudo make uninstall
```
> [100%] Uninstalling...
> -- Uninstalling /usr/local/include/klee/klee.h
> -- Uninstalling /usr/local/lib/klee/runtime/libkleeRuntimeFreestanding64_Release.bca
> ...
> [100%] Built target uninstall
I referred Z3 and STP build system to add this feature, each of which supports `make uninstall`. One thing I failed is to remove the progress number above. (That doesn't appear for Z3 and STP...) However after digging in cmake documentation, I concluded that it is too time-consuming.
> Add cmake custom target `uninstall`

- test/CMakeLists.txt
CMake 3.19+ started to issue warnings if this policy is set to OLD:
```
CMake Deprecation Warning at test/CMakeLists.txt:143 (cmake_policy):
The OLD behavior for policy CMP0026 will be removed from a future version
of CMake.
The cmake-policies(7) manual explains that the OLD behaviors of all
policies are deprecated and that a policy should be set to OLD only under
specific short-term circumstances.  Projects should be ported to the NEW
behavior and not rely on setting a policy to OLD.
```
This PR tries to fix that.
> cmake: Fix CMP0026 policy deprecation warning

- scripts/build/run-tests.sh
- test/CMakeLists.txt
- test/CXX/LandingPad.cpp
- test/Expr/Parser/Concat64.kquery
- test/Feature/PreferCex.c
- test/lit.cfg
- test/regression/2014-09-13-debug-info.c
It may happen that some older instance of `klee` is already present in `PATH`.  All tests that call plain `klee` instead of `%klee` may use it and then unexpectedly fail.
This PR will make all tests that rely on KLEE tools being explicitly in `PATH` fail in the CI.  From now on, only LLVM tools, `FileCheck` and `not` will be in `lit`'s `PATH`.
> Assert that all tools in tests in CI are invoked through their corresponding macros 

- tools/klee-replay/file-creator.c
Increase the size of the buffer to `PATH_MAX` in `create_link` as that is the maximal possible length of `fname` and check whether output truncation occurred.
Fixes:
```
tools/klee-replay/file-creator.c: In function 'create_file':
tools/klee-replay/file-creator.c:55:31: warning: '%s' directive output may be truncated writing up to 4095 bytes into a region of size 64 [-Wformat-truncation=]
55 |   snprintf(buf, sizeof(buf), "%s.lnk", fname);
|                               ^~
......
344 |   target = tmpname;
|            ~~~~~~~
In file included from /usr/include/stdio.h:866,
from tools/klee-replay/file-creator.c:16:
/usr/include/bits/stdio2.h:70:10: note: '__snprintf_chk' output between 5 and 4100 bytes into a destination of size 64
70 |   return __builtin___snprintf_chk (__s, __n, …
```
> klee-replay: Fix `-Wformat-truncation` warning

- test/Concrete/ConcreteTest.py
Some Linux distributions, e.g. Fedora, do not install the unversioned Python binary by default and Python 2 has been dead for more than a year.
> test/Concrete: Use Python 3 in `ConcreteTest.py` explicitly

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- test/Feature/MaxStaticForkPct.c
This PR does the following:
1. fixes the silent concretization reported in #526 
2. refactors the code handling --max-static-*pct into a separate function thus partially addressing #527 
3. adds a new --max-static-pcc-heck-delay to replace the hardcoded time delay after these checks are enforced
4. adds a test case for these arguments, as the code was not tested by the current test suite
> Fixed silent concretization and refactored the code handling --max-static-*pct

- .cirrus.yml
- include/klee/Core/Interpreter.h
- lib/Core/Executor.cpp
- test/CXX/symex/libc++/uncaught_exception.cpp
- test/Feature/SilentKleeAssume.c
- test/Feature/consecutive_divide_by_zero.c
- test/Feature/srem.c
- test/Intrinsics/Missing.ll
- test/regression/2020-02-24-count-paths-nodump.c
- tools/klee/main.cpp
Originally part of #1343:
Although I don't like the misleading output of "completed paths", it should also count states when we do not dump states at the end. You can observe it with current upstream KLEE:
`klee -dump-states-on-halt=false -max-instructions=1 program.bc`
outputs:
`KLEE: done: completed paths = 0`
This fix adds `states.size()` to that counter.
**Edit:**
As discussed below this PR now splits the path summary into "completed" and "partially completed" paths.
---
To help expedite the review please ensure the …
> Fix path stats for disabled state dumping

- scripts/build/p-klee-linux-ubuntu.inc
Codecov depends on git to detect the SHA sum of the repository.
Install as a dependency.
Warning message from codecov:
```
2021-09-13T08:59:56.7220068Z   _____          _
2021-09-13T08:59:56.7220767Z  / ____|        | |
2021-09-13T08:59:56.7221266Z | |     ___   __| | ___  ___ _____   __
2021-09-13T08:59:56.7221738Z | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
2021-09-13T08:59:56.7222216Z | |___| (_) | (_| |  __/ (_| (_) \ V /
2021-09-13T08:59:56.7222716Z  \_____\___/ \__,_|\___|\___\___/ \_/
2021-09-13T08:59:56.7224450Z                               Bash-1.0.6
2021-09-13T08:59:56.7225219Z 
2021-09-13T08:59:56.7225641Z 
2021-09-13T08:59:56.7231885Z [0;33m==>[0m git not installed, testing for mercurial
2021-09-13T08:59:56.7242361Z [0;31m==>[0m git nor mercurial are installed. Uploader may …
```
> Install git as a requirement for codecov

- test/Feature/KleeStatsColumns.test
- tools/klee-stats/klee-stats
Currently `klee-stats --print-all` prints the last columns in varying order. With this fix we keep the same order every time to make it easier to join .csv files.
Before (headers with 5 runs on the same directories):
```Bash
|              Path              |    Instrs|  Time(s)|  TUser(s)|  ICov(%)|  BCov(%)|  ICount|  TSolver(s)|  TSolver(%)|  States|  AvgStates|  Mem(MB)|  Queries|  AvgQC|  Tcex(s)|  Tcex(%)|  Tfork(s)|  Tfork(%)|  TResolve(s)|  TResolve(%)|  QCexCMisses|  QCexCHits|  NumQueryConstructs|  QueryTime|  maxState|  maxMem|  RelUserTime|  TimedOutQueries|  avgMem|  ArrayHashTime|  MadviseCalls|  PartialBranches|  NumBranches|  InhibitedForks|  NumAllocs|  AllQueries|  QueryCacheHits|  CoveredInstructions|  QueryCacheMisses|  MaxRSS|  ExternalCalls|  FullBranches| …
```
> klee-stats: order remaining columns alphabetically

- lib/Core/Executor.cpp
Since KLEE requires C++14, we should prefer `nullptr` to plain `0`.
> Core/Executor: use `nullptr` instead of `0`

- tools/ktest-tool/ktest-tool
`ktest-tool` silently exits when an object for `--extract` can't be found. It now prints a warning message and exits with error code `1`, e.g.:
Before:
```Bash
> ktest-tool --extract Z --extract A-data test000096.ktest        
```
After:
```Bash
> ktest-tool --extract Z --extract A-data test000096.ktest        
Could not find object: Z
```
or:
```Bash
> ktest-tool --extract Z --extract A-data --extract B-data --extract C-Data test000096.ktest
Could not find objects: B-data, C-Data, Z
```
> ktest-tool: --extract: warn if object can't be found

- lib/Core/ExecutionState.cpp
- lib/Core/ExecutionState.h
- lib/Core/Executor.cpp
- lib/Core/Memory.h
- lib/Core/SpecialFunctionHandler.cpp
- test/Replay/libkleeruntest/replay_cex_after_assumed_malloc.c
- test/Replay/libkleeruntest/replay_cex_incorrect_result.c
There is some problem with handling preferCex. Sometimes addresses initialized in some state, but Klee try to read them from another state. Sometimes it causes the segfault.  
The file which create this error is also attached to pull-request as new system-test.
Also after this cnahge first parameter of preferCex has no effect and now it is only for compability.
> Fix crash of KLEE on preferCex() function on some code

- CMakeLists.txt
Before this change, we created a symlink to the given library in their expected
location and then installed the original library.  This was problematic as the
install directives are performed the order they are encountered during the
configure step and the installation of directory containing the symlink was
processed after the installation of the original library.  Therefore, the
original libraries were installed but were subsequently overwritten by the
symlinks.
This commit changes the behaviour so that we create hard links in the expected
location and install them together with the rest of the KLEE runtime as was
originally intended.
> There are test cases for the code you added or modified OR no such test cases are required.
I found this issue when I was adding uClibc to KLEE package …
> cmake: do not create symlinks to `klee-uclibc` and `klee-libcxx`

- runtime/POSIX/FreeBSD.h
- runtime/POSIX/stubs.c
> Use more precise version check for selecting swapoff() signature.

- lib/Core/SpecialFunctionHandler.cpp
- test/Feature/MakeSymbolicAPI.c
Removed outdated klee_make_symbolic_name reference and extended the test MakeSymbolicAPI
> Removed outdated klee_make_symbolic_name reference and extended the test MakeSymbolicAPI

- tools/gen-random-bout/gen-random-bout.cpp
There is no need to use stat64 explicitly in gen-random-bout.  This also eliminates some warnings on e.g., macOS.
> Do not use stat64 directly in gen-random-bout

- unittests/CMakeLists.txt
- unittests/TestMain.cpp
KLEE currently supports (and recommends) Google Test version 1.7.0. For newer versions (current: 1.11.0), however, there are certain issues:
- Google Test itself was moved into a `googletest` subdirectory (1.8.0+), as `googlemock` was added right next to it. This means **`GTEST_INCLUDE_DIR` has to be set manually** as it can no longer be derived automatically from `GTEST_SRC_DIR`. Note that adding the subdirectory to `GTEST_SRC_DIR`, while seemingly working for some versions, leads to issues in at least the most current version as it results in inclusion of the wrong `CMakeLists.txt` file.
- Google Test's `gtest_main` uses `__FILE__` (and thus a path to the file) for its "Running main() from" line, but `llvm-lit` (which we use to invoke unit tests) currently matches exactly "Running …
> Improve Google Test Integration and Version Support (for Unit Testing)

- lib/Core/CoreStats.cpp
- lib/Core/CoreStats.h
- test/Feature/KleeStats.c
- test/Feature/KleeStatsColumns.test
- test/Feature/KleeStatsNoBr.c
- tools/klee-stats/klee-stats
KLEE:
* removes `reachableUncovered` (unused)
klee-stats:
* show MaxMemory as float (before rounded integer, often < AvgMem)
* show MiB instead of MB (to reflect computation)
* fixes BCov calculation when no `br` instructions in bitcode
* extends/adapts some tests
* reorders/renames columns in `klee-stats` to
* increase consistency
* improve readability by grouping topic-wise
* add missing and (hopefully) improve documentation for stats in --help message
* add `--print-columns` to print user-defined columns, e.g. `--print-columns 'Path,Instrs,Time(s)'`
RFC:
* I'd also remove
* `TFork` from KLEE as it is misleading and not well implemented
* and maybe: `RelUserTime` (`TUser(%)`) from `klee-stats` - not sure what this is good for (we already have `TUser(s)` and for short run times it's just …
> some fixes/extensions for klee-stats

- unittests/CMakeLists.txt
When building KLEE with `-DUSE_CMAKE_FIND_PACKAGE_LLVM=1` and an LLVM with source tree that does not export target `gtest`, we will use the GTest sources that come along LLVM. One of the changes made by #1458 is that `gtest_main` is no longer used because we cannot reliably control the source from which it will be build. However, it will still be built and in case of the LLVM version includes LLVM specific headers. I thus removed a line too much in my last PR which I am re-adding here. Otherwise, the compilation of `gtest_main` will fail like this:
```
llvm/llvm/utils/unittest/UnitTestMain/TestMain.cpp:9:10: fatal error: llvm/Support/CommandLine.h: No such file or directory
9 | #include "llvm/Support/CommandLine.h"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
> Fix building GTest from LLVM sources

- scripts/build/p-clang-linux-ubuntu.inc
- scripts/build/p-llvm-linux-ubuntu.inc
`build.sh` hangs as `grep` waits for input in two cases
- [ x There are test cases for the code you added or modified OR no such test cases are required.
> build: fix missing target for grep

- test/Runtime/POSIX/FD_Fail.c
/etc/mtab doesn't exist in the Nix build sandbox since /etc doesn't
exist. However, /dev/zero is more common on UNIX systems and does.
> Fix FD_Fail test in nix sandbox

- include/klee/System/MemoryUsage.h
- lib/Support/MemoryUsage.cpp
- test/Feature/MemoryLimit.c
Fixed GetTotalMallocUsage on macOS and a few small updates related to this functionality. 
Note that the test MemoryLimit.h fails without this fix on macOS 12.1
> Fixed GetTotalMallocUsage on macOS and a few small updates related to this functionality 

- lib/Core/StatsTracker.cpp
Remove unnecessary call to deprecated function sqlite3_enable_shared_cache, which triggers a warning on macOS. 
From https://sqlite.org/c3ref/enable_shared_cache.html: "Shared cache is disabled by default. It is recommended that it stay that way. In other words, do not use this routine."
> Remove unnecessary call to deprecated function sqlite3_enable_shared_cache

- Dockerfile
The current Dockerfile sets up the PATH variable to point to an incorrect llvm directory.  This interferes with easily running `clang`.  This lazy PR fixes it.
> Update the Dockerfile to use the correct path for llvm-110

- CMakeLists.txt
- include/klee/Config/config.h.cmin
- lib/Support/MemoryUsage.cpp
Fix deprecation warning with newer glibc.
> use mallinfo2 if available

- lib/Core/ExecutionState.cpp
- test/Feature/StackTraceOutput.c
Beforehand the stack traces in `.err` files looked a bit odd:
```
#000000026 in foo (i, k=12) at test.c:7 // with symbol names
#100000050 in main () at test.c:15
```
or
```
#000000025 in foo (, =12) at test.c:7 // without symbol names
#100000048 in main () at test.c:15
```
I've slightly modified it to:
```
#000000026 in foo(i=symbolic, k=12) at test.c:7
#100000050 in main() at test.c:15
```
and
```
#000000025 in foo(symbolic, 12) at test.c:7
#100000048 in main() at test.c:15
```
> .err files: minor readability changes to stack trace output

- Dockerfile
As a follow-up to recent build script enhancements
(https://github.com/klee/klee/commit/818275b7249250780ddd5ed021cae64288514270),
finally build KLEE inside of the Docker image as artefact owned by the
`klee` user, including user-installed Python3 modules.
This fixes issues with non-writable build directories.
In addition `$HOME/.local/bin` directory is made available in search path.
> Use `klee` user to install system dependencies

- test/Feature/EntryPoint.c
- tools/klee/main.cpp
KLEE crashes, when a user call it with argument `--entry-point=""`. I fix this situation with check that `--entry-point` is non-empty.
Closes #1522
> Fix error with empty EntryPoint

- lib/Solver/MetaSMTBuilder.h
- lib/Solver/STPBuilder.cpp
- lib/Solver/Z3Builder.cpp
This deals with a long-standing `FIXME` in the KLEE codebase where `getArrayForUpdate` is implemented recursively, which could lead to KLEE crashing. This PR transforms the recursive code into an iterative version.
This of course introduces a potential performance penalty by storing the required information in an explicit stack on the heap instead of the implicit function call stack. While I personally don't think the performance penalty is a problem, queries with a small (but non-zero) amount of uncached update nodes will incur additional `malloc`s now.
> Implement getArrayForUpdate iteratively

- include/klee/Module/KCallable.h
- include/klee/Module/KModule.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/ExternalDispatcher.cpp
- lib/Core/ExternalDispatcher.h
- lib/Module/KModule.cpp
- test/Feature/InlineAsm.c
- test/regression/2012-05-13-asm-causes-aborts.c
- test/regression/2022-06-28-asm-causes-error.c
- tools/klee/main.cpp
The wrapper (`KCallable`) was created for the objects (`Function, InlineAsm`) that can be called in LLVM IR. Now `callExternalFunction` takes the `KCallable` wrapper as an argument. In the `ExternalDispatcherImpl::createDispatcher` function     was  added a code branch to process inline assembler code (the `llvm::IRBuilder<>.CreateCall` function call with the `InlineAsm` object as a parameter).
Closes #1514.
> Inline assembly support (external call)

- cmake/fstatat.c
- runtime/POSIX/CMakeLists.txt
- runtime/POSIX/fd.c
When compiling POSIX runtime with glibc it spills out several warnings:
```
/klee/runtime/POSIX/fd.c:573:19: warning: nonnull parameter 'path' will evaluate to 'true' on first encounter [-Wpointer-bool-conversion]
(path ? __concretize_string(path) : NULL), buf, (long)flags);
^~~~ ~
/usr/include/sys/stat.h:266:14: note: declared 'nonnull' here
__THROW __nonnull ((2, 3));
^
/usr/include/sys/cdefs.h:390:28: note: expanded from macro '__nonnull'
^
/usr/include/sys/cdefs.h:384:57: note: expanded from macro '__attribute_nonnull__'
```
This PR tests if `path` is declared nonnull via cmake and removes the ternary operator in that case (but adds an `assert` just to be safe).
Another fix would have been to just disable the warning :man_shrugging:
```C
#pragma GCC diagnostic push
#pragma GCC …
```
> POSIX runtime: fstatat: check for nonnull path APIs

- include/klee/Expr/Expr.h
- lib/Core/Executor.cpp
- lib/Expr/Expr.cpp
- test/VectorInstructions/external_call.c
Extend the maximum width of arguments and return values up to 512 bits in order to accept SIMD vectors.
Closes #1488.
> Support arguments of width 128, 256 and 512 bits for external calls

- runtime/klee-libc/__cxa_atexit.c
Corrected wrong usage of klee_report_error in __cxa_atexit handler. Presumably, the last argument should contain extension `.err` as in other usages.
> Corrected wrong usage of klee_report_error in __cxa_atexit handler

- lib/Solver/Z3Solver.cpp
`Z3_TRUE` was removed in z3 4.11.0.  The release notes say to use `true` instead.  Indeed, from z3 4.8. (released in 2018) through 4.10.2 (released recently), `Z3_TRUE` was a macro that expanded to `true`.  Prior to that, in z3 4.7.1 and older, `Z3_TRUE` was a macro that expanded to 1.
I'm not sure I understand what you want me to do with clang-format.  It leaves the lines I modified unchanged, although running clang-format on `lib/Solver/Z3Solver.cpp` does make some changes, unrelated to this patch.
> Use true instead of Z3_TRUE (removed in z3 4.11.0)

- lib/Module/IntrinsicCleaner.cpp
- test/Intrinsics/noalias-scope-decl.ll
New `llvm.experimental.noalias.scope.decl` intrinsic [appeared](https://llvm.org/docs/LangRef.html#llvm-experimental-noalias-scope-decl-intrinsic) in LLVM 12.0 which purposes to identify where a noalias scope is declared and accepts `metadata` as an argument. Execution of that call usually causes an error as shown in the example of stacktrace below:
```
klee: /mnt/c/Work/klee-simd-runtime/lib/Core/Executor.cpp:1232: const klee::Cell &klee::Executor::eval(klee::KInstruction *, unsigned int, klee::ExecutionState &) const: Assertion `vnumber != -1 && "Invalid operand to eval(), not a value or constant!"' failed.
#0 0x00007fa241a35ef3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/x86_64-linux-gnu/libLLVM-12.so.1+0xbd8ef3)
#1 0x00007fa241a341e2 llvm::sys::RunSignalHandlers() …
```
> Pass llvm.experimental.noalias.scope.decl to IntrinsicLowering so that it strips out these intrinsics

- test/Feature/VarArgByVal.c
This PR fixes the test `Feature/VarArgByVal.c`. The test was passing but not checking anything since
since the following `RUN` FileCheck-directive was missing a colon and thus was never executed:
https://github.com/klee/klee/blob/667ce0f1ef33c32fbe2d1836fc1b334066e244ca/test/Feature/VarArgByVal.c#L7
The `FileCheck` command is also broken since `FileCheck` takes only one positional argument and `klee-last/assembly.ll` is not found.
Besides fixing these issues, the `CHECK` directive was extended to actually match the intended lines.
> fix FileCheck cmd of VarArgByVal test

- tools/klee-replay/klee-replay.c
These fixes some leaks in klee-replay reported in #1512.
While these particular leaks are not important, we should get to a stage where LSan & ASan runs pass.
> Fixed some leaks in klee-replay

- test/Merging/unexpected_close.c
While the the test contained `CHECK` directives, it was missing an invocation of `FileCheck`, which is added with this PR.
> add missing FileCheck command to Merging/unexpected_close test

- tools/klee/main.cpp
Creating `klee-last` as a relative symlink (instead of referring to an absolute path) makes the result stay correct even if moved.
This is especially important when running KLEE in a docker container, as the mapped path may differ from the host path (or other mapped paths).
> Create `klee-last` as a relative symlink

- include/klee/Expr/ArrayExprVisitor.h
- lib/Expr/ArrayExprVisitor.cpp
- test/ArrayOpt/test_multindex_multarray.c
Previously, the code did two consecutive checks.  First one succeeded
only if the given index was not already seen and the second one did
an analogous check but for arrays.  However, if the given index usage
was already detected for some array, its usage for another array that
already had some other index detected would be silently skipped and the
`incompatible` flag would not be set.
Therefore, if the code contained e.g. the following conditional jump on two
arrays with two symbolic indices, the multi-index access would remain
undetected:
```c
if ((array1[k] + array2[x] + array2[k]) == 0)
```
Resulting in the following output:
```
KLEE: WARNING: OPT_I: infeasible branch!
KLEE: WARNING: OPT_I: successful
```
EDIT: major description rewrite so that it's much easier to understand the …
> `ConstantArrayExprVisitor`: Fix detection of multiple array indices 

- CMakeLists.txt
- lib/Basic/CMakeLists.txt
- lib/Core/CMakeLists.txt
- lib/Expr/CMakeLists.txt
- lib/Module/CMakeLists.txt
- lib/Solver/CMakeLists.txt
- lib/Support/CMakeLists.txt
- test/CMakeLists.txt
- tools/kleaver/CMakeLists.txt
- unittests/CMakeLists.txt
With recent LLVM versions, this should allow to link against dynamic LLVM libraries.
Let's if this builds with our setup, i.e. through all LLVM versions.
> Change `llvm_map_components_to_libnames` to `llvm_config` CMake function

- lib/Solver/STPSolver.cpp
- test/Solver/STPswitchSAT.c
This PR enables KLEE to switch the underlying SAT solver for STP:
```bash
$ klee --stp-sat-solver=simpleminisat test.bc
KLEE: Using STP solver backend
KLEE: SAT solver: simplifying MiniSat
```
```bash
$ klee --stp-sat-solver=riss test.bc
KLEE: Using STP solver backend
KLEE: WARNING: RISS not supported by STP
KLEE: Fallback SAT solver: CryptoMiniSat
...
```
Background: I use the STP version from my Linux distribution that bundles MiniSat and CryptoMiniSat. Unfortunately, CryptoMiniSat is the default which was ineffable slow with KLEE in the past (haven't checked recently).
> STP: make SAT solver configurable

- runtime/POSIX/fd.c
Fixes an unused variable warning that occurs for configurations in which asserts are disabled for the runtime.
> fix unused variable warning

- scripts/build/p-llvm-linux-ubuntu.inc
Ubuntu-provided packages were not correctly installed/detected.
Necessary to reduce build time for KLEE's Uclibc CI
> Fix detection and installation of Ubuntu-provided llvm/clang packages

- tools/klee-replay/file-creator.c
Fixes another set-but-unused variable warning.
> fix unused variables warning

- include/klee/Core/Interpreter.h
- include/klee/Statistics/Statistic.h
Otherwise we see errors like this with gcc13:
include/klee/Statistics/Statistic.h:31:10: error: no type named 'uint32_t' in namespace 'std'
> include cstdint for *int*_t

- .github/workflows/differential-shellcheck.yml
This change will ensure that the ShellCheck action will scan `.inc` shell scripts.
The feature was added via:
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/232
Follow-up to https://github.com/klee/klee/pull/1548#issuecomment-1481632582
/cc @MartinNowack
> Run ShellCheck on `*.inc` shell scripts

- include/klee/KDAlloc/allocator.h
- unittests/KDAlloc/allocate.cpp
- unittests/KDAlloc/rusage.cpp
- unittests/KDAlloc/sample.cpp
Not a very major issue, but I noticed a few confusing / outdated comments in KDAlloc code, which I propose to change.
Summary:
- mappings were only shared in a former version of KDAlloc
- `AllocationFactory(std::size_t, std::uint32_t)`'s second parameter is used for quarantine size, not the location of the mapping
> change some obsolete KDAlloc comments

- include/klee/ADT/RNG.h
- lib/Support/RNG.cpp
- unittests/RNG/RNGTest.cpp
KLEE contains its own PRNG implementation (a version of the (32 bit) original mersenne twister, if I read `include/klee/ADT/RNG.h` right).
We can remove this and just rely on the standard C++ `<random>` instead, which allows us to remove a bunch of code, and improve our general random number handling (e.g., by using `std::uniform_int_distribution` instead of the modulo operator to pick without bias).
As the actual implementation of `std::uniform_int_distribution` and friends (but *not* the random number generators `std::mt19937` and `std::mt19937_64`) differ between platforms, this PR currently only includes the changes that should be uncontroversial.
This PR removes >130 lines of code this way.
> Replace KLEE's mersenne twister with std::mt19937

- test/Solver/2016-04-12-array-parsing-bug.kquery
- test/Solver/FastCexSolver.kquery
- test/regression/2016-03-22-independence-solver-missing-objects-for-assignment.kquery
- tools/ktest-gen/ktest-gen.cpp
- tools/ktest-randgen/ktest-randgen.cpp
Modify names of SMT variables to use underscores instead of dashes in the ktest-(rand) gen tools and tests.  This is a follow-up of #1152, where the renaming was incomplete.
> Modify names of SMT variables to use underscores instead of dashes

- include/klee/KDAlloc/allocator.h
- include/klee/KDAlloc/mapping.h
- include/klee/KDAlloc/suballocators/loh.h
- include/klee/KDAlloc/suballocators/sized_regions.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/MemoryManager.cpp
- lib/Core/MemoryManager.h
This PR contains a number of small KDAlloc improvements. Amongst minor API work, they should primarily increase logging and behavior when the mapping cannot be allocated. Additionally, a better algorithm for LOH deallocation should improve speed and reduce memory usage for LOH quarantine by half, all the while being vastly simpler.
> KDAlloc Improvements

- test/Feature/EntryPointMissing.c
- tools/klee/main.cpp
This also fixes an abnormal termination when --entry-point and --libc=uclibc are used together (#1572) Add tests for missing entry points.
> Refactored and fixed the code dealing with the entry point

- test/Feature/KleeStatsColumns.test
- test/Feature/KleeStatsCsv.test
- test/Feature/KleeStatsEmpty.test
The sqlite3 databases used for the stats are journalled and potentially must be written to. Therefore, the sqlite3 driver used by `klee-stats` requires write permissions on the database files.
By copying the stats files to the test directory, we can now compile and test an out-of-tree build without requiring any write permissions on the source folder at all.
> Copy stats to test directory when running tests

- .clang-format
I noticed that the `.clang-format` file still references C++11; however, [the documentation of `clang-format`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#standard) told me that this is actually not quite true anymore:
- "`Cpp11` is a deprecated alias for `Latest`"
- `Latest`: "Parse and format using the latest supported language version." (for some time already: C++20)
I'm not sure how relevant this really is, but since I stumbled on it anyway, I've just set the value to `c++17` to make it fixed to the currently supported C++ version which I believe was also the intention before.
> .clang-format: c++17

- CMakeLists.txt
- cmake/fstatat.c
- include/klee/Config/config.h.cmin
- runtime/POSIX/CMakeLists.txt
In #1484, @251 successfully fixed a compiler warning. If I understand his changes correctly, however, the second part of keeping the old implementation for header files that do not assume `pathname` to be `nonnull`, seems to have not worked out so well... :wink: 
In short: #1484 introduced a CMake variable `FSTATAT_PATH_ACCEPTS_NULL` and acts on its value via `#ifdef` in 
https://github.com/klee/klee/blob/8301eecbd0ba1ada6cfb3a1fd9da195b6be0ee16/runtime/POSIX/fd.c#L571-L576
However, the value never makes it from CMake into C, as there is no corresponding `#cmakedefine` in `config.h`.
This PR fixes this problem and refactors the code slightly to use `check_c_source_compiles()` instead of a separate file.
> Fix `fstatat()` null-path detection

- lib/Core/Searcher.cpp
- lib/Core/Searcher.h
- test/regression/2020-04-11-batching-search-zero-time-budget.c
`BatchingSearcher` has a feature that automatically adjusts the time budget if too much time has passed between two `selectState()` calls. However, there is a bug: The budget is also increased when it was initially disabled (set to 0). Through the increase, the time budget is enabled and thus, `BatchingSearcher` effectively picks a very arbitrary time budget on its own.
Because I believe that the hard-to-read implementation of the function contributed to this bug being introduced, I also refactored it and hopefully made it more readable.
> Fix `BatchingSearcher` ignoring disabled time budget

- test/Feature/StackTraceOutput.c
This test previously had a REQUIRES line with `geq-llvm-7.0`. Because LLVM version 7.0 is no longer "known" (`test/lit.cfg`), the required feature is not available and the test is discarded as unsupported by `llvm-lit`.
The additional commit cleans the test up a bit (use of `@LINE`, rearrange `CHECK`s, `clang-format`).
> Re-enable `StackTraceOutput.c` test

- tools/ktest-gen/ktest-gen.cpp
The current build throws a warning with gcc 13:
```
klee/tools/ktest-gen/ktest-gen.cpp:39:13: warning: ‘void push_range(KTest*, const char*, unsigned int)’ defined but not used [-Wunused-function]
39 | static void push_range(KTest *b, const char *name, unsigned value) {
|             ^~~~~~~~~~
```
> ktest-gen: remove unused function

- README-CMake.md
- unittests/CMakeLists.txt
This PR restores the ability to reuse a `gtest` target exported by LLVM's build tree. This feature was broken by #1569 which removed `AddLLVM.cmake` (required for building LLVM's version of Google Test) globally. After #1569 and this PR, the `gtest` target now needs to be reused whenever `LLVM_DIR` is pointed to an LLVM build tree (think: the result of `make` instead of `make install`) and `LLVM_INCLUDE_TESTS` is `ON` (the default). In particular, this corner of KLEE's build system is no longer hidden behind the `USE_CMAKE_FIND_PACKAGE_LLVM` flag (obsoleted by #1569 and removed in the last spot by this PR). Without this PR, one will instead be just greeted by an error when KLEE tries to build Google Test (the `gtest` target is already defined). When `LLVM_INCLUDE_TESTS` is `OFF`, KLEE …
> Fix reusing LLVM's Google Test target & source

- unittests/CMakeLists.txt
This PR removes some obsolete code from `unittests/CMakeLists.txt`:
- policy CMP0077 does not need to be set with CMake 3.16.0 as minimum version (bumped by #1587)
- the `UNITTEST_MAIN_LIBS` variable is no longer set (obsoleted by #1588)
In addition it refactors two things:
- If `GTEST_SRC_DIR` is not found automatically, the error message previously complained that the `Google Test source directory "GTEST_SRC_DIR-NOTFOUND" cannot be found.`
- Most (current) versions of Google Test actually set proper (public) include directories themselves, document and set the include directory ourselves when necessary.
This PR is self-contained in that it only addresses issues in a single file.
**NOTE:** This PR also contains the two commits from #1626 (due to a conflicting change).
> Updates to `unittests/CMakeLists.txt`

- tools/ktest-randgen/ktest-randgen.cpp
Fixes the following compiler warning:
```
tools/ktest-randgen/ktest-randgen.cpp: In function ‘void create_stat(size_t, stat*)’:
tools/ktest-randgen/ktest-randgen.cpp:118:15: warning: pointer ‘filename’ used after ‘void free(void*)’ [-Wuse-after-free]
118 |     error_exit("%s:%d: Error writing %s\n", __FILE__, __LINE__, filename);
|     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tools/ktest-randgen/ktest-randgen.cpp:117:9: note: call to ‘void free(void*)’ here
117 |     free(filename);
|     ~~~~^~~~~~~~~~
```
> Fix `ktest-randgen`: use after free

- lib/Core/SpecialFunctionHandler.cpp
- lib/Core/SpecialFunctionHandler.h
We can get rid of quite some lines with the only downside of having to write `SpecialFunctionHandler::HandlerInfo` three times more.
> SpecialFunctionHandler: use `std::array` for handlerInfo

- runtime/POSIX/fd.c
- test/Runtime/POSIX/FilePerm.c
Rewrote has_permission in the POSIX runtime. We now only return with permission error a single time in symbolic execution mode.
The rewrite also fixes a bug reported in #1230.
Rewrote the FilePerm.c test accordingly.
> Rewrote and fixed has_permission in the POSIX runtime

- unittests/Ref/RefTest.cpp
This commit suppresses the following warning (introduced with GCC 13, clang apparently added this earlier), which warns about precisely the situation that we want to test:
```
[147/164] Building CXX object unittests/Ref/CMakeFiles/RefTest.dir/RefTest.cpp.o
klee/unittests/Ref/RefTest.cpp: In member function ‘virtual void RefTest_SelfMove_Test::TestBody()’:
klee/unittests/Ref/RefTest.cpp:99:7: warning: moving ‘r’ of type ‘klee::ref<Expr>’ to itself [-Wself-move]
99 |     r = std::move(r);
|     ~~^~~~~~~~~~~~~~
klee/unittests/Ref/RefTest.cpp:99:7: note: remove ‘std::move’ call
```
> RefTest: suppress `-Wself-move`

- include/klee/KDAlloc/allocator.h
- include/klee/KDAlloc/suballocators/cow_ptr.h
- include/klee/KDAlloc/suballocators/sized_regions.h
- lib/Core/Executor.cpp
- unittests/KDAlloc/randomtest.cpp
This MR adds a few checks on the returned `LocationInfo`s in KDAllocs random test. As these checks fail, we then reimplement the LOH location info functionality in the same style as its (newer) `getSize` functionality. This makes the improved test pass again =).
The bugs that this PR should fix revolve around potential null pointer dereferences (in the treap, we used to do `&*node->lhs` in the hope that it returns a null pointer if `node->lhs` does not hold a value, which it does not) and wrong assumptions (the predecessor is only guaranteed to exist at the very end).
This change makes `getSize` and `getLocationInfo` look very similar for the treap. They are not quite the same, as they look up slightly different information. At the moment we have no use for a combined function that would …
> Kdalloc location info

- unittests/KDAlloc/CMakeLists.txt
- unittests/KDAlloc/allocate.cpp
- unittests/KDAlloc/randomtest.cpp
- unittests/KDAlloc/reuse.cpp
- unittests/KDAlloc/sample.cpp
- unittests/KDAlloc/stacktest.cpp
Simplifies KDAlloc tests by:
1. Removing the ability to use them for simple benchmarks against `std::malloc`. (Rationale: We use KLEE runs to compare against the `std::malloc` based allocator, reduces complexity)
2. Removing an unused define (`KDALLOC_CHECKED` is not honored anymore, as all checks are now asserts, as per the merge of KDAlloc into mainline KLEE)
3. Reorganizing the use of `USE_GTEST_INSTEAD_OF_MAIN` to be more localized.
> Simplify KDAlloc tests

- lib/Solver/CexCachingSolver.cpp
Removed broken experimental optimisation for validity (`--cex-cache-exp`).  A crash bug triggered by this experimental optimisation was reported in #1654 and having thought about this, it is non-trivial to get this optimisation right, and as the comments already suggest, unclear if it would lead to performance gains.
> Remove broken experimental optimisation for validity (--cex-cache-exp)

- lib/Core/MemoryManager.cpp
- test/Feature/DoubleFree.c
- test/Feature/MultipleFreeResolution.c
- test/Feature/OneFreeError.c
- test/regression/2007-10-11-illegal-access-after-free-and-branch.c
Changed some tests to assume KDAlloc and made KDAlloc the default memory allocator.
Based on the recent experiments with KDAlloc in the group, I think we are ready to make it the default option!
> Change some tests to assume KDAlloc and make KDAlloc the default memory allocator.

- include/klee/KDAlloc/suballocators/slot_allocator.h
This just removes a warning in C++20 compilers and should have no impact on behavior at all.
> replace deprecated (as of c++20) std::is_pod with std::trivial && std::is_standard_layout

- include/klee/Expr/Assignment.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/SeedInfo.cpp
- test/Feature/SeedConcretizeExtendFP.c
- test/Feature/SeedConcretizeExternalCall.c
- test/Feature/SeedConcretizeFP.c
- test/Feature/SeedConcretizeMalloc.c
- test/Feature/SeedConcretizePatchedFP.c
- test/Feature/SeedExtension.c
- test/Runtime/POSIX/SeedAndFail.c
Concretize values based on seeds when available.  The three commits handle the cases of concretizing an expression via toConstant, performing an external call with symbolic arguments and calling malloc with a symbolic argument, respectively. 
Each case is accompanied by a test. 
The PR is based on #1117 by @hoangmle
> Concretize values based on seeds when available, remove --zero-seed-extension and improve/fix seeding code

- test/Feature/VarArgByVal.c
I ran a bunch of KLEE builds with LLVM 15 and 16, and got a bunch of test failures like the following:
```
$ ":" "RUN: at line 8"
$ "FileCheck" "/klee/test/Feature/VarArgByVal.c" "--input-file=/klee/build/test/Feature/Output/VarArgByVal.c.tmp.klee-out/assembly.ll"
/klee/test/Feature/VarArgByVal.c:12:11: error: CHECK: expected string not found in input
// CHECK: call void (ptr, i32, i64, ...) @test2(ptr sret(%struct.foo) align 8 %tmp, i32 noundef {{.*}}, i64 noundef {{.*}}, i32 noundef {{.*}}, ptr noundef byval(%struct.foo) align 8 {{.*}}, i64 noundef {{.*}}, ptr noundef byval(%struct.bar) align 8 {{.*}}, ptr noundef byval(%struct.foo) align 8 {{.*}}, ptr noundef byval(%struct.bar) align 8 {{.*}})
^
/klee/build/test/Feature/Output/VarArgByVal.c.tmp.klee-out/assembly.ll:645:170: note: …
```
> Fix brittleness in Feature/VarArgByVal test

- lib/Core/Executor.cpp
`ExternalCallPolicy::All` was incorrectly used instead of `ExtCallWarnings::All`.  This happened to work correctly as currently the two are assigned the same value.
> Fixed incorrect reference in ExternalCallWarnings

- test/Feature/TargetMismatch.c
Remove the unnecessary not Darwin requirement for the test TargetMismatch.c
> Remove the not Darwin requirement for the test TargetMismatch.c

- lib/Core/ExecutionTree.cpp
- lib/Core/ExecutionTreeWriter.cpp
Rename `ptree-batch-size` to `exec-tree-batch-size`, and `compress-execution-tree` to `compress-exec-tree`.  Fix an incorrect reference to `--write-exec-tree`.
> Fix some inconsistent execution tree options

- lib/Core/Executor.cpp
- lib/Core/Executor.h
- test/Feature/ExtCall.c
- test/Feature/ExtCallOverapprox.c
- test/Feature/SeedConcretizeExternalCall.c
This PR, based on #1520, fixes the concretization of arguments following an external call with symbolic arguments.  
It also introduces a new external call policy, where the symbolic inputs are left unconstrained following such a call, useful for certain external calls such as printf. 
Relevant tests are also added or updated.
> Fixes the concretization of symbolic arguments following an external call, and introduces a new external call policy

- scripts/build/p-libcxx.inc
- scripts/build/p-llvm.inc
In commit 2b07721, support was added to p-libcxx.inc & p-llvm.inc for LLVM versions 14+ (in which, apparently, certain build flags were changed). To detect these recent versions, the variable LLVM_VERSION_SHORT was compared numerically to "14"-- the intent obviously being to express "LLVM version 14 or later".
However, in both v-clang.inc & v-llvm.inc, LLVM_VERSION_SHORT is defined as the concatenation of LLVM_VERSION_MAJOR and LLVM_VERSION_MINOR. Therefore, on a machine with, say, LLVM 13.0 installed, LLVM_VERSION_SHORT will be "130" which compares as larger than "14".
This patch changes the comparison to be against "140" which I believe captures the original intent.
RE the final checkbox-- I've tested this on my machine locally by building libcxx. I'm not sure what formal tests might be …
> Compare LLVM_VERSION_SHORT to "140" rather than "14".

- lib/Core/AddressSpace.cpp
- lib/Core/AddressSpace.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/Memory.cpp
- lib/Core/Memory.h
- test/Feature/ConcretizeSymbolicExternals.c
Before, external changes to symbolic variables have not been propagated
back to their internal representation.
Do a byte-by-byte comparison and potential update if required.
The test case is based on the example provided by Mingyi Liu from the
mailing list.
> Correctly update symbolic variables that have been changed externally

- test/lit.cfg
If the tabulate library is looked up via `PYTHONPATH`, we need to forward that variable through `lit` to the tests, so that `klee-stats` can find it.
This came up during investigation of the nix building issues mentioned in #1690, but is not necessary to solve those (making sure that the "right" python is first in `PATH` already does the trick).
> add pythonpath to lit forwarded env vars

- .github/workflows/build.yaml
- include/klee/Solver/IncompleteSolver.h
- lib/Solver/AssignmentValidatingSolver.cpp
- lib/Solver/CachingSolver.cpp
- lib/Solver/CexCachingSolver.cpp
- lib/Solver/IndependentSolver.cpp
- lib/Solver/QueryLoggingSolver.h
- lib/Solver/STPSolver.h
- lib/Solver/ValidatingSolver.cpp
- lib/Solver/Z3Solver.cpp
- lib/Solver/Z3Solver.h
Addressed missing override warnings emitted by recent compilers, such as:
```
klee/lib/Solver/ValidatingSolver.cpp:35:8: warning: 'computeValue' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
bool computeValue(const Query &, ref<Expr> &result);
^
klee/include/klee/Solver/SolverImpl.h:87:18: note: overridden virtual function is here
virtual bool computeValue(const Query& query, ref<Expr> &result) = 0;
```
Also reformatted nearby declarations.
> Addressed missing override warnings emitted by recent compilers; Fixes recent MSan issues

- lib/Core/SpecialFunctionHandler.cpp
- test/Runtime/POSIX/_exit.c
- tools/klee/main.cpp
This adds a handler for `_Exit` to handle it the same way `_exit` is handled, and also a test case.
Previously, calling `_Exit` would result in an external call, terminating KLEE.
While `_Exit` was initially introduced with C99, it's now also [part of POSIX.1-2008](https://www.man7.org/linux/man-pages/man2/exit.2.html)
> Add _Exit function handler

- .github/workflows/build.yaml
Fixed bug that disabled the CI tests for the Linux targets.
Without the `|`, the two run lines were concatenated and the merged line errored -- while `sysctl` emitted an error, the exit code was still 0, which hid the issue. 
Introduced in https://github.com/klee/klee/pull/1707/
Thanks to @ocelaiwo for reporting it.
> Fix bug that disabled the CI tests for the Linux targets

- tools/klee-replay/file-creator.c
- tools/klee-replay/klee-replay.c
klee-replay references `PATH_MAX`, but the corresponding header `<limits.h>` was not included.
Seems like with `glibc` it gets transitively included, but this is not the case with `musl-libc` toolchain.
> fix(klee-replay): add missing `<limits.h>` includes

- scripts/build/p-clang-linux-arch.inc
- scripts/build/p-clang-linux-debian.inc
- scripts/build/p-libcxx-linux-arch.inc
- scripts/build/p-libcxx-linux-debian.inc
- scripts/build/p-libcxx.inc
- scripts/build/p-llvm-linux-arch.inc
- scripts/build/p-llvm-linux-debian.inc
This patch adds files `p-{clang,llvm,libcxx}-linux-debian.inc`; this will greatly speed-up Debian & Arch builds when LLVM has been installed via the distribution-specific packages.
Remove the extra "lib*" directory level in `install_libcxx()` when building form LLVM version < 14. At least on Debian, using LLVM 13.0 from the apt repos, this doesn't exist & breaks bitcode extraction.
- N/A: There are test cases for the code you added or modified OR no such test cases are required.
Note to reviewers: I believe the "SpellCheck" errors to be spurious.
> Specialize the build for some expensive components for Arch & Debian.

- lib/Solver/IndependentSolver.cpp
Fixing [this FIXME](https://github.com/klee/klee/blob/master/lib/Solver/IndependentSolver.cpp#L482) - replacing raw pointers with `std::unique_ptr` within `IndependentSolver` and removing all `delete`s. I also refactored `getAllIndependentConstraintsSets` in this way but if that is too big of a change, happy to revert to https://github.com/klee/klee/pull/1727/commits/87b23e6d434f34d325a4ef1abf004a8284517119 instead.
> Prefer `std::unique_ptr` within `IndependentSolver`

- lib/Core/ExecutorUtil.cpp
- lib/Module/IntrinsicCleaner.cpp
- lib/Module/KLEEIRMetaData.h
- lib/Module/OptNone.cpp
- lib/Module/Passes.h
- lib/Module/RaiseAsm.cpp
- lib/Support/ErrorHandling.cpp
- tools/klee/main.cpp
See #1739 for previous discussion. I was asked to open a separate PR for the LLVM 17 compatibility patches, this now also includes LLVM 19 (at least, it compiles).
They deprecated `startswith` in LLVM 18 and removed it in LLVM 19. To stay compatible with LLVM 13 I changed it to `.find()` instead of `#if` and duplicating the code.
> LLVM 17-19 compatibility

- lib/Support/MemoryUsage.cpp
[GCC 14 supports `__has_feature()`](https://gcc.gnu.org/gcc-14/changes.html) to be compatible with Clang.
However, GCC still does not ship the header file `<sanitizer/allocator_interface.h>`.
The current handling code thus leads to the following error when comping KLEE with ASan support and GCC 14.2:
```
klee/lib/Support/MemoryUsage.cpp: In function ‘size_t klee::util::GetTotalMallocUsage()’:
klee/lib/Support/MemoryUsage.cpp:56:48: error: ‘__asan_get_current_allocated_bytes’ was not declared in this scope; did you mean ‘__asan_get_current_fake_stack’?
56 | #       define ASAN_GET_ALLOCATED_MEM_FUNCTION __asan_get_current_allocated_bytes
|                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
klee/lib/Support/MemoryUsage.cpp:91:10: note: in expansion of macro …
```
> fix ASan support for GCC 14 (and modernize it)

- test/Feature/WriteXML.c
- tools/klee/main.cpp
Add an option to generate XML test cases. This PR revives #1181.
> Add an option to generate XML test cases
