scripts/klee-clang
Provide clang-based alternative to klee-gcc
=> Add klee-clang as alternative to klee-gcc

include/klee/Expr.h, include/klee/util/ArrayCache.h, lib/Core/Executor.cpp, lib/Core/Executor.h, lib/Core/Memory.cpp, lib/Core/Memory.h, lib/Core/MemoryManager.h, lib/Expr/ArrayCache.cpp, lib/Expr/Expr.cpp, lib/Expr/Parser.cpp, unittests/Expr/ExprTest.cpp, unittests/Solver/SolverTest.cpp, utils/sanitizers/lsan.txt
Note KLEE is still leaking (see ``utils/sanitizers/lsan.txt``) in other places. I will be investigating these other leaks soon.
=> Try to fix leaking Array objects detected by ASan.

lib/Expr/Parser.cpp
the ``ParserImpl`` it wouldn't free allocated ``Identifier``s
=> Fix a leak detected by ASan in the KQuery parser where on destruction of

lib/Solver/IndependentSolver.cpp
@holycrap872 I decided to try and fix the leak in the independence solver myself.
I'd appreciate it if you could take a look seeing as you are the original author of the code I'm trying to fix. The second commit is the interesting one. The first commit is just a clean up of the code formatting to improve readability and conform to our coding style.
=> Fix independence solver leak

include/klee/Expr.h, include/klee/util/Assignment.h, lib/Expr/Assigment.cpp, lib/Expr/Expr.cpp
This is motivated by some out-of-tree work I'm doing with KLEE right now.
=> A few Expr related clean ups

lib/Expr/ExprPPrinter.cpp
The address of KLEE-internal data structures should not influence the
order arrays are printed out.
Order arrays by name.
=> ExprPPrinter: Print out arrays deterministically

lib/Solver/STPBuilder.cpp, lib/Solver/Z3Builder.cpp
As different arrays in a execution state can have the same name, they name still needs to be unique for STP/Z3 expression generation. The previous approach used the address of the allocated array to unique them. The new approach just uses the growing size of the already hashed arrays to generate a unique name.
Beside simplifying the names, it allows to generate names deterministically based on the order arrays are inserted and makes generated STP queries comparable (the same for Z3 queries).
=> Generate unique STP and Z3 array names deterministically

lib/Core/Executor.cpp, lib/Core/ExecutorTimers.cpp
Print timeout information to both stderr and messages.txt
=> Use klee_message for timeout information

lib/Core/Executor.cpp, lib/Core/Executor.h, lib/Core/ExecutorTimers.cpp, lib/Core/Searcher.cpp, lib/Core/Searcher.h, test/Feature/DeterministicSwitch.c
Respect the order of the added states by putting them in a vector instead of a set.
=> Deterministic state addition/removing

lib/Solver/STPBuilder.cpp, lib/Solver/STPBuilder.h, test/regression/2016-04-14-sdiv-2.c
Currently just for discussion.
=> Fix variable shifting

lib/Solver/MetaSMTSolver.cpp, lib/Solver/STPSolver.cpp
Some error outputs were missing \n, so add the new line to all of
them.
Signed-off-by: Jiri Slaby <jslaby@suse.cz>
=> fprintf: convert to klee_warning

lib/Solver/QueryLoggingSolver.cpp
=> Fix to #445

lib/Core/SpecialFunctionHandler.cpp, test/regression/2016-08-06-klee-get-obj-size.c
Implementation of the solution for #446 as I described it in the issue report
=> Fix for #446

lib/Core/Executor.cpp, lib/Module/Passes.h, lib/Module/RaiseAsm.cpp, test/Feature/RaiseAsm.c
Improved support for assembler handling.
Providing additional triple information
to raise assembler for supported architectures
only.
Implemented support for raising full assembly
memory fence.
Added initial support for memory fences in Executor.
=> Extended support for assembler raising

.travis.yml
Use newer Ubuntu system 14.04.
=> Use newer trusty-based Travis CI

.travis/metaSMT.sh, lib/Solver/MetaSMTSolver.cpp
This patch also removes support for boolector-1.5.x, which is very old now and requires a workaround.
I also have made some minor cosmetic changes which I feel improve the code a bit.
=> Add support for boolector-2.2.0

lib/Module/RaiseAsm.cpp
=> Support for Darwin platform in RaiseAsm pass

CMakeLists.txt
Fixes a few very minor problems I noticed when I was modifying this code in my fork of KLEE.
=> [CMake] uclibc detection tidy

include/klee/Expr.h, lib/Expr/Expr.cpp
This addresses issues discussed in #515
=> Fix Expr::compare

tools/klee-stats/CMakeLists.txt
=> Fixed the issue of klee-stats not being copied to bin/

lib/Core/Executor.cpp
=> Revert "Increased the type size for the stop-after-n-instructions option to a…"

lib/Solver/STPSolver.cpp
=> Added error message when STP fails to fork.

test/Replay/libkleeruntest/replay_invalid_klee_assume.c, test/Replay/libkleeruntest/replay_invalid_klee_choose.c, test/Replay/libkleeruntest/replay_invalid_klee_range.c, test/Replay/libkleeruntest/replay_invalid_num_objects.c, test/Replay/libkleeruntest/replay_invalid_object_names.c, test/Replay/libkleeruntest/replay_invalid_object_size.c, test/Replay/libkleeruntest/replay_posix_runtime.c, test/Replay/libkleeruntest/replay_simple.c, test/Replay/libkleeruntest/replay_two_objects.c
This PR resolves #591 (and makes @ccadar happy)
=> Fix linker compatibility under macOS

lib/Core/Executor.cpp, test/regression/2017-02-21-pathOS-id.c
Separated patch according to #579
=> Fix internal fork without new pathOS.id

include/klee/Interpreter.h, lib/Core/Executor.cpp, lib/Core/Executor.h, test/regression/2017-03-23-early-exit-log-stats.c, tools/klee/main.cpp
**DO NOT MERGE**
[WIP] Fix bug where stats would not be updated on early exit caused by finding a bug with the `-exit-on-error` option enabled.
=> [WIP] Fix bug where stats would not be updated on early exit

include/klee/CommandLine.h, include/klee/Solver.h, include/klee/util/Assignment.h, lib/Basic/CmdLineOptions.cpp, lib/Basic/ConstructSolverChain.cpp, lib/Expr/Assigment.cpp, lib/Solver/AssignmentValidatingSolver.cpp
Add `AssignmentValidatingSolver`. It's purpose is to check any computed
assignments against the corresponding `Query` object and check the
assignment evaluates correctly.
This can be switched on using `-debug-assignment-validating-solver`
on the command line.
=> Add `AssignmentValidatingSolver`

.travis.yml, .travis/install-llvm-and-runtime-compiler.sh, .travis/install-tcmalloc.sh, .travis/klee.sh, .travis/solvers.sh, .travis/stp.sh, .travis/testing-utils.sh, .travis/z3.sh
This PR will fail **a lot**, since it requires some deep modifications.
MacOS support added through [homebrew](https://brew.sh) through personalized [KLEE repository](https://github.com/andreamattavelli/homebrew-klee).
=> Travis-CI target for macOS

.travis/install-llvm-and-runtime-compiler.sh, .travis/install-tcmalloc.sh, .travis/klee.sh, .travis/stp.sh, .travis/testing-utils.sh, .travis/z3.sh, Dockerfile
#595 broke the Docker image build.
=> [Docker] Unbreak build.

CMakeLists.txt, README-CMake.md, runtime/CMakeLists.txt, runtime/Makefile.cmake.bitcode.rules
This fixes #631 and a few other minors issues.
=> [CMake] bitcode build system fixes

test/lit.cfg
This is useful for testing ranges. Especially when tests are run on
later LLVM versions.
=> test: lit, add geq/lt-llvm- configs

.travis/metaSMT.sh
[TravisCI] Check if `METASMT_VERSION` is set and abort if it is not
set. Also exit if any of the commands in `.travis/metaSMT.sh` fail.
=> [TravisCI] Check if `METASMT_VERSION` is set

test/Feature/LongDouble.c
This fixes #664.
As reported by @jirislaby the `test/Feature/LongDouble.cpp` test
fails to compile with Clang 3.4 due to new changes the libstdc++
headers. This ends up giving errors like
```
In file included from /home/abuild/rpmbuild/BUILD/klee-1.3.0+20170409/test/Feature/LongDouble.cpp:12:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/cstdlib:77:
/usr/bin/../lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/std_abs.h:101:3: error: unknown type name '__float128'
__float128
^
/usr/bin/../lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/std_abs.h:102:7: error: unknown type name '__float128'
abs(__float128 __x)
^
2 errors generated.
```
Clang 4.0 seems fine with this source file so the problem has already
been addressed …
=> Fix test failure on systems with libstdc++ corresponding to gcc7.

lib/Core/Executor.cpp
=> Added location info for external calls and improved a message.

.travis.yml
=> Added caching of Homebrew downloads

test/Feature/LongDouble.c
=> Cleanup tests for last LLVM 2.9 references

.travis.yml, .travis/stp.sh
- Added BOOST library to compile full version of STP (this will also be reflected in Docker)
- Build will now stop on errors
=> [TravisCI] Some fixes for STP scripts

include/klee/Internal/ADT/DiscretePDF.inc, lib/Basic/Statistics.cpp, lib/Core/Executor.cpp, lib/Core/Memory.cpp, lib/Core/StatsTracker.cpp, lib/Expr/ExprSMTLIBPrinter.cpp, lib/Module/RaiseAsm.cpp, lib/Support/FileHandling.cpp, lib/Support/TreeStream.cpp, tools/klee/main.cpp
Fixes klee/klee#717
delete on null pointer is always safe.
=> Remove unnecessary null pointer checks

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp
First step toward addressing #710
=> Added support for hiding command-line options

CMakeLists.txt
=> [cmake]Fix detection of non-standard path for tcmalloc

.travis.yml
=> [TravisCI] Bumped xcode version for TravisCI

.travis.yml, .travis/klee.sh, README.md, codecov.yml
TODO to make this PR work as intended:
@delcypher can you please double-check that I am invoking CMake correctly?
=> [Travis-CI] Added codecov.io support

Dockerfile
pull request for issue #816 wishlist: add wllvm to Dockerimage
=> add wllvm to the python packages to be installed

lib/Core/Executor.cpp, lib/Module/LowerSwitch.cpp
non-llvm-specific preparation for llvm 5.0.
=> Llvm 50 prep

.travis/z3.sh
Do not merge yet. Let travis decide.
=> [WIP] Fix python2 linking

lib/Core/Executor.cpp, lib/Core/ExecutorUtil.cpp, test/Feature/AddressOfLabels.c, test/Feature/AddressOfLabelsSymbolic.c
=> Add blockaddress and indirectbr

runtime/POSIX/fd.c, test/Runtime/POSIX/FileTime.c
Extends #855 by fixing test case
=> Yxliang01 fix posix runtime utimes

lib/Expr/ExprPPrinter.cpp
As requested by @ccadar in #892, this commit is factored out into its own pull request.
=> Typefix in ExprPPrinter.cpp

test/TestRunner.sh
=> Removed obsolete script

lib/Core/ExternalDispatcher.cpp
@MartinNowack addresses comment made by @adrianherrera in #385
=> ExternalDispatcher: setErrorStr for EngineBuilder

include/klee/SolverImpl.h, lib/Core/MemoryManager.h, lib/Core/SeedInfo.h
A couple of includes were missing and hidden by different include order in different files.
This adds them.
=> Fix missing includes and declarations

scripts/build/run-coverage.sh
Merge unittest coverage results and system tests coverage results
into one coverage report.
=> Workaround for flaky coverage

CMakeLists.txt, include/klee/Config/config.h.cmin, runtime/POSIX/fd.h, test/CMakeLists.txt, tools/klee-replay/CMakeLists.txt, tools/klee-replay/file-creator.c, tools/klee-replay/klee-replay.c, tools/klee-replay/klee-replay.h
At least it compiles and the test suite passes. This PR also fixes #984 and there was an unsuccessful attempt to solve this issue in #813.
=> Add support for OSX to klee-replay

include/klee/Internal/Support/CompressionStream.h, include/klee/Internal/Support/FileHandling.h, include/klee/Interpreter.h, lib/Core/Executor.cpp, lib/Core/Executor.h, lib/Core/ExecutorTimers.cpp, lib/Core/StatsTracker.cpp, lib/Core/StatsTracker.h, lib/Solver/QueryLoggingSolver.cpp, lib/Solver/QueryLoggingSolver.h, lib/Solver/Z3Solver.cpp, lib/Support/CompressionStream.cpp, lib/Support/FileHandling.cpp, tools/klee/main.cpp
Just a few changes to remove duplicated code, changing the signature of compressed_fd_ostream and fixing two error messages to reflect the actual file extension.
=> File handling refactoring

test/ArrayOpt/test-mix.c, test/ArrayOpt/test_and.c, test/ArrayOpt/test_array_index_array.c, test/ArrayOpt/test_array_index_array_diffsize.c, test/ArrayOpt/test_cache.c, test/ArrayOpt/test_const_arr-idx.c, test/ArrayOpt/test_expr_complex.c, test/ArrayOpt/test_expr_simple.c, test/ArrayOpt/test_feasible.c, test/ArrayOpt/test_hybrid.c, test/ArrayOpt/test_multindex.c, test/ArrayOpt/test_new.c, test/ArrayOpt/test_nier.c, test/ArrayOpt/test_noncontiguous_idx.c, test/ArrayOpt/test_position.c, test/ArrayOpt/test_sub_idx.c, test/ArrayOpt/test_var_idx.c, test/Concrete/CMakeLists.txt, test/Concrete/Makefile.cmake.test.in, test/Feature/EscapingFunctions.c, test/Feature/EscapingFunctionsAlias.c, test/Runtime/FreeStanding/freestanding_only.c, test/Runtime/POSIX/CanonicalizeFileName.c, test/Runtime/POSIX/TestMain.c, test/Runtime/POSIX/Usage.c, test/regression/2018-05-17-replay-short-names.c, test/regression/2018-10-01-double-segfault.c
Some tests were still missing `%O0opt`.
=> add %OOopt to recently added tests and Concrete

utils/hacks/TreeGraphs/DumpTreeStream.py
the function name is "getTreeStream" but here's a spelling error
=> fix a bug in a function call

test/CXX/ArrayNew.cpp, test/CXX/LandingPad.cpp, test/CXX/New.cpp, test/CXX/SimpleVirtual.cpp, test/CXX/StaticConstructor.cpp, test/CXX/StaticDestructor.cpp, test/CXX/Trivial.cpp, test/Dogfood/ImmutableSet.cpp, test/Feature/CallToUndefinedExternal.cpp, test/Feature/LargeReturnTypes.cpp, test/lit.cfg, test/lit.site.cfg.in
Travis seems to be fine with it.
=> tests: rename xxclang to clangxx

.travis.yml, lib/Core/Executor.cpp, lib/Module/KModule.cpp
That was much easier than expected. Local builds are already working.
=> Add support for LLVM 8.0

lib/Core/Searcher.cpp, lib/Core/UserSearcher.cpp
This addresses #https://github.com/klee/klee/issues/1049
=> --batching-search changes

.travis.yml, Dockerfile
Use `stp 2.3.3` and `klee-uclibc-v1.2`
Update `Dockerfile` with updated dependencies.
=> Update docker v2

lib/Core/SpecialFunctionHandler.cpp, lib/Module/RaiseAsm.cpp, test/Concrete/ConcreteTest.py
With this patches, only single test is failing.
=> Fix KLEE tests running on FreeBSD.

.travis.yml, scripts/build/p-klee-linux-ubuntu-16.04.inc, scripts/build/p-sqlite.inc, scripts/build/v-sanitizer_compiler.inc, scripts/build/v-sqlite.inc
@ccadar This fixes building the Docker image. Strange that this issue is not triggered by any other build setup.
=> Remove CC as requirement; automatically set by sanitizer_compiler

tools/klee-stats/klee-stats
This fixes handling of time in the grafana data source.
=> Fix handling of time in grafana

lib/Core/StatsTracker.cpp
We do this mainly to prevent the creation of new file descriptors during KLEE runs. I've also added:
```
sqlite3_config(SQLITE_CONFIG_SINGLETHREAD);
sqlite3_enable_shared_cache(0);
```
to prevent the use of mutexes and to disable the shared cache (should be off by default already).
https://www.sqlite.org/c3ref/c_config_covering_index_scan.html#sqliteconfigsinglethread
https://www.sqlite.org/sharedcache.html
@gdish Would be nice if you could test the Grafana backend with this patch.
=> StatsTracker: switch from TRUNCATE to WAL journal mode

tools/gen-bout/gen-bout.cpp, tools/klee-replay/file-creator.c, tools/klee-replay/klee-replay.c
That way we don't rely on optimisations and also should increase readability.
=> replace fprintf with fputs/fputc

Dockerfile, scripts/build/d-klee-linux-ubuntu.inc
Add missing file utility in docker images
Fixes #1164
=> Add missing file utility in docker image

tools/klee-replay/klee-replay.c
Fixes #1150 .
The new error message looks like:
`KLEE-REPLAY: ERROR: executable ./not-path: No such file or directory`
Can't write a test becase `lit` hates relative paths
=> [klee-replay] Fix relative executable paths

lib/Core/Executor.cpp, runtime/POSIX/fd.c, test/Runtime/POSIX/DirConsistency.c, test/regression/2015-08-05-invalid-fork.c, test/regression/2019-09-06-make-const-symbolic.c
Warn about cases like #248.
Fixes #248
=> Do not symbolize read-only objects

lib/Module/IntrinsicCleaner.cpp, test/Intrinsics/IsConstant.ll
This allowed me to move further with FreeBSD libc support. A part of https://github.com/klee/klee/issues/678
=> Implement @llvm.is.constant() intrinsic handling and add a test for it.

lib/Core/StatsTracker.cpp
Statistics encoded in `run.istats` were limited to a maximum number of 13 due to encoding in a `uint64_t` variable.
This approach has multiple limitations:
- a maximum number of 13 statistics were allowed
- a subtle bug can be triggered if many more statistics are added - independent of the selected statistics for `run.istats`
Depending on the linking order, statistics will get a different ID. Previously, the ID was used to shift a `1` to its position marking the statistic as being used.
This will lead to undefined behaveour if more than 63 statistics are used.
Using an `llvm::SmallBitVector` instead fixes both problems.
=> Remove statistics limit from istats.

.cirrus.yml
=> FreeBSD CI adjustments.

CMakeLists.txt, NEWS
Please let me know if I missed anything or would like to rephrase any part.
=> Release notes for KLEE 2.1

.travis.yml
I was glad to see this feature, as the overview of Travis CI was not that helpful in figuring out what job(s) failed without inspecting the job(s).
=> Named jobs in Travis CI for better visualization of results

.travis.yml
Trying to see if this fixed the macOS failures on the master branch...
=> Change the way bash is upgraded on macOS

.travis.yml
Testing the hypothesis in #1300
=> Remove secure vars

lib/Core/Searcher.cpp, lib/Core/Searcher.h, lib/Core/UserSearcher.cpp, test/Merging/easy_merge.c, test/Merging/incomplete_merge.c, test/Merging/loop_merge.c, test/Merging/merge_fail.c, test/Merging/nested_merge.c, test/Merging/split_merge.c
* C++11ify files
* add Doxygen documentation
* remove incompatibility check for merging searcher and random-path - this should work now (#1168)
=> Searcher cleanup

.travis.yml, test/CXX/StaticDestructor.cpp
…ructors (observed on macOS). Also made the test less fragile with respect to optimizations.
=> StaticDestructor.cpp test not working on macOS

runtime/klee-libc/__cxa_atexit.c, test/Runtime/klee-libc/atexit_order.c
=> Call functions in __cxa_atexit in reverse order 

runtime/CMakeLists.txt, runtime/Fortify/CMakeLists.txt, runtime/Fortify/fortify.c, runtime/Freestanding/CMakeLists.txt, runtime/Freestanding/fortify-fs.c, runtime/klee-libc/CMakeLists.txt, runtime/klee-libc/fortify-klibc.c, test/Runtime/FreeStanding/memcpy_chk.c, test/Runtime/FreeStanding/memcpy_chk_err.c, test/Runtime/Uclibc/strcpy_chk.c, test/Runtime/klee-libc/strcat_chk.c, tools/klee/main.cpp
=> Added support for -D_FORTIFY_SOURCE

tools/klee-replay/klee-replay.c
=> Do not redefine fgetc_unlocked and fputc_unlocked unconditionally.

.travis.yml
This simply updates the version of macOS used on Travis CI.  The current version is really old and might be responsible for the recent macOS failures we've been seeing. 
---
- [x ] The PR addresses a single issue.  In other words, if some parts of a PR could form another independent PR, you should break this PR into multiple smaller PRs.
=> Use a more recent version of macOS in Travis CI

.github/workflows/build.yaml, .travis.yml, lib/Core/Executor.cpp, lib/Core/Executor.h, lib/Core/ExternalDispatcher.cpp, lib/Core/GetElementPtrTypeIterator.h, lib/Core/StatsTracker.cpp, lib/Module/InstructionInfoTable.cpp, lib/Module/KModule.cpp, lib/Module/ModuleUtil.cpp, lib/Module/Optimize.cpp, lib/Module/RaiseAsm.cpp, tools/klee/main.cpp
This PR contains remaining changes to support LLVM 11.
----------------------------------
=> Add support for LLVM 11 (LLVM 11 2/2)

CMakeLists.txt, runtime/CMakeLists.txt
Automatically detect if 32bit bitcode files can be built.
In this case, build runtime library with 32bit as well.
=> Only build 32bit runtime libraries if supported by platform

NEWS
=> Release notes for v2.2

CMakeLists.txt
- [x ] Spellcheck all messages added to the codebase, all comments, as well as commit messages.
=> Update version to 2.2

CMakeLists.txt
- [] Add test cases exercising the code you added or modified.  We expect [system and/or unit test cases](https://klee.github.io/docs/developers-guide/#regression-testing-framework) for all non-trivial changes.  After you submit your PR, you will be able to see a [Codecov report](https://docs.codecov.io/docs/pull-request-comments) telling you which parts of your patch are not covered by the regression test suite.  You will …
=> Advancing version to 2.3-pre

.cirrus.yml
=> FreeBSD CI: Use FreeBSD 12.2 instead of 12.1 and LLVM 9 instead of LLVM 8

runtime/POSIX/klee_init_env.c
=> posix runtime: remove dead branch

runtime/klee-libc/mempcpy.c, test/Runtime/klee-libc/mempcpy.c
Remove the code duplication and just use `memcpy`.
----
=> klee-libc: simplify mempcpy

runtime/POSIX/fd.c, test/Runtime/POSIX/GetcwdFail.c
=> Fix malloc/0-size handling in getcwd

.github/pull_request_template.md
Summary: Improved the PR template by
1. Making it more succinct
2. Adding a summary
3. Moving the explanation at the bottom and moving the detailed documentation to the website
This PR uses the new template. 
Supersedes #1362.
Checklist:
- Logical sequence of commits:
- Comments:
- Formatting:
- Test cases:
Thank you for contributing to KLEE. We are looking forward to reviewing your PR. However, given the small number of active reviewers and our limited time, it might take a while to do so. We aim to get back to each PR within one month, and often do so within one week.
To review your PR, please add a summary of the proposed changes and ensure all items are fulfilled in the checklist above, by placing an "x" inside each applicable pair of brackets. More details about each item can be …
=> Improved PR template by making it more succinct.

runtime/POSIX/fd_init.c, runtime/POSIX/klee_init_env.c
Add malloc checks as discussed in #1346.
---
=> Fix runtime mallocs

test/Runtime/POSIX/Futimesat.c, test/lit.cfg
This MR resolves #1411.
I am pleased to offer you a patch to the test case. It doesn't change the POSIX model at all. However, checks were changed as though it was concrete execution.
=> Test failure for WSL 1

.github/workflows/build.yaml, .travis.yml, lib/Core/Executor.cpp, lib/Module/IntrinsicCleaner.cpp, scripts/build/p-klee-linux-ubuntu.inc, scripts/build/p-libcxx-linux-ubuntu.inc, scripts/build/p-llvm-linux-ubuntu.inc, test/Intrinsics/MinMax.ll, test/Intrinsics/abs-no-overflow.ll, test/Intrinsics/abs-overflow.ll, test/lit.cfg
This PR adds support for LLVM 12 and I'll convert it to a regular one once LLVM 12 is released. Fortunately, much less work was required this time.
=> Add support for LLVM 12

.github/workflows/build.yaml, .travis.yml, lib/Core/ExternalDispatcher.cpp, lib/Expr/Expr.cpp, lib/Module/IntrinsicCleaner.cpp, lib/Support/FileHandling.cpp, test/Concrete/GlobalUndef.ll, test/lit.cfg, tools/kleaver/main.cpp, tools/klee/main.cpp
This PR adds support for LLVM 13.
**EDIT**: Update checklist after Codecov report. Btw, the :cl: emoji in 4d1661c is not present in the commit message itself, it's just a bug on GitHub's side.
=> Add support for LLVM 13

include/klee/Core/TerminationTypes.h, lib/Core/Executor.cpp, lib/Core/Executor.h, lib/Core/MergeHandler.cpp, lib/Core/SpecialFunctionHandler.cpp
The reasoning here is to track all path terminations: esp. for debugging or visualising a persistent process tree (with or without full MoKlee integration) it is helpful to know the exact reason (`StateTerminationType`) why a path terminated.
---
=> Introduce termination categories

include/klee/Core/BranchTypes.h, lib/Core/Executor.cpp, lib/Core/Executor.h, lib/Core/PTree.cpp, lib/Core/PTree.h, lib/Core/SpecialFunctionHandler.cpp, unittests/Searcher/SearcherTest.cpp
This PR extends #1343 and keeps track of the different branch types.
---
=> Introduce BranchTypes (requires #1343)

Dockerfile
Here is the version bump for Google Test discussed in #1458.
=> Dockerfile: use Google Test 1.11.0

lib/Support/MemoryUsage.cpp
Fixed a wrong type when computing memory usage on macOS
=> Fixed a wrong type when computing memory usage on macOS

Dockerfile
=> Update dependencies in Docker files.

CMakeLists.txt, NEWS
=> Release notes for KLEE 2.3

CMakeLists.txt
=> Set version number to 3.0-pre

test/Feature/BitcastAlias.ll, test/Feature/BitcastAliasMD2U.ll, test/Feature/ConstantArray.ll, test/Feature/ConstantStruct.ll, test/Feature/GetElementPtr.ll, test/Feature/GlobalVariable.ll, test/Feature/ImpliedValue.c.failing, test/Feature/InsertExtractValue.ll, test/Feature/asm_lifting.ll, test/Intrinsics/IntrinsicTrap.ll, test/Intrinsics/Overflow.ll, test/Intrinsics/OverflowMul.ll, test/Intrinsics/Saturating.ll, test/lit.cfg, test/regression/2007-08-01-bool-zext-in-call.ll, test/regression/2007-08-16-invalid-constant-value.c, test/regression/2018-10-28-alias-to-alias.ll, test/regression/2018-10-30-llvm-pr39177.ll, test/regression/2019-08-01-trap-instruction.ll, test/regression/2019-08-02-missing-switch-default.ll
This PR is similar to #1401 but for LLVM tools.
=> tests: invoke LLVM tools through their corresponding macros

lib/Core/SpecialFunctionHandler.cpp
use size() to get N in bind(), just like the way in prepare().
=> Make bind() in SpecialFunctionHandler.cpp more readable.

lib/Core/ImpliedValue.cpp, lib/Solver/FastCexSolver.cpp, lib/Solver/IndependentSolver.cpp, lib/Solver/Solver.cpp, test/Expr/ReadExprConsistency.c, test/Replay/klee-replay/KleeZesti.c, test/Replay/libkleeruntest/replay_klee_prefer_cex.c, test/Runtime/POSIX/SymFileConsistency.c, test/regression/2014-09-13-debug-info.c, unittests/Expr/ArrayExprTest.cpp
Fixes the spelling of some words that I found throughout the comments and code of the project. Has no effect on the program execution, just for the sake of clarity.
=> Spelling Fixes

Dockerfile
Install tabulate package for klee-stats to work when used within KLEE Docker.
- [X ] The PR addresses a single issue.  If it can be divided into multiple independent PRs, please do so.
- [X ] The PR is divided into a logical sequence of commits OR a single commit is sufficient.
- [X ] There are no unnecessary commits (e.g. commits fixing issues in a previous commit in the same PR).
- [X ] Each commit has a meaningful message documenting what it does.
- [X ] All messages added to the codebase, all comments, as well as commit messages are spellchecked.
- [X ] The code is commented OR not applicable/necessary.
- [X ] The patch is formatted via clang-format OR not applicable (if explicitly overridden leave unchecked and explain).
- [X ] There are test cases for the code you added or modified …
=> Update Dockerfile to install tabulate

lib/Core/Executor.cpp, lib/Module/IntrinsicCleaner.cpp, test/Intrinsics/FMulAdd.ll
Add support for `llvm.fma` and `llvm.fmuladd` intrinsics.
=> Intrinsics: Add support for `@llvm.f{ma,muladd}.f*`

.github/workflows/build.yaml
Implements coverage analysis for z3 and stp in a more lightweight manner than #1531. This PR simply runs the coverage analysis twice and leaves the merging to codecov.io, [which they claim to support](https://docs.codecov.com/docs/merging-reports).
Note that the original Z3 test run is not needed anymore, as it is performed as a code coverage run instead. As the original name is protected, merging this PR should require changing the github settings for protected actions.
=> Perform coverage analysis for z3 as well

include/klee/Solver/Solver.h, lib/Solver/ConstructSolverChain.cpp, lib/Solver/ValidatingSolver.cpp
[ASAN runs of the crosscheck core solver functionality exposed a memory leak](https://github.com/klee/klee/runs/7123590267?check_suite_focus=true#step:4:643) which is fixed in this PR.
=> Fix memory leak in crosscheck core solver mechanism

test/Feature/const_array_opt1.c
Fixes test `Feature/const_array_opt1`.
The `grep` command was not called since the `RUN` directive was missing.
I fixed it by adding an equivalent `FileCheck` call that should also increase readability.
=> fix output check in test const_arr_opt1

.github/workflows/build.yaml, test/Solver/CrosscheckCoreStpZ3.c, test/Solver/DummySolver.c, test/Solver/ExerciseSolver.c.inc, test/Solver/NoSTP.c, test/Solver/NoZ3.c, test/Solver/ValidatingSolver.c
Adds a few more tests to push those code coverage numbers up.
=> Add a few simple solver tests

scripts/build/p-clang-osx.inc, scripts/build/p-llvm-osx.inc
=> Do not escape "@".  This triggers an error now in the CI.

include/klee/Core/BranchTypes.h, include/klee/Core/TerminationTypes.h, include/klee/Solver/SolverStats.h, lib/Core/CoreStats.cpp, lib/Core/CoreStats.h, lib/Core/ExecutionState.h, lib/Core/Executor.cpp, lib/Core/Executor.h, lib/Core/ExternalDispatcher.cpp, lib/Core/MergeHandler.cpp, lib/Core/SpecialFunctionHandler.cpp, lib/Core/StatsTracker.cpp, lib/Core/TimingSolver.cpp, lib/Solver/DummySolver.cpp, lib/Solver/MetaSMTSolver.cpp, lib/Solver/STPSolver.cpp, lib/Solver/SolverStats.cpp, lib/Solver/Z3Solver.cpp, test/Feature/KleeStatsBranches.c, test/Feature/KleeStatsTermClasses.c, tools/kleaver/main.cpp, tools/klee-stats/klee-stats, tools/klee/main.cpp
This PR adds the following statistics:
* InhibitedForks
* QCacheHits/Misses
* ExternalCalls
* Allocations (this one exposes the existing one, in other projects I just count calls to `executeAlloc`)
* renames States to ActiveStates (active), adds States (total)
* renames numQueries/Queries to SolverQueries (into constraint solver), adds Queries (into solver chain)
* branch types
* termination classes
Notes:
* The termination class commit adds three new termination functions to cover all classes (A "class" categorises termination types. I don't want to expose all termination types as we have quite a lot.) and adds two classes (EarlyUser and EarlyAlgorithm).
* I've replaced usages of `terminateOnError` with `terminateOnProgramError` to reflect the termination class and be more consistent
* …
=> Add more statistics (incl. branches and termination classes)

test/Coverage/ReplayOutDir.c, test/Feature/AddressOfLabelsSymbolic.c, test/Feature/ExprLogging.c, test/Feature/WithLibc.c, test/Feature/arithmetic-right-overshift-sym-conc.c, test/Runtime/klee-libc/bcmp.c, test/regression/2016-06-28-div-zero-bug.c
=> tests: add some missing headers

lib/Core/Executor.cpp
This is a patch that I've made long ago and which I rediscovered last week.  Somehow I forgot to post a PR at that time.  Tested with a 32bit build of KLEE.
According to i686 System V ABI 2.1.1, long double must be aligned to 4 bytes.  Thus, its size with padding is 12 bytes.  Prior to this change only 10 bytes were used.
This commit fixes the following out of bound pointer access.
```
$ clang -m32 -O0 -Xclang -disable-O0-optnone -g -emit-llvm -c test/Feature/VarArgAlignment.c -o varalign.bc
$ klee varalign.bc
KLEE: output directory is "/home/lukas/klee/klee-out-19"
KLEE: Using Z3 solver backend
KLEE: WARNING: undefined reference to function: printf
KLEE: WARNING ONCE: calling external: printf(44120064, 1, 2, 3) at test/Feature/VarArgAlignment.c:23 17
i1, i2, i3: 1, 2, 3
l1: 4
i4: 5
ld1: …
```
=> Core/Executor: long double on i686 must be aligned to 4 bytes

include/klee/Support/CompilerWarning.h
Remove warning/errors for older LLVM versions.
=> Remove additional quotation marks

include/klee/Solver/Common.h, include/klee/Solver/IncompleteSolver.h, include/klee/Solver/Solver.h, include/klee/Solver/SolverImpl.h, lib/Core/Executor.cpp, lib/Core/Executor.h, lib/Core/TimingSolver.h, lib/Solver/AssignmentValidatingSolver.cpp, lib/Solver/CachingSolver.cpp, lib/Solver/CexCachingSolver.cpp, lib/Solver/ConstructSolverChain.cpp, lib/Solver/CoreSolver.cpp, lib/Solver/DummySolver.cpp, lib/Solver/FastCexSolver.cpp, lib/Solver/IncompleteSolver.cpp, lib/Solver/IndependentSolver.cpp, lib/Solver/KQueryLoggingSolver.cpp, lib/Solver/MetaSMTSolver.cpp, lib/Solver/MetaSMTSolver.h, lib/Solver/QueryLoggingSolver.cpp, lib/Solver/QueryLoggingSolver.h, lib/Solver/SMTLIBLoggingSolver.cpp, lib/Solver/STPSolver.cpp, lib/Solver/Solver.cpp, lib/Solver/ValidatingSolver.cpp, lib/Solver/Z3Solver.cpp, tools/kleaver/main.cpp, unittests/Solver/SolverTest.cpp, unittests/Solver/Z3SolverTest.cpp
This PR consists of only the changes to Solver ownership factored out from #1601.
=> Solver ownership

include/klee/KDAlloc/allocator.h, include/klee/KDAlloc/suballocators/slot_allocator.h
With infinite quarantine, we actually only need a single `size_t` to perform sized allocations. Neither quarantine nor the bitmap is needed for the slot allocator, as it will always return the lowest possible slot after quarantine. Since quarantine is infinite, it will therefore return the slots in the following order: 0, 1, 2, 3, ... - a sequence that can be trivially encoded by only storing the next element. (Remember that it gets converted to an address using `control.baseAddress + control.convertIndexToPosition(index)`, which transforms the sequence to be more fitting for its purpose.)
This PR implements this by adding a template parameter (and specialization)  for the `SlotAllocator` class. While that makes everything very easy on that side of the issue, it means that we must be a …
=> Further improve KDAlloc memory usage with infinite quarantine

Dockerfile
Use newer LLVM 13 for the Docker image
=> Use recommended LLVM 13 as part of the Docker image

.github/workflows/docker_release_push.yml
=> Build and push Docker image as part of a release

CMakeLists.txt, NEWS
Release notes for KLEE 3.0.  Please let me know if you see any issues, omissions, etc.
=> Release notes for KLEE 3.0

CMakeLists.txt
=> Changed version to 3.1-pre

lib/Core/MemoryManager.cpp
Fixed a format specifier pointed to by a compiler warning.
=> Fixed a format specifier pointed to by a compiler warning.

lib/Core/Executor.cpp, lib/Core/MergeHandler.cpp, lib/Core/SpecialFunctionHandler.cpp, tools/klee/main.cpp
Small improvements to the help menu
=> Small improvements to the help menu

.cirrus.yml
=> Switch to FreeBSD 14 and 13.2; Use LLVM 13

CMakeLists.txt, NEWS
Release notes for KLEE 3.1. Please let me know if you spot any issues.
=> Release notes for KLEE 3.1

NEWS
Final changes to release notes for v3.1
=> Final changes to release notes for v3.1

CMakeLists.txt
=> Setting version to 3.2-pre

.github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md, CMakeLists.txt, LICENSE.TXT, NEWS, README.md
New domain name klee-se.org!  Updating links.
=> New domain name klee-se.org, updating links.

test/CMakeLists.txt
TARGET_TRIPLE was renamed to LLVM_TARGET_TRIPLE since LLVM 15: https://github.com/llvm/llvm-project/commit/0c0f6cfb7b9fab0ee69ef67ed95c194698c9d794
=> TARGET_TRIPLE was renamed to LLVM_TARGET_TRIPLE since LLVM 15

.github/workflows/build.yaml
Switch to LLVM 13 as the default version in the CI
=> Switch to LLVM 13 as the default version in the CI

.github/workflows/build.yaml, .github/workflows/differential-shellcheck.yml, .github/workflows/docker_release_push.yml, .shellcheckrc
- Add ShellCheck configuration file with setting default shell to bash
- Update ShellCheck and Checkout GHAs to their latest versions
Please see the commit messages for more information.
Related to:
- https://github.com/klee/klee/pull/1713
/cc @MartinNowack
=> Update ShellCheck to latest version & add ShellCheck configuration

Dockerfile
Install 'less' in the Docker container
=> Install 'less' in the Docker container

.github/workflows/build.yaml, scripts/build/p-klee-osx.inc, scripts/build/run-tests.sh
Fixes detection and deletion of `klee` in `PATH` handling.
Update handling of Python-dependencies under MacOS.
=> Fix test runner and update Python-based dependency handling for MacOS setups

scripts/build/common-functions, scripts/build/p-klee-linux-ubuntu.inc, scripts/build/p-stp-linux-ubuntu.inc, scripts/build/p-stp.inc
Fix compilation of the STP master branch -- it now depends on ABC and uses submodules: https://github.com/stp/stp/pull/496.
=> Fix compilation of the STP master branch -- it now depends on ABC and uses submodules
